// Code generated by ent, DO NOT EDIT.

package apikeymonthcreditbucket

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldEQ(FieldUpdatedAt, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v uuid.UUID) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldEQ(FieldAPIKeyID, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldEQ(FieldProjectID, v))
}

// Month applies equality check predicate on the "month" field. It's identical to MonthEQ.
func Month(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldEQ(FieldMonth, v))
}

// QuotaMilli applies equality check predicate on the "quota_milli" field. It's identical to QuotaMilliEQ.
func QuotaMilli(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldEQ(FieldQuotaMilli, v))
}

// AllocationActive applies equality check predicate on the "allocation_active" field. It's identical to AllocationActiveEQ.
func AllocationActive(v bool) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldEQ(FieldAllocationActive, v))
}

// ChargedMilli applies equality check predicate on the "charged_milli" field. It's identical to ChargedMilliEQ.
func ChargedMilli(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldEQ(FieldChargedMilli, v))
}

// PendingMilli applies equality check predicate on the "pending_milli" field. It's identical to PendingMilliEQ.
func PendingMilli(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldEQ(FieldPendingMilli, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldLTE(FieldUpdatedAt, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v uuid.UUID) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v uuid.UUID) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...uuid.UUID) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...uuid.UUID) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldNotIn(FieldProjectID, vs...))
}

// MonthEQ applies the EQ predicate on the "month" field.
func MonthEQ(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldEQ(FieldMonth, v))
}

// MonthNEQ applies the NEQ predicate on the "month" field.
func MonthNEQ(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldNEQ(FieldMonth, v))
}

// MonthIn applies the In predicate on the "month" field.
func MonthIn(vs ...time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldIn(FieldMonth, vs...))
}

// MonthNotIn applies the NotIn predicate on the "month" field.
func MonthNotIn(vs ...time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldNotIn(FieldMonth, vs...))
}

// MonthGT applies the GT predicate on the "month" field.
func MonthGT(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldGT(FieldMonth, v))
}

// MonthGTE applies the GTE predicate on the "month" field.
func MonthGTE(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldGTE(FieldMonth, v))
}

// MonthLT applies the LT predicate on the "month" field.
func MonthLT(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldLT(FieldMonth, v))
}

// MonthLTE applies the LTE predicate on the "month" field.
func MonthLTE(v time.Time) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldLTE(FieldMonth, v))
}

// QuotaMilliEQ applies the EQ predicate on the "quota_milli" field.
func QuotaMilliEQ(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldEQ(FieldQuotaMilli, v))
}

// QuotaMilliNEQ applies the NEQ predicate on the "quota_milli" field.
func QuotaMilliNEQ(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldNEQ(FieldQuotaMilli, v))
}

// QuotaMilliIn applies the In predicate on the "quota_milli" field.
func QuotaMilliIn(vs ...int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldIn(FieldQuotaMilli, vs...))
}

// QuotaMilliNotIn applies the NotIn predicate on the "quota_milli" field.
func QuotaMilliNotIn(vs ...int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldNotIn(FieldQuotaMilli, vs...))
}

// QuotaMilliGT applies the GT predicate on the "quota_milli" field.
func QuotaMilliGT(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldGT(FieldQuotaMilli, v))
}

// QuotaMilliGTE applies the GTE predicate on the "quota_milli" field.
func QuotaMilliGTE(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldGTE(FieldQuotaMilli, v))
}

// QuotaMilliLT applies the LT predicate on the "quota_milli" field.
func QuotaMilliLT(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldLT(FieldQuotaMilli, v))
}

// QuotaMilliLTE applies the LTE predicate on the "quota_milli" field.
func QuotaMilliLTE(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldLTE(FieldQuotaMilli, v))
}

// AllocationActiveEQ applies the EQ predicate on the "allocation_active" field.
func AllocationActiveEQ(v bool) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldEQ(FieldAllocationActive, v))
}

// AllocationActiveNEQ applies the NEQ predicate on the "allocation_active" field.
func AllocationActiveNEQ(v bool) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldNEQ(FieldAllocationActive, v))
}

// ChargedMilliEQ applies the EQ predicate on the "charged_milli" field.
func ChargedMilliEQ(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldEQ(FieldChargedMilli, v))
}

// ChargedMilliNEQ applies the NEQ predicate on the "charged_milli" field.
func ChargedMilliNEQ(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldNEQ(FieldChargedMilli, v))
}

// ChargedMilliIn applies the In predicate on the "charged_milli" field.
func ChargedMilliIn(vs ...int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldIn(FieldChargedMilli, vs...))
}

// ChargedMilliNotIn applies the NotIn predicate on the "charged_milli" field.
func ChargedMilliNotIn(vs ...int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldNotIn(FieldChargedMilli, vs...))
}

// ChargedMilliGT applies the GT predicate on the "charged_milli" field.
func ChargedMilliGT(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldGT(FieldChargedMilli, v))
}

// ChargedMilliGTE applies the GTE predicate on the "charged_milli" field.
func ChargedMilliGTE(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldGTE(FieldChargedMilli, v))
}

// ChargedMilliLT applies the LT predicate on the "charged_milli" field.
func ChargedMilliLT(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldLT(FieldChargedMilli, v))
}

// ChargedMilliLTE applies the LTE predicate on the "charged_milli" field.
func ChargedMilliLTE(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldLTE(FieldChargedMilli, v))
}

// PendingMilliEQ applies the EQ predicate on the "pending_milli" field.
func PendingMilliEQ(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldEQ(FieldPendingMilli, v))
}

// PendingMilliNEQ applies the NEQ predicate on the "pending_milli" field.
func PendingMilliNEQ(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldNEQ(FieldPendingMilli, v))
}

// PendingMilliIn applies the In predicate on the "pending_milli" field.
func PendingMilliIn(vs ...int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldIn(FieldPendingMilli, vs...))
}

// PendingMilliNotIn applies the NotIn predicate on the "pending_milli" field.
func PendingMilliNotIn(vs ...int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldNotIn(FieldPendingMilli, vs...))
}

// PendingMilliGT applies the GT predicate on the "pending_milli" field.
func PendingMilliGT(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldGT(FieldPendingMilli, v))
}

// PendingMilliGTE applies the GTE predicate on the "pending_milli" field.
func PendingMilliGTE(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldGTE(FieldPendingMilli, v))
}

// PendingMilliLT applies the LT predicate on the "pending_milli" field.
func PendingMilliLT(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldLT(FieldPendingMilli, v))
}

// PendingMilliLTE applies the LTE predicate on the "pending_milli" field.
func PendingMilliLTE(v int64) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.FieldLTE(FieldPendingMilli, v))
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.APIKeyMonthCreditBucket) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.APIKeyMonthCreditBucket) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.APIKeyMonthCreditBucket) predicate.APIKeyMonthCreditBucket {
	return predicate.APIKeyMonthCreditBucket(sql.NotPredicates(p))
}
