// Code generated by ent, DO NOT EDIT.

package quotaadjustmentaudit

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the quotaadjustmentaudit type in the database.
	Label = "quota_adjustment_audit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldOwnerType holds the string denoting the owner_type field in the database.
	FieldOwnerType = "owner_type"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldActorUserID holds the string denoting the actor_user_id field in the database.
	FieldActorUserID = "actor_user_id"
	// FieldOldQuotaMilli holds the string denoting the old_quota_milli field in the database.
	FieldOldQuotaMilli = "old_quota_milli"
	// FieldNewQuotaMilli holds the string denoting the new_quota_milli field in the database.
	FieldNewQuotaMilli = "new_quota_milli"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// Table holds the table name of the quotaadjustmentaudit in the database.
	Table = "quota_adjustment_audits"
)

// Columns holds all SQL columns for quotaadjustmentaudit fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldOwnerType,
	FieldOwnerID,
	FieldActorUserID,
	FieldOldQuotaMilli,
	FieldNewQuotaMilli,
	FieldReason,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// OldQuotaMilliValidator is a validator for the "old_quota_milli" field. It is called by the builders before save.
	OldQuotaMilliValidator func(int64) error
	// NewQuotaMilliValidator is a validator for the "new_quota_milli" field. It is called by the builders before save.
	NewQuotaMilliValidator func(int64) error
	// ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	ReasonValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OwnerType defines the type for the "owner_type" enum field.
type OwnerType string

// OwnerType values.
const (
	OwnerTypeProject OwnerType = "project"
	OwnerTypeAPIKey  OwnerType = "api_key"
)

func (ot OwnerType) String() string {
	return string(ot)
}

// OwnerTypeValidator is a validator for the "owner_type" field enum values. It is called by the builders before save.
func OwnerTypeValidator(ot OwnerType) error {
	switch ot {
	case OwnerTypeProject, OwnerTypeAPIKey:
		return nil
	default:
		return fmt.Errorf("quotaadjustmentaudit: invalid enum value for owner_type field: %q", ot)
	}
}

// OrderOption defines the ordering options for the QuotaAdjustmentAudit queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByOwnerType orders the results by the owner_type field.
func ByOwnerType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerType, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByActorUserID orders the results by the actor_user_id field.
func ByActorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorUserID, opts...).ToFunc()
}

// ByOldQuotaMilli orders the results by the old_quota_milli field.
func ByOldQuotaMilli(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOldQuotaMilli, opts...).ToFunc()
}

// ByNewQuotaMilli orders the results by the new_quota_milli field.
func ByNewQuotaMilli(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNewQuotaMilli, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}
