// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Size: 128, SchemaType: map[string]string{"postgres": "citext"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending_mentor", "pending_teacher", "approved", "active", "rejected", "revoked"}, Default: "pending_mentor"},
		{Name: "key_hash", Type: field.TypeBytes, Unique: true, Nullable: true},
		{Name: "key_prefix", Type: field.TypeString, Nullable: true, Size: 32},
		{Name: "claimed_at", Type: field.TypeTime, Nullable: true},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "owner_user_id", Type: field.TypeUUID},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_keys_projects_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[9]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "api_keys_users_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "apikey_owner_user_id_name",
				Unique:  true,
				Columns: []*schema.Column{APIKeysColumns[10], APIKeysColumns[3]},
				Annotation: &entsql.IndexAnnotation{
					Where: "status IN ('pending_mentor', 'pending_teacher', 'approved', 'active')",
				},
			},
			{
				Name:    "apikey_owner_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[10], APIKeysColumns[1]},
			},
			{
				Name:    "apikey_project_id_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[9], APIKeysColumns[4], APIKeysColumns[1]},
			},
			{
				Name:    "apikey_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[4], APIKeysColumns[1]},
			},
		},
	}
	// APIKeyAuditsColumns holds the columns for the "api_key_audits" table.
	APIKeyAuditsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "action", Type: field.TypeEnum, Enums: []string{"mentor_approved", "mentor_rejected", "teacher_approved", "teacher_rejected", "mentor_revoked"}},
		{Name: "comment", Type: field.TypeString, Nullable: true, Size: 1000},
		{Name: "api_key_id", Type: field.TypeUUID},
		{Name: "actor_user_id", Type: field.TypeUUID},
	}
	// APIKeyAuditsTable holds the schema information for the "api_key_audits" table.
	APIKeyAuditsTable = &schema.Table{
		Name:       "api_key_audits",
		Columns:    APIKeyAuditsColumns,
		PrimaryKey: []*schema.Column{APIKeyAuditsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_key_audits_api_keys_audits",
				Columns:    []*schema.Column{APIKeyAuditsColumns[4]},
				RefColumns: []*schema.Column{APIKeysColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "api_key_audits_users_api_key_audits",
				Columns:    []*schema.Column{APIKeyAuditsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "apikeyaudit_api_key_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{APIKeyAuditsColumns[4], APIKeyAuditsColumns[1]},
			},
			{
				Name:    "apikeyaudit_actor_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{APIKeyAuditsColumns[5], APIKeyAuditsColumns[1]},
			},
		},
	}
	// APIKeyModelsColumns holds the columns for the "api_key_models" table.
	APIKeyModelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "api_key_id", Type: field.TypeUUID},
		{Name: "model_id", Type: field.TypeUUID},
	}
	// APIKeyModelsTable holds the schema information for the "api_key_models" table.
	APIKeyModelsTable = &schema.Table{
		Name:       "api_key_models",
		Columns:    APIKeyModelsColumns,
		PrimaryKey: []*schema.Column{APIKeyModelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_key_models_api_keys_models",
				Columns:    []*schema.Column{APIKeyModelsColumns[2]},
				RefColumns: []*schema.Column{APIKeysColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "api_key_models_models_api_key_models",
				Columns:    []*schema.Column{APIKeyModelsColumns[3]},
				RefColumns: []*schema.Column{ModelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "apikeymodel_api_key_id_model_id",
				Unique:  true,
				Columns: []*schema.Column{APIKeyModelsColumns[2], APIKeyModelsColumns[3]},
			},
			{
				Name:    "apikeymodel_model_id",
				Unique:  false,
				Columns: []*schema.Column{APIKeyModelsColumns[3]},
			},
		},
	}
	// MentorProjectApplicationsColumns holds the columns for the "mentor_project_applications" table.
	MentorProjectApplicationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "approved", "rejected", "cancelled"}, Default: "pending"},
		{Name: "review_comment", Type: field.TypeString, Nullable: true, Size: 1000},
		{Name: "reviewed_at", Type: field.TypeTime, Nullable: true},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "mentor_id", Type: field.TypeUUID},
		{Name: "reviewed_by", Type: field.TypeUUID, Nullable: true},
	}
	// MentorProjectApplicationsTable holds the schema information for the "mentor_project_applications" table.
	MentorProjectApplicationsTable = &schema.Table{
		Name:       "mentor_project_applications",
		Columns:    MentorProjectApplicationsColumns,
		PrimaryKey: []*schema.Column{MentorProjectApplicationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "mentor_project_applications_projects_mentor_applications",
				Columns:    []*schema.Column{MentorProjectApplicationsColumns[5]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "mentor_project_applications_users_mentor_project_applications",
				Columns:    []*schema.Column{MentorProjectApplicationsColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "mentor_project_applications_users_reviewed_project_applications",
				Columns:    []*schema.Column{MentorProjectApplicationsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "mentorprojectapplication_project_id_mentor_id",
				Unique:  true,
				Columns: []*schema.Column{MentorProjectApplicationsColumns[5], MentorProjectApplicationsColumns[6]},
				Annotation: &entsql.IndexAnnotation{
					Where: "status = 'pending'",
				},
			},
			{
				Name:    "mentorprojectapplication_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{MentorProjectApplicationsColumns[2], MentorProjectApplicationsColumns[1]},
			},
			{
				Name:    "mentorprojectapplication_mentor_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{MentorProjectApplicationsColumns[6], MentorProjectApplicationsColumns[1]},
			},
		},
	}
	// ModelsColumns holds the columns for the "models" table.
	ModelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "model_id", Type: field.TypeString, Unique: true, Size: 256, SchemaType: map[string]string{"postgres": "citext"}},
		{Name: "display_name", Type: field.TypeString, Size: 256},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2048},
		{Name: "category", Type: field.TypeEnum, Enums: []string{"text", "image", "audio", "video", "multimodal", "embedding", "rerank"}, Default: "text"},
		{Name: "capabilities", Type: field.TypeJSON},
		{Name: "input_modalities", Type: field.TypeJSON},
		{Name: "output_modalities", Type: field.TypeJSON},
		{Name: "context_window", Type: field.TypeInt, Nullable: true},
		{Name: "max_output_tokens", Type: field.TypeInt, Nullable: true},
		{Name: "is_common", Type: field.TypeBool, Default: false},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending_configuration", "active", "inactive"}, Default: "pending_configuration"},
	}
	// ModelsTable holds the schema information for the "models" table.
	ModelsTable = &schema.Table{
		Name:       "models",
		Columns:    ModelsColumns,
		PrimaryKey: []*schema.Column{ModelsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "model_status_is_common",
				Unique:  false,
				Columns: []*schema.Column{ModelsColumns[13], ModelsColumns[12]},
			},
			{
				Name:    "model_category_status",
				Unique:  false,
				Columns: []*schema.Column{ModelsColumns[6], ModelsColumns[13]},
			},
		},
	}
	// ModelBindingsColumns holds the columns for the "model_bindings" table.
	ModelBindingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "upstream_model_name", Type: field.TypeString, Size: 256},
		{Name: "adapter", Type: field.TypeEnum, Enums: []string{"openai_compatible", "openai_responses", "openai_embeddings", "openai_images", "openai_audio", "openai_video", "openai_realtime", "openai_moderations", "anthropic", "cohere_rerank_v2", "google_gemini_v1beta"}},
		{Name: "priority", Type: field.TypeInt, Default: 100},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive"}, Default: "active"},
		{Name: "model_id", Type: field.TypeUUID},
		{Name: "provider_id", Type: field.TypeUUID},
	}
	// ModelBindingsTable holds the schema information for the "model_bindings" table.
	ModelBindingsTable = &schema.Table{
		Name:       "model_bindings",
		Columns:    ModelBindingsColumns,
		PrimaryKey: []*schema.Column{ModelBindingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "model_bindings_models_bindings",
				Columns:    []*schema.Column{ModelBindingsColumns[7]},
				RefColumns: []*schema.Column{ModelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "model_bindings_providers_model_bindings",
				Columns:    []*schema.Column{ModelBindingsColumns[8]},
				RefColumns: []*schema.Column{ProvidersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "modelbinding_model_id_provider_id_adapter",
				Unique:  true,
				Columns: []*schema.Column{ModelBindingsColumns[7], ModelBindingsColumns[8], ModelBindingsColumns[4]},
			},
			{
				Name:    "modelbinding_model_id_status_priority",
				Unique:  false,
				Columns: []*schema.Column{ModelBindingsColumns[7], ModelBindingsColumns[6], ModelBindingsColumns[5]},
			},
			{
				Name:    "modelbinding_provider_id_status",
				Unique:  false,
				Columns: []*schema.Column{ModelBindingsColumns[8], ModelBindingsColumns[6]},
			},
		},
	}
	// OrganizationsColumns holds the columns for the "organizations" table.
	OrganizationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 128, SchemaType: map[string]string{"postgres": "citext"}},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 1024},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive"}, Default: "active"},
	}
	// OrganizationsTable holds the schema information for the "organizations" table.
	OrganizationsTable = &schema.Table{
		Name:       "organizations",
		Columns:    OrganizationsColumns,
		PrimaryKey: []*schema.Column{OrganizationsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "organization_status",
				Unique:  false,
				Columns: []*schema.Column{OrganizationsColumns[5]},
			},
		},
	}
	// OrganizationMembersColumns holds the columns for the "organization_members" table.
	OrganizationMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "organization_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// OrganizationMembersTable holds the schema information for the "organization_members" table.
	OrganizationMembersTable = &schema.Table{
		Name:       "organization_members",
		Columns:    OrganizationMembersColumns,
		PrimaryKey: []*schema.Column{OrganizationMembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "organization_members_organizations_memberships",
				Columns:    []*schema.Column{OrganizationMembersColumns[2]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "organization_members_users_organization_memberships",
				Columns:    []*schema.Column{OrganizationMembersColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "organizationmember_organization_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{OrganizationMembersColumns[2], OrganizationMembersColumns[3]},
			},
			{
				Name:    "organizationmember_user_id",
				Unique:  false,
				Columns: []*schema.Column{OrganizationMembersColumns[3]},
			},
		},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Size: 128, SchemaType: map[string]string{"postgres": "citext"}},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 1024},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive"}, Default: "active"},
		{Name: "organization_id", Type: field.TypeUUID},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "projects_organizations_projects",
				Columns:    []*schema.Column{ProjectsColumns[6]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "project_organization_id_name",
				Unique:  true,
				Columns: []*schema.Column{ProjectsColumns[6], ProjectsColumns[3]},
			},
			{
				Name:    "project_organization_id_status",
				Unique:  false,
				Columns: []*schema.Column{ProjectsColumns[6], ProjectsColumns[5]},
			},
		},
	}
	// ProjectMembersColumns holds the columns for the "project_members" table.
	ProjectMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// ProjectMembersTable holds the schema information for the "project_members" table.
	ProjectMembersTable = &schema.Table{
		Name:       "project_members",
		Columns:    ProjectMembersColumns,
		PrimaryKey: []*schema.Column{ProjectMembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "project_members_projects_memberships",
				Columns:    []*schema.Column{ProjectMembersColumns[2]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "project_members_users_project_memberships",
				Columns:    []*schema.Column{ProjectMembersColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "projectmember_project_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{ProjectMembersColumns[2], ProjectMembersColumns[3]},
			},
			{
				Name:    "projectmember_user_id",
				Unique:  false,
				Columns: []*schema.Column{ProjectMembersColumns[3]},
			},
		},
	}
	// ProvidersColumns holds the columns for the "providers" table.
	ProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 128, SchemaType: map[string]string{"postgres": "citext"}},
		{Name: "base_url", Type: field.TypeString, Size: 2048},
		{Name: "credential_ciphertext", Type: field.TypeBytes},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive"}, Default: "active"},
	}
	// ProvidersTable holds the schema information for the "providers" table.
	ProvidersTable = &schema.Table{
		Name:       "providers",
		Columns:    ProvidersColumns,
		PrimaryKey: []*schema.Column{ProvidersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "provider_status",
				Unique:  false,
				Columns: []*schema.Column{ProvidersColumns[6]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Size: 64},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 254, SchemaType: map[string]string{"postgres": "citext"}},
		{Name: "password_hash", Type: field.TypeString, Size: 255},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"student", "mentor", "teacher"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending_invite", "active", "disabled"}, Default: "active"},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_role_status",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[6], UsersColumns[7]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIKeysTable,
		APIKeyAuditsTable,
		APIKeyModelsTable,
		MentorProjectApplicationsTable,
		ModelsTable,
		ModelBindingsTable,
		OrganizationsTable,
		OrganizationMembersTable,
		ProjectsTable,
		ProjectMembersTable,
		ProvidersTable,
		UsersTable,
	}
)

func init() {
	APIKeysTable.ForeignKeys[0].RefTable = ProjectsTable
	APIKeysTable.ForeignKeys[1].RefTable = UsersTable
	APIKeysTable.Annotation = &entsql.Annotation{
		Table: "api_keys",
	}
	APIKeysTable.Annotation.Checks = map[string]string{
		"api_key_material_matches_status": "\n\t\t\t\t(status IN ('pending_mentor', 'pending_teacher', 'approved', 'rejected')\n\t\t\t\t\tAND key_hash IS NULL AND key_prefix IS NULL AND claimed_at IS NULL AND revoked_at IS NULL)\n\t\t\t\tOR (status = 'active'\n\t\t\t\t\tAND key_hash IS NOT NULL AND key_prefix IS NOT NULL AND claimed_at IS NOT NULL AND revoked_at IS NULL)\n\t\t\t\tOR (status = 'revoked'\n\t\t\t\t\tAND key_hash IS NOT NULL AND key_prefix IS NOT NULL AND claimed_at IS NOT NULL AND revoked_at IS NOT NULL)\n\t\t\t",
	}
	APIKeyAuditsTable.ForeignKeys[0].RefTable = APIKeysTable
	APIKeyAuditsTable.ForeignKeys[1].RefTable = UsersTable
	APIKeyAuditsTable.Annotation = &entsql.Annotation{
		Table: "api_key_audits",
	}
	APIKeyAuditsTable.Annotation.Checks = map[string]string{
		"api_key_audit_reason_required": "\n\t\t\t\taction NOT IN ('mentor_rejected', 'teacher_rejected', 'mentor_revoked')\n\t\t\t\tOR (comment IS NOT NULL AND btrim(comment) <> '')\n\t\t\t",
	}
	APIKeyModelsTable.ForeignKeys[0].RefTable = APIKeysTable
	APIKeyModelsTable.ForeignKeys[1].RefTable = ModelsTable
	APIKeyModelsTable.Annotation = &entsql.Annotation{
		Table: "api_key_models",
	}
	MentorProjectApplicationsTable.ForeignKeys[0].RefTable = ProjectsTable
	MentorProjectApplicationsTable.ForeignKeys[1].RefTable = UsersTable
	MentorProjectApplicationsTable.ForeignKeys[2].RefTable = UsersTable
	MentorProjectApplicationsTable.Annotation = &entsql.Annotation{
		Table: "mentor_project_applications",
	}
	MentorProjectApplicationsTable.Annotation.Checks = map[string]string{
		"mentor_project_application_rejection_reason": "\n\t\t\t\tstatus <> 'rejected' OR (review_comment IS NOT NULL AND btrim(review_comment) <> '')\n\t\t\t",
		"mentor_project_application_review_state":     "\n\t\t\t\t(status IN ('pending', 'cancelled') AND reviewed_by IS NULL AND reviewed_at IS NULL)\n\t\t\t\tOR (status IN ('approved', 'rejected') AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)\n\t\t\t",
	}
	ModelsTable.Annotation = &entsql.Annotation{
		Table: "models",
	}
	ModelBindingsTable.ForeignKeys[0].RefTable = ModelsTable
	ModelBindingsTable.ForeignKeys[1].RefTable = ProvidersTable
	ModelBindingsTable.Annotation = &entsql.Annotation{
		Table: "model_bindings",
	}
	OrganizationsTable.Annotation = &entsql.Annotation{
		Table: "organizations",
	}
	OrganizationMembersTable.ForeignKeys[0].RefTable = OrganizationsTable
	OrganizationMembersTable.ForeignKeys[1].RefTable = UsersTable
	OrganizationMembersTable.Annotation = &entsql.Annotation{
		Table: "organization_members",
	}
	ProjectsTable.ForeignKeys[0].RefTable = OrganizationsTable
	ProjectsTable.Annotation = &entsql.Annotation{
		Table: "projects",
	}
	ProjectMembersTable.ForeignKeys[0].RefTable = ProjectsTable
	ProjectMembersTable.ForeignKeys[1].RefTable = UsersTable
	ProjectMembersTable.Annotation = &entsql.Annotation{
		Table: "project_members",
	}
	ProvidersTable.Annotation = &entsql.Annotation{
		Table: "providers",
	}
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
}
