export type Role = 'student' | 'mentor' | 'teacher'
export type UserStatus = 'pending_invite' | 'active' | 'disabled'
export type ResourceStatus = 'active' | 'inactive'
export type ModelStatus = 'pending_configuration' | 'active' | 'inactive'
export type ApiKeyStatus = 'pending_mentor' | 'pending_teacher' | 'approved' | 'active' | 'rejected' | 'revoked'
export type ApplicationStatus = 'pending' | 'approved' | 'rejected' | 'cancelled'
export type ModelCategory = 'text' | 'image' | 'audio' | 'video' | 'multimodal' | 'embedding' | 'rerank'
export type BindingAdapter = 'openai_compatible' | 'anthropic'
export type AuditAction = 'mentor_approved' | 'mentor_rejected' | 'teacher_approved' | 'teacher_rejected' | 'mentor_revoked'
export type ProgressStep = 'submitted' | 'mentor_review' | 'teacher_review' | 'claimed'
export type ProgressCurrent = 'mentor_review' | 'teacher_review' | 'claim' | 'active' | 'rejected' | 'rejected_teacher' | 'revoked'

export type User = { id: string; name: string; email: string; role: Role; status: UserStatus; created_at: string }
export type Organization = { id: string; name: string; description?: string | null; status: ResourceStatus }
export type Project = { id: string; organization_id: string; name: string; description?: string | null; status: ResourceStatus; has_mentor: boolean; is_responsible?: boolean; application_status?: ApplicationStatus }
export type Model = { id: string; model_id: string; display_name: string; description?: string | null; category: ModelCategory; capabilities: string[]; input_modalities: string[]; output_modalities: string[]; context_window?: number | null; max_output_tokens?: number | null; is_common: boolean; status: ModelStatus; route_ready: boolean }
export type Provider = { id: string; name: string; base_url: string; credential_configured: boolean; status: ResourceStatus; created_at: string; updated_at: string }
export type Binding = { id: string; model_id: string; provider_id: string; upstream_model_name: string; adapter: BindingAdapter; priority: number; status: ResourceStatus; created_at: string; updated_at: string }
export type Progress = { current: ProgressCurrent; completed_steps: ProgressStep[] }
export type Audit = { action: AuditAction; actor_role: Role; comment?: string | null; created_at: string }
export type ApiKey = { id: string; name: string; status: ApiKeyStatus; progress: Progress; applicant?: User; organization: Organization; project: Project; models: Model[]; audits?: Audit[]; key_prefix?: string | null; claimed_at?: string | null; created_at: string; updated_at: string }
export type Application = { id: string; status: ApplicationStatus; mentor: User; project: Project; reviewer?: User; review_comment?: string | null; reviewed_at?: string | null; created_at: string }
export type MentorCandidate = { id: string; name: string; email: string; is_member: boolean }
export type Session = { access_token: string; token_type: string; expires_in: number; user: User }
export type PageMeta = { next_cursor?: string | null }
export type Envelope<T> = { data: T; meta?: PageMeta; request_id?: string }
export type ApiErrorDetails = { model_ids: string[] } | Array<{ field: string; reason: string }>
export type ApiError = { error?: { code?: string; message?: string; details?: ApiErrorDetails }; request_id?: string }

export type OrganizationCreate = { name: string; description?: string; status?: ResourceStatus }
export type OrganizationUpdate = { name?: string; description?: string; status?: ResourceStatus }
export type ProjectCreate = { organization_id: string; name: string; description?: string; status?: ResourceStatus }
export type ProjectUpdate = { name?: string; description?: string; status?: ResourceStatus }
export type ProviderCreate = { name: string; base_url: string; credential: string; status?: ResourceStatus }
export type ProviderUpdate = { name?: string; base_url?: string; credential?: string; status?: ResourceStatus }
export type ModelCreate = { model_id: string; display_name: string; description?: string; category: ModelCategory; capabilities: string[]; input_modalities: string[]; output_modalities: string[]; context_window?: number; max_output_tokens?: number; is_common?: boolean; status?: Exclude<ModelStatus, 'active'> }
export type ModelUpdate = { display_name?: string; description?: string; category?: ModelCategory; capabilities?: string[]; input_modalities?: string[]; output_modalities?: string[]; context_window?: number | null; max_output_tokens?: number | null; is_common?: boolean; status?: ModelStatus }
export type BindingCreate = { provider_id: string; upstream_model_name: string; adapter: BindingAdapter; priority: number; status: ResourceStatus }
export type BindingUpdate = { upstream_model_name?: string; adapter?: BindingAdapter; priority?: number; status?: ResourceStatus }
export type RequestedModel = { model_id: string; display_name: string; description?: string | null; category: ModelCategory; capabilities: string[]; input_modalities: string[]; output_modalities: string[]; context_window?: number | null; max_output_tokens?: number | null }
export type SubmitApiKey = { name: string; organization_id: string; project_id: string; model_ids: string[]; requested_models: RequestedModel[] }
export type ModelResolution = { exists: boolean; model?: Model }
