export type Role = 'student' | 'mentor' | 'teacher'
export type UserStatus = 'pending_invite' | 'active' | 'disabled'
export type ResourceStatus = 'active' | 'inactive'
export type ModelStatus = 'pending_configuration' | 'active' | 'inactive'
export type ApiKeyStatus = 'pending_mentor' | 'pending_teacher' | 'approved' | 'active' | 'rejected' | 'revoked'
export type ApplicationStatus = 'pending' | 'approved' | 'rejected' | 'cancelled'
export type ModelCategory = 'text' | 'image' | 'audio' | 'video' | 'multimodal' | 'embedding' | 'rerank'
export type ModelCapability = 'reasoning'|'vision'|'tool_calling'|'structured_output'|'web_search'|'coding'|'embeddings'|'rerank'|'realtime'|'image_generation'|'video_generation'|'speech_to_text'|'text_to_speech'
export type BindingAdapter = 'openai_compatible' | 'openai_responses' | 'openai_embeddings' | 'openai_images' | 'openai_audio' | 'openai_video' | 'openai_realtime' | 'openai_moderations' | 'anthropic' | 'cohere_rerank_v2' | 'google_gemini_v1beta'
export type AuditAction = 'mentor_approved' | 'mentor_rejected' | 'teacher_approved' | 'teacher_rejected' | 'mentor_revoked'
export type ProgressStep = 'submitted' | 'mentor_review' | 'teacher_review' | 'claimed'
export type ProgressCurrent = 'mentor_review' | 'teacher_review' | 'claim' | 'active' | 'rejected' | 'rejected_teacher' | 'revoked'

export type User = { id: string; name: string; email: string; role: Role; status: UserStatus; created_at: string }
export type Organization = { id: string; name: string; description?: string | null; status: ResourceStatus }
export type Project = { id: string; organization_id: string; name: string; description?: string | null; status: ResourceStatus; has_mentor: boolean; is_responsible?: boolean; application_status?: ApplicationStatus; monthly_credit_quota: string }
export type Model = { model_id: string; display_name: string; description?: string | null; category: ModelCategory; capabilities: ModelCapability[]; input_modalities: string[]; output_modalities: string[]; context_window?: number | null; max_input_tokens?: number | null; max_output_tokens?: number | null; is_common: boolean; status: ModelStatus; route_ready: boolean; credit_multiplier: string | null }
export type UsageSlice = { id: string; name: string; credits: string; calls?: number }
export type KeyUsage = { id: string; name: string; status: ApiKeyStatus; quota: string; used: string; pending: string; overage: string; models: UsageSlice[] }
export type StudentUsage = { month: string; keys: KeyUsage[] }
export type ProjectUsage = { month: string; project_id: string; project_name: string; quota: string; allocated: string; charged: string; pending: string; available: string; members: Array<{ user_id: string; user_name: string; credits: string; keys: Array<{ id: string; name: string; status: ApiKeyStatus; quota: string; allocation: string; used: string; models: UsageSlice[] }>; free_models: UsageSlice[] }>; models: UsageSlice[]; free_models: UsageSlice[] }
export type CallLog = { id: string; request_id: string; project_id: string; project_name: string; user_id: string; user_name: string; api_key_id: string; api_key_name: string; model_id: string; model_name: string; provider_name: string; protocol: string; path: string; multiplier: string; credits: string; billing_state: string; outcome: string; error_category: string; error_message: string; created_at: string; attempts?: Array<{ provider_name: string; status: string; error_category: string; error_message: string; http_status?: number; latency_ms: number }> }
export type InputMonitorItem = { call_id: string; project_id: string; project_name: string; user_id: string; user_name: string; api_key_name: string; model_name: string; provider_name: string; credits: string; outcome: string; preview: string; content_bytes: number; truncated: boolean; created_at: string; content?: string }
export type Provider = { id: string; name: string; base_url: string; credential_configured: boolean; status: ResourceStatus; created_at: string; updated_at: string }
export type Binding = { id: string; model_id: string; provider_id: string; upstream_model_name: string; adapter: BindingAdapter; priority: number; status: ResourceStatus; created_at: string; updated_at: string }
export type Progress = { current: ProgressCurrent; completed_steps: ProgressStep[] }
export type Audit = { action: AuditAction; actor_role: Role; comment?: string | null; created_at: string }
export type ApiKey = { id: string; name: string; status: ApiKeyStatus; progress: Progress; applicant?: User; organization: Organization; project: Project; models: Model[]; audits?: Audit[]; key_prefix?: string | null; claimed_at?: string | null; requested_monthly_credits?: string; mentor_monthly_credits?: string | null; monthly_credits?: string | null; created_at: string; updated_at: string }
export type Application = { id: string; status: ApplicationStatus; mentor: User; project: Project; reviewer?: User; review_comment?: string | null; reviewed_at?: string | null; created_at: string }
export type MentorCandidate = { id: string; name: string; email: string; is_member: boolean }
export type Session = { access_token: string; token_type: string; expires_in: number; user: User }
export type PageMeta = { next_cursor?: string | null }
export type Envelope<T> = { data: T; meta?: PageMeta; request_id?: string }
export type ApiErrorDetails = { model_ids?: string[]; operation?: string; state_changed?: boolean } | Array<{ field: string; reason: string }>
export type ApiError = { error?: { code?: string; message?: string; details?: ApiErrorDetails }; request_id?: string }

export type OrganizationCreate = { name: string; description?: string; status?: ResourceStatus }
export type OrganizationUpdate = { name?: string; description?: string; status?: ResourceStatus }
export type ProjectCreate = { organization_id: string; name: string; description?: string; status?: ResourceStatus; monthly_credit_quota: string }
export type ProjectUpdate = { name?: string; description?: string; status?: ResourceStatus; monthly_credit_quota?: string; quota_change_reason?: string }
export type ProviderCreate = { name: string; base_url: string; credential: string; status?: ResourceStatus }
export type ProviderUpdate = { name?: string; base_url?: string; credential?: string; status?: ResourceStatus }
export type ModelCreate = { model_id: string; display_name: string; description?: string; category: ModelCategory; capabilities: ModelCapability[]; input_modalities: string[]; output_modalities: string[]; context_window?: number; max_input_tokens?: number; max_output_tokens?: number; is_common?: boolean; status?: Exclude<ModelStatus, 'active'>; credit_multiplier?: string }
export type ModelUpdate = { model_id: string; display_name?: string; description?: string; category?: ModelCategory; capabilities?: ModelCapability[]; input_modalities?: string[]; output_modalities?: string[]; context_window?: number | null; max_input_tokens?: number | null; max_output_tokens?: number | null; is_common?: boolean; status?: ModelStatus; credit_multiplier?: string; multiplier_change_reason?: string }
export type BindingCreate = { provider_id: string; upstream_model_name: string; adapter: BindingAdapter; priority: number; status: ResourceStatus }
export type BindingUpdate = { upstream_model_name?: string; adapter?: BindingAdapter; priority?: number; status?: ResourceStatus }
export type RequestedModel = { model_id: string; display_name?: string }
export type SubmitApiKey = { name: string; organization_id: string; project_id: string; models: RequestedModel[]; requested_monthly_credits: string }
export type ModelCatalogCandidate = { model_id:string;description?:string|null;owned_by:string[];model_types:string[];supported_endpoint_types:string[];tags:string[];suggestion:{category:ModelCategory;capabilities:ModelCapability[];input_modalities:string[];output_modalities:string[]} }
export type ModelCatalogPage = { items:ModelCatalogCandidate[];page:number;page_size:number;total:number }
export type ProbeEndpoint = 'chat_completions'|'responses'|'messages'|'embeddings'|'rerank'
export type ProbeResponse = { results:Array<{endpoint:ProbeEndpoint|'models';path:string;http_status:number;duration_ms:number;truncated:boolean;error?:string;limits:{context_window?:number;max_input_tokens?:number;max_output_tokens?:number}}>;configuration:{description?:string;category?:ModelCategory;capabilities?:ModelCapability[];input_modalities?:string[];output_modalities?:string[];context_window?:number;max_input_tokens?:number;max_output_tokens?:number} }
