<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { teacherAPI } from '../../api/teacher'
import type { Binding, BindingAdapter, Model, ModelCapability, ModelStatus, ProbeEndpoint, ProbeResponse, Provider } from '../../api/types'
import { APIError } from '../../api/client'
import StatusBadge from '../../components/StatusBadge.vue'
import AppDialog from '../../components/AppDialog.vue'
import LoadingRegion from '../../components/LoadingRegion.vue'
import { useLoadState } from '../../composables/useLoadState'
import { useToast } from '../../composables/useToast'
import { capabilityLabel, capabilityOptions, formatTokenK, parseTokenK } from '../../utils/modelCatalog'

const DEFAULT_CONTEXT_WINDOW = 128_000
const DEFAULT_MAX_INPUT_TOKENS = 128_000
const DEFAULT_MAX_OUTPUT_TOKENS = 4_000
const adapterOptions: Array<{ value: BindingAdapter; label: string }> = [
  { value: 'openai_compatible', label: 'OpenAI Chat / Completions' },
  { value: 'openai_responses', label: 'OpenAI Responses' },
  { value: 'openai_embeddings', label: 'OpenAI Embeddings' },
  { value: 'anthropic', label: 'Anthropic Messages' },
  { value: 'cohere_rerank_v2', label: 'Cohere Rerank v2' },
]
const probeEndpointOptions: Array<{ value: ProbeEndpoint; label: string }> = [
  { value: 'chat_completions', label: 'Chat / Completions' }, { value: 'responses', label: 'Responses' },
  { value: 'messages', label: 'Messages' }, { value: 'embeddings', label: 'Embeddings' }, { value: 'rerank', label: 'Rerank' },
]

const rows = ref<Model[]>([]), providers = ref<Provider[]>([]), tab = ref<'common' | 'all'>('common'), query = ref('')
const selected = ref<{ model: Model; bindings: Binding[] } | null>(null), dialogOpen = ref(false), step = ref(1), error = ref('')
const catalog = ref<any[]>([]), catalogPage = ref(1), catalogTotal = ref(0), catalogQuery = ref('')
const quickFillPromptOpen = ref(false), quickFillPromptShown = ref(false), probeOpen = ref(false), probePending = ref(false)
const multiplierReason = ref(''), bindingOpen = ref(false), editingBinding = ref<Binding | null>(null)
const toast = useToast(), loadState = useLoadState(), route = useRoute(), router = useRouter()
const modelForm = reactive<any>({ model_id: '', display_name: '', description: '', category: 'text', capabilities: [] as ModelCapability[], input_modalities: ['text'], output_modalities: ['text'], context_window: DEFAULT_CONTEXT_WINDOW, max_input_tokens: DEFAULT_MAX_INPUT_TOKENS, max_output_tokens: DEFAULT_MAX_OUTPUT_TOKENS, is_common: false, status: 'pending_configuration' as ModelStatus, credit_multiplier: '1.000' })
const bindingForm = reactive({ provider_id: '', upstream_model_name: '', adapter: 'openai_compatible' as BindingAdapter, priority: 100, status: 'active' as 'active' | 'inactive' })
const probeForm = reactive<{ provider_id: string; base_url: string; credential: string; upstream_model_name: string; endpoints: ProbeEndpoint[] }>({ provider_id: '', base_url: '', credential: '', upstream_model_name: '', endpoints: ['chat_completions'] })
const filtered = computed(() => rows.value.filter(model => (tab.value === 'all' || model.is_common) && (!query.value || `${model.display_name} ${model.model_id}`.toLowerCase().includes(query.value.toLowerCase()))).sort((a, b) => a.display_name.localeCompare(b.display_name)))
const maxCatalogPage = computed(() => Math.max(1, Math.ceil(catalogTotal.value / 20)))

async function load() { await loadState.run(async () => { try { [rows.value, providers.value] = await Promise.all([teacherAPI.models(), teacherAPI.providers()]); const target = String(route.query.model || ''); if (target) { const row = rows.value.find(item => item.model_id === target); if (row) await open(row) } } catch (e) { error.value = msg(e) } }) }
function defaultDescription() { const name = String(modelForm.display_name || modelForm.model_id).trim(); return name ? `${name}（${modelForm.model_id}）` : modelForm.model_id }
function ensureBaseDefaults() { if (!String(modelForm.description || '').trim()) modelForm.description = defaultDescription(); if (!modelForm.category) modelForm.category = 'text'; if (!Array.isArray(modelForm.capabilities)) modelForm.capabilities = []; if (!Array.isArray(modelForm.input_modalities) || !modelForm.input_modalities.length) modelForm.input_modalities = ['text']; if (!Array.isArray(modelForm.output_modalities) || !modelForm.output_modalities.length) modelForm.output_modalities = ['text']; if (!modelForm.context_window) modelForm.context_window = DEFAULT_CONTEXT_WINDOW; if (!modelForm.max_input_tokens) modelForm.max_input_tokens = DEFAULT_MAX_INPUT_TOKENS; if (!modelForm.max_output_tokens) modelForm.max_output_tokens = DEFAULT_MAX_OUTPUT_TOKENS; if (!modelForm.credit_multiplier) modelForm.credit_multiplier = '1.000'; if (typeof modelForm.is_common !== 'boolean') modelForm.is_common = false }
function resetProbeForm() { Object.assign(probeForm, { provider_id: '', base_url: '', credential: '', upstream_model_name: modelForm.model_id, endpoints: ['chat_completions'] }) }
function reset() { Object.assign(modelForm, { model_id: '', display_name: '', description: '', category: 'text', capabilities: [], input_modalities: ['text'], output_modalities: ['text'], context_window: DEFAULT_CONTEXT_WINDOW, max_input_tokens: DEFAULT_MAX_INPUT_TOKENS, max_output_tokens: DEFAULT_MAX_OUTPUT_TOKENS, is_common: false, status: 'pending_configuration', credit_multiplier: '1.000' }); selected.value = null; step.value = 1; dialogOpen.value = true; multiplierReason.value = ''; catalog.value = []; catalogQuery.value = ''; quickFillPromptShown.value = false; quickFillPromptOpen.value = false; probeOpen.value = false; resetProbeForm() }
async function open(model: Model) { selected.value = await teacherAPI.model(model.model_id); Object.assign(modelForm, selected.value.model); step.value = 1; dialogOpen.value = true; quickFillPromptShown.value = false; quickFillPromptOpen.value = false; probeOpen.value = false; resetProbeForm(); await router.replace({ query: { model: model.model_id } }) }
function close() { dialogOpen.value = false; selected.value = null; quickFillPromptOpen.value = false; probeOpen.value = false; bindingOpen.value = false; void router.replace({ query: {} }) }
function canOpenStep(target: number) { if (selected.value || target === 1) return true; return target === 2 && Boolean(String(modelForm.model_id).trim() && String(modelForm.display_name).trim()) }
function goToStep(target: number) { if (!canOpenStep(target)) return; step.value = target; if (target === 2) enterBaseStep() }
function enterBaseStep() { ensureBaseDefaults(); step.value = 2; if (!quickFillPromptShown.value) { quickFillPromptShown.value = true; quickFillPromptOpen.value = true } }
function startQuickFill() { quickFillPromptOpen.value = false; resetProbeForm(); probeOpen.value = true }
async function searchCatalog() { catalogQuery.value = modelForm.model_id; const page = await teacherAPI.catalogCandidates(catalogQuery.value, catalogPage.value, 20); catalog.value = page.items; catalogTotal.value = page.total }
function chooseCandidate(item: any) { modelForm.model_id = item.model_id; modelForm.display_name = item.model_id; modelForm.description = Array.from(String(item.description || '')).slice(0, 2048).join(''); Object.assign(modelForm, item.suggestion); catalog.value = [] }
function toggleCapability(value: ModelCapability) { const index = modelForm.capabilities.indexOf(value); index >= 0 ? modelForm.capabilities.splice(index, 1) : modelForm.capabilities.push(value) }
async function saveBase() { try { const body: any = { model_id: modelForm.model_id, display_name: modelForm.display_name, description: modelForm.description, category: modelForm.category, capabilities: modelForm.capabilities, input_modalities: modelForm.input_modalities, output_modalities: modelForm.output_modalities, context_window: modelForm.context_window, max_input_tokens: modelForm.max_input_tokens, max_output_tokens: modelForm.max_output_tokens, is_common: modelForm.is_common }; if (selected.value) { if (modelForm.credit_multiplier !== selected.value.model.credit_multiplier) { body.credit_multiplier = modelForm.credit_multiplier; body.multiplier_change_reason = multiplierReason.value.trim() } await teacherAPI.updateModel(body) } else await teacherAPI.createModel({ ...body, credit_multiplier: modelForm.credit_multiplier, status: 'pending_configuration' }); selected.value = await teacherAPI.model(modelForm.model_id); Object.assign(modelForm, selected.value.model); toast.success('基础配置已保存'); step.value = 3; await load() } catch (e) { error.value = msg(e) } }
function applyProbeConfiguration(configuration: ProbeResponse['configuration']) { if (configuration.description) modelForm.description = configuration.description; if (configuration.category) modelForm.category = configuration.category; if (configuration.capabilities) modelForm.capabilities = [...configuration.capabilities]; if (configuration.input_modalities?.length) modelForm.input_modalities = [...configuration.input_modalities]; if (configuration.output_modalities?.length) modelForm.output_modalities = [...configuration.output_modalities]; if (configuration.context_window) modelForm.context_window = configuration.context_window; if (configuration.max_input_tokens) modelForm.max_input_tokens = configuration.max_input_tokens; if (configuration.max_output_tokens) modelForm.max_output_tokens = configuration.max_output_tokens }
async function probe() { try { probePending.value = true; probeForm.upstream_model_name ||= modelForm.model_id; const result = await teacherAPI.probeModel({ provider_id: probeForm.provider_id || undefined, base_url: probeForm.base_url || undefined, credential: probeForm.credential || undefined, upstream_model_name: probeForm.upstream_model_name, endpoints: probeForm.endpoints }); applyProbeConfiguration(result.configuration || {}); probeOpen.value = false; probeForm.credential = ''; const succeeded = result.results.filter(item => item.http_status >= 200 && item.http_status < 300).length; toast.success(succeeded ? '一键填充完成，已自动更新基础配置' : '测试未返回可用字段，已保留默认配置') } catch (e) { error.value = msg(e) } finally { probePending.value = false } }
function openBinding(binding?: Binding) { editingBinding.value = binding || null; Object.assign(bindingForm, { provider_id: binding?.provider_id || '', upstream_model_name: binding?.upstream_model_name || modelForm.model_id, adapter: binding?.adapter || 'openai_compatible', priority: binding?.priority || 100, status: binding?.status || 'active' }); bindingOpen.value = true }
async function saveBinding() { try { if (editingBinding.value) await teacherAPI.updateBinding(editingBinding.value.id, bindingForm); else await teacherAPI.createBinding(modelForm.model_id, bindingForm); selected.value = await teacherAPI.model(modelForm.model_id); bindingOpen.value = false; step.value = 4; toast.success('Binding 已保存'); await load() } catch (e) { error.value = msg(e) } }
async function toggleStatus() { try { const next = modelForm.status === 'active' ? 'inactive' : 'active'; await teacherAPI.updateModel({ model_id: modelForm.model_id, status: next }); toast.success(next === 'active' ? '模型已启用' : '模型已停用'); await load(); close() } catch (e) { error.value = msg(e) } }
function msg(e: unknown) { return e instanceof APIError ? e.message : '请求失败' }
onMounted(load)
</script>

<template>
  <section class="page">
    <div class="page-heading"><div><p class="eyebrow">TEACHER</p><h1>模型管理</h1><p class="muted">配置模型元数据、计费倍率、常用标记和供应商 Binding。</p></div><button class="button primary" @click="reset">新增模型</button></div>
    <p v-if="error" class="error banner">{{ error }}</p>
    <section class="panel"><div class="segmented"><button :class="{ active: tab === 'common' }" @click="tab = 'common'">常用模型</button><button :class="{ active: tab === 'all' }" @click="tab = 'all'">全部模型 <span>{{ rows.length }}</span></button></div><label>搜索<input v-model="query" placeholder="名称或 model_id"></label></section>
    <LoadingRegion :initial-loading="loadState.initialLoading.value" :refreshing="loadState.refreshing.value" variant="cards" label="正在加载模型"><div class="grid two" style="margin-top:20px"><article v-for="model in filtered" :key="model.model_id" class="panel"><div class="row"><div><strong>{{ model.display_name }}</strong><p class="muted">{{ model.model_id }} · {{ model.category }}</p></div><StatusBadge :status="model.status" /></div><div class="chip-list"><span class="chip">{{ model.credit_multiplier ?? '未配置' }}x</span><span v-for="capability in model.capabilities" :key="capability" class="chip">{{ capabilityLabel(capability) }}</span></div><div class="actions"><button class="button ghost" @click="open(model)">配置</button></div></article></div></LoadingRegion>
    <AppDialog :open="dialogOpen" :title="selected ? selected.model.display_name : '新增模型'" wide @update:open="$event ? null : close()">
      <div class="wizard-steps"><button v-for="item in [{ n: 1, t: '模型标识' }, { n: 2, t: '基础配置' }, { n: 3, t: 'Binding' }, { n: 4, t: '启用确认' }]" :key="item.n" class="wizard-step" :class="{ active: step === item.n, done: step > item.n }" :disabled="!canOpenStep(item.n)" @click="goToStep(item.n)"><span>{{ item.n }}</span>{{ item.t }}</button></div>
      <section v-if="step === 1"><div class="grid two"><label>模型 ID<input v-model="modelForm.model_id" :readonly="Boolean(selected)" required @input="searchCatalog"></label><label>模型名称<input v-model="modelForm.display_name" required></label></div><div v-if="!selected && catalog.length"><div v-for="item in catalog" :key="item.model_id" class="list-row"><div><strong>{{ item.model_id }}</strong><p class="muted">{{ item.description || '无描述' }}</p></div><button class="button ghost" @click="chooseCandidate(item)">选择</button></div><div class="pagination"><button class="button ghost" :disabled="catalogPage <= 1" @click="catalogPage--; searchCatalog()">←</button><span>{{ catalogPage }} / {{ maxCatalogPage }}</span><button class="button ghost" :disabled="catalogPage >= maxCatalogPage" @click="catalogPage++; searchCatalog()">→</button></div></div></section>
      <section v-else-if="step === 2"><label>描述<textarea v-model="modelForm.description" rows="3" /></label><div class="grid two"><label>类别<select v-model="modelForm.category"><option v-for="value in ['text', 'image', 'audio', 'video', 'multimodal', 'embedding', 'rerank']" :key="value">{{ value }}</option></select></label><label>计费倍率<input v-model="modelForm.credit_multiplier"></label></div><div class="grid two"><fieldset><legend>输入模态</legend><label v-for="value in ['text', 'image', 'audio', 'video']" :key="value" class="checkbox-option"><input v-model="modelForm.input_modalities" type="checkbox" :value="value">{{ value }}</label></fieldset><fieldset><legend>输出模态</legend><label v-for="value in ['text', 'image', 'audio', 'video']" :key="value" class="checkbox-option"><input v-model="modelForm.output_modalities" type="checkbox" :value="value">{{ value }}</label></fieldset></div><fieldset><legend>能力</legend><label v-for="item in capabilityOptions" :key="item.value" class="checkbox-option"><input type="checkbox" :checked="modelForm.capabilities.includes(item.value)" @change="toggleCapability(item.value)">{{ item.label }}</label></fieldset><div class="grid three"><label>上下文长度（K）<input :value="modelForm.context_window ? formatTokenK(modelForm.context_window).replace('K', '') : ''" @input="modelForm.context_window = parseTokenK(($event.target as HTMLInputElement).value)"></label><label>最大输入（K）<input :value="modelForm.max_input_tokens ? formatTokenK(modelForm.max_input_tokens).replace('K', '') : ''" @input="modelForm.max_input_tokens = parseTokenK(($event.target as HTMLInputElement).value)"></label><label>最大输出（K）<input :value="modelForm.max_output_tokens ? formatTokenK(modelForm.max_output_tokens).replace('K', '') : ''" @input="modelForm.max_output_tokens = parseTokenK(($event.target as HTMLInputElement).value)"></label></div><label class="checkbox-option"><input v-model="modelForm.is_common" type="checkbox">全局常用模型</label><label v-if="selected && modelForm.credit_multiplier !== selected.model.credit_multiplier">倍率变更原因<textarea v-model="multiplierReason" /></label><div class="actions"><button class="button secondary" @click="startQuickFill">一键配置</button><button class="button primary" @click="saveBase">保存基础配置</button></div></section>
      <section v-else-if="step === 3"><div class="row"><h2>供应商 Binding</h2><button class="button secondary" @click="openBinding()">＋</button></div><article v-for="binding in (selected?.bindings || [])" :key="binding.id" class="list-row"><div><strong>{{ providers.find(provider => provider.id === binding.provider_id)?.name || '供应商' }}</strong><p class="muted">{{ binding.adapter }} · 优先级 {{ binding.priority }}</p></div><button class="button ghost" @click="openBinding(binding)">编辑</button></article><p v-if="!selected?.bindings.length" class="empty">请点击右上角＋新增 Binding</p></section>
      <section v-else><p>基础配置已保存，并且至少存在一条 active Binding 后才能启用模型。</p><div class="actions"><button class="button" :class="modelForm.status === 'active' ? 'danger' : 'primary'" :disabled="modelForm.status !== 'active' && !selected?.model.route_ready" @click="toggleStatus">{{ modelForm.status === 'active' ? '停用模型' : '启用模型' }}</button></div></section>
    </AppDialog>
    <AppDialog :open="quickFillPromptOpen" title="基础配置已有默认值" @update:open="quickFillPromptOpen = $event"><p><strong>好消息：</strong>模型的基础信息已经自动填入默认值，你可以直接继续配置或保存。</p><p class="muted">是否现在连接供应商，通过 <code>/v1/models</code> 和所选真实端点进一步补全简介、标签、能力与容量？</p><div class="actions"><button class="button ghost" @click="quickFillPromptOpen = false">否，采用默认值</button><span class="muted">选否则会采用默认值进入下一步</span><button class="button primary" @click="startQuickFill">是，开始一键填充</button></div></AppDialog>
    <AppDialog :open="probeOpen" title="一键配置" wide @update:open="probeOpen = $event"><form @submit.prevent="probe"><div class="grid two"><label>模型 ID<input :value="modelForm.model_id" readonly></label><label>上游模型名<input v-model="probeForm.upstream_model_name" required></label></div><label>注册供应商<select v-model="probeForm.provider_id"><option value="">手写供应商</option><option v-for="provider in providers" :key="provider.id" :value="provider.id">{{ provider.name }}</option></select></label><template v-if="!probeForm.provider_id"><label>供应商 Base URL<input v-model="probeForm.base_url" placeholder="https://example.com" required></label><label>临时测试 Key<input v-model="probeForm.credential" type="password" required></label></template><fieldset><legend>测试端点</legend><label v-for="item in probeEndpointOptions" :key="item.value" class="checkbox-option"><input v-model="probeForm.endpoints" type="checkbox" :value="item.value">{{ item.label }}</label></fieldset><p class="muted">系统还会自动请求供应商 <code>/v1/models</code>，只将匹配模型的标准化信息带回基础配置，不在页面展示上游响应正文。</p><div class="actions"><button class="button primary" :disabled="probePending || probeForm.endpoints.length === 0">{{ probePending ? '正在测试…' : '开始测试并自动填充' }}</button></div></form></AppDialog>
    <AppDialog :open="bindingOpen" :title="editingBinding ? '编辑 Binding' : '新增 Binding'" wide @update:open="bindingOpen = $event"><form @submit.prevent="saveBinding"><label>供应商<select v-model="bindingForm.provider_id" required><option value="">请选择</option><option v-for="provider in providers" :key="provider.id" :value="provider.id">{{ provider.name }}</option></select></label><label>上游模型名<input v-model="bindingForm.upstream_model_name" required></label><label>端点类型<select v-model="bindingForm.adapter"><option v-for="item in adapterOptions" :key="item.value" :value="item.value">{{ item.label }}</option></select></label><label>优先级<input v-model.number="bindingForm.priority" type="number" min="0"></label><div class="actions"><button class="button primary">保存</button></div></form></AppDialog>
  </section>
</template>
