<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { teacherAPI } from '../../api/teacher'
import type { Application, Organization, Project } from '../../api/types'
import { APIError } from '../../api/client'
import StatusBadge from '../../components/StatusBadge.vue'
import AppDialog from '../../components/AppDialog.vue'
import LoadingRegion from '../../components/LoadingRegion.vue'
import { useLoadState } from '../../composables/useLoadState'
import { useToast } from '../../composables/useToast'
const orgs=ref<Organization[]>([]),projects=ref<Project[]>([]),apps=ref<Application[]>([]),query=ref(''),drawer=ref(false),editing=ref<Project|null>(null),reviewing=ref<Application|null>(null),approve=ref(false),comment=ref(''),error=ref(''),toast=useToast(),loadState=useLoadState()
const form=reactive({organization_id:'',name:'',description:'',status:'active' as 'active'|'inactive',monthly_credit_quota:'20000.000',quota_change_reason:''})
const filtered=computed(()=>projects.value.filter(project=>!query.value||project.name.toLowerCase().includes(query.value.toLowerCase())))
async function load(){await loadState.run(async()=>{try{[orgs.value,projects.value,apps.value]=await Promise.all([teacherAPI.organizations(),teacherAPI.projects(),teacherAPI.mentorApplications()]);error.value=''}catch(e){error.value=msg(e)}})}
function open(project?:Project){editing.value=project??null;Object.assign(form,{organization_id:project?.organization_id??'',name:project?.name??'',description:project?.description??'',status:project?.status??'active',monthly_credit_quota:project?.monthly_credit_quota??'20000.000',quota_change_reason:''});drawer.value=true}
async function save(){try{if(editing.value){const quotaChanged=form.monthly_credit_quota!==editing.value.monthly_credit_quota;if(quotaChanged&&!form.quota_change_reason.trim()){error.value='修改项目额度必须填写原因';return}await teacherAPI.updateProject(editing.value.id,{name:form.name,description:form.description,status:form.status,...(quotaChanged?{monthly_credit_quota:form.monthly_credit_quota,quota_change_reason:form.quota_change_reason}:{})})}else await teacherAPI.createProject({organization_id:form.organization_id,name:form.name,description:form.description,status:form.status,monthly_credit_quota:form.monthly_credit_quota});toast.success(editing.value?'项目已更新':'项目已创建');drawer.value=false;await load()}catch(e){error.value=msg(e)}}
async function toggle(project:Project){try{await teacherAPI.updateProject(project.id,{status:project.status==='active'?'inactive':'active'});await load()}catch(e){error.value=msg(e)}}
async function review(){if(!reviewing.value)return;if(!approve.value&&!comment.value.trim()){error.value='驳回必须填写原因';return}try{await teacherAPI.reviewMentor(reviewing.value.id,approve.value,comment.value||undefined);reviewing.value=null;await load()}catch(e){error.value=msg(e)}}
function msg(e:unknown){return e instanceof APIError?e.message:'请求失败'}onMounted(load)
</script>
<template><section class="page"><div class="page-heading"><div><p class="eyebrow">TEACHER</p><h1>项目管理</h1><p class="muted">维护项目状态与月度 credit 总额度。</p></div><button class="button primary" @click="open()">添加项目</button></div><p v-if="error" class="error banner">{{error}}</p><LoadingRegion :initial-loading="loadState.initialLoading.value" :refreshing="loadState.refreshing.value" variant="split" label="正在加载项目"><div class="grid two"><section class="panel"><label>搜索<input v-model="query"></label><article v-for="project in filtered" :key="project.id" class="list-row"><div><strong>{{project.name}}</strong><p class="muted">{{orgs.find(org=>org.id===project.organization_id)?.name}} · 月额度 {{project.monthly_credit_quota}}</p></div><div class="actions"><StatusBadge :status="project.status"/><button class="button ghost" @click="open(project)">编辑</button><button class="button" :class="project.status==='active'?'danger':'secondary'" @click="toggle(project)">{{project.status==='active'?'停用':'启用'}}</button></div></article></section><aside class="panel"><h2>导师项目申请</h2><article v-for="app in apps" :key="app.id" class="review-row"><div><strong>{{app.mentor.name}}</strong><p>{{app.project.name}}</p></div><div class="actions"><button class="button danger" @click="reviewing=app;approve=false">驳回</button><button class="button primary" @click="reviewing=app;approve=true">通过</button></div></article></aside></div></LoadingRegion><AppDialog :open="drawer" :title="editing?'编辑项目':'创建项目'" @update:open="drawer=$event"><form @submit.prevent="save"><label>所属组织<select v-model="form.organization_id" :disabled="Boolean(editing)" required><option value="">请选择</option><option v-for="org in orgs" :key="org.id" :value="org.id">{{org.name}}</option></select></label><label>名称<input v-model="form.name" required></label><label>说明<textarea v-model="form.description" rows="3"></textarea></label><label>月度总额度（credits）<input v-model="form.monthly_credit_quota" inputmode="decimal" required></label><label v-if="editing&&form.monthly_credit_quota!==editing.monthly_credit_quota">调额原因<textarea v-model="form.quota_change_reason" rows="3" required></textarea></label><label>状态<select v-model="form.status"><option value="active">启用</option><option value="inactive">停用</option></select></label><button class="button primary">保存</button></form></AppDialog><AppDialog :open="Boolean(reviewing)" :title="approve?'通过导师申请':'驳回导师申请'" @update:open="reviewing=$event?reviewing:null"><label>审核意见<textarea v-model="comment" rows="3"></textarea></label><button class="button" :class="approve?'primary':'danger'" @click="review">确认</button></AppDialog></section></template>
