<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { teacherAPI } from '../../api/teacher'
import type { ApiKey } from '../../api/types'
import { APIError, apiErrorMessage } from '../../api/client'
import StatusBadge from '../../components/StatusBadge.vue'
import AppDialog from '../../components/AppDialog.vue'
import LoadingRegion from '../../components/LoadingRegion.vue'
import { useLoadState } from '../../composables/useLoadState'
import { useToast } from '../../composables/useToast'
const rows=ref<ApiKey[]>([]),selected=ref<ApiKey|null>(null),comment=ref(''),monthlyCredits=ref(''),query=ref(''),error=ref(''),confirmation=ref<'approve'|'reject'|null>(null),toast=useToast(),router=useRouter(),loadState=useLoadState()
const filtered=computed(()=>rows.value.filter(key=>!query.value||`${key.applicant?.name} ${key.applicant?.email} ${key.project.name}`.toLowerCase().includes(query.value.toLowerCase()))),ready=computed(()=>Boolean(selected.value?.models.every(model=>model.status==='active'&&model.route_ready&&model.credit_multiplier!==null)))
async function load(){await loadState.run(async()=>{try{rows.value=(await teacherAPI.keyReviews()).sort((a,b)=>a.created_at.localeCompare(b.created_at));error.value=''}catch(e){error.value=msg(e)}})}
async function open(row:ApiKey){try{selected.value=await teacherAPI.keyReview(row.id);monthlyCredits.value=selected.value.mentor_monthly_credits??selected.value.requested_monthly_credits??'';comment.value=''}catch(e){error.value=msg(e)}}
async function act(){if(!selected.value||!confirmation.value)return;const approve=confirmation.value==='approve';if(approve&&!monthlyCredits.value){error.value='终审通过必须填写最终月额度';return}if(!approve&&!comment.value.trim()){error.value='驳回必须填写原因';return}try{await teacherAPI.reviewKey(selected.value.id,approve,approve?monthlyCredits.value:undefined,comment.value||undefined);toast.success(approve?'终审已通过':'申请已驳回');selected.value=null;confirmation.value=null;await load()}catch(e){confirmation.value=null;error.value=apiErrorMessage(e,approve?'终审未完成，请检查申请状态后重试':'驳回未完成，请检查申请状态后重试')}}
function msg(e:unknown){return e instanceof APIError?e.message:'请求失败'}function refresh(){void load()}
onMounted(()=>{void load();window.addEventListener('nebula:refresh',refresh)});onBeforeUnmount(()=>window.removeEventListener('nebula:refresh',refresh))
</script>
<template><section class="page"><div class="page-heading"><div><p class="eyebrow">TEACHER</p><h1>审批密钥</h1><p class="muted">确认最终额度并原子占用项目当月额度。</p></div><button class="button secondary" @click="load">刷新</button></div><p v-if="error" class="error banner">{{error}}</p><label>搜索<input v-model="query"></label><LoadingRegion :initial-loading="loadState.initialLoading.value" :refreshing="loadState.refreshing.value" variant="split" label="正在加载终审队列"><div class="grid two"><section class="panel"><article v-for="key in filtered" :key="key.id" class="review-row"><div><strong>{{key.name}}</strong><p>{{key.applicant?.name}} · {{key.project.name}}</p><p class="muted">学生 {{key.requested_monthly_credits}} · 导师 {{key.mentor_monthly_credits}}</p></div><button class="button primary" @click="open(key)">终审</button></article></section><section class="panel"><template v-if="selected"><h2>{{selected.name}}</h2><p>项目总额度 {{selected.project.monthly_credit_quota}} credits</p><p>学生申请 {{selected.requested_monthly_credits}} · 导师审核 {{selected.mentor_monthly_credits}} credits</p><label>老师最终月额度（credits）<input v-model="monthlyCredits" inputmode="decimal" required></label><article v-for="model in selected.models" :key="model.id" class="list-row"><div><strong>{{model.display_name}}</strong><p class="muted">{{model.model_id}} · {{model.credit_multiplier??'未配置'}}x · 路由 {{model.route_ready?'就绪':'未就绪'}}</p></div><button v-if="model.status!=='active'||!model.route_ready||model.credit_multiplier===null" class="button ghost" @click="router.push(`/teacher/models?model=${model.id}`)">配置</button></article><label>终审意见<textarea v-model="comment" rows="4"></textarea></label><div class="actions"><button class="button danger" @click="confirmation='reject'">驳回</button><button class="button primary" :disabled="!ready" @click="confirmation='approve'">终审通过</button></div></template><div v-else class="empty">选择申请查看终审摘要</div></section></div></LoadingRegion><AppDialog :open="Boolean(confirmation)" :title="confirmation==='approve'?'确认终审通过':'确认驳回'" @update:open="confirmation=$event?confirmation:null"><p>{{confirmation==='approve'?`将占用 ${monthlyCredits} credits 项目额度。`:'驳回原因将永久记录。'}}</p><button class="button" :class="confirmation==='approve'?'primary':'danger'" @click="act">确认</button></AppDialog></section></template>
