<script setup lang="ts">
import { ref } from 'vue'
import { teacherAPI } from '../../api/teacher'
import type { Organization, ProjectUsage } from '../../api/types'
import { APIError } from '../../api/client'
import CreditDonut from '../../components/CreditDonut.vue'
import EmptyState from '../../components/EmptyState.vue'
import AppDialog from '../../components/AppDialog.vue'
import { useVisibilityPolling } from '../../composables/useVisibilityPolling'

const rows=ref<ProjectUsage[]>([]),organizations=ref<Organization[]>([]),expanded=ref<ProjectUsage|null>(null),month=ref(new Date().toISOString().slice(0,7)),organization=ref(''),query=ref(''),error=ref('')
async function load(){try{const params=new URLSearchParams({month:month.value,...(organization.value?{organization_id:organization.value}:{}),...(query.value?{q:query.value}:{})});[rows.value,organizations.value]=await Promise.all([teacherAPI.projectSpend(params.toString()),teacherAPI.organizations()]);error.value=''}catch(caught){error.value=caught instanceof APIError?caught.message:'加载项目花费失败'}}
useVisibilityPolling(load)
function rateLabel(row:ProjectUsage){if(Number(row.quota)===0)return'N/A';return`${(Number(row.charged)/Number(row.quota)*100).toFixed(1)}%`}
function remaining(row:ProjectUsage){return Math.max(0,Number(row.quota)-Number(row.charged)).toFixed(3)}
function segments(row:ProjectUsage){return row.models.map(model=>({name:model.name,value:Number(model.credits)})).concat([{name:'未消耗额度',value:Number(remaining(row)),color:'#dfe3ec'}])}
</script>

<template><section class="page"><div class="page-heading"><div><p class="eyebrow">TEACHER</p><h1>项目花费</h1><p class="muted">按项目查看本月实际 credits 开销；不包含成员、Key、邮箱或提示词。</p></div><label>月份<input v-model="month" type="month" @change="load"></label></div><p v-if="error" class="error banner">{{error}}</p><section class="panel"><div class="filter-grid"><label>组织<select v-model="organization"><option value="">全部组织</option><option v-for="item in organizations" :key="item.id" :value="item.id">{{item.name}}</option></select></label><label>项目名称<input v-model="query" placeholder="输入项目名称"></label></div><button class="button primary" @click="load">查询</button></section><section class="panel"><table v-if="rows.length" class="usage-table project-spend-table"><caption class="table-caption"><strong>项目级花费</strong> · 实际使用率 = 本月已用 credits / 项目月额度；图表按正倍率模型拆分。</caption><thead><tr><th scope="col">项目</th><th scope="col">实际开销</th><th scope="col">已用 / 总额度</th><th scope="col">0x 模型调用</th><th scope="col">操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.project_id"><th scope="row"><span class="project-spend-name"><strong>{{row.project_name}}</strong><small class="muted">剩余 {{remaining(row)}} credits</small></span></th><td class="project-spend-chart"><CreditDonut mini :segments="segments(row)" :total="Number(row.quota)" :label="`${row.project_name} 实际开销概览`"/></td><td><span class="project-spend-usage"><strong>{{row.charged}} / {{row.quota}}</strong><span>{{rateLabel(row)}} 已用</span><span v-if="Number(row.charged)>Number(row.quota)" class="error">超额 {{(Number(row.charged)-Number(row.quota)).toFixed(3)}} credits</span></span></td><td><div v-if="row.free_models.length" class="free-call-list"><span v-for="model in row.free_models" :key="model.id">{{model.name}} · {{model.calls}} 次</span></div><span v-else class="muted">无</span></td><td><button class="button ghost" @click="expanded=row">查看大图</button></td></tr></tbody></table><EmptyState v-else title="暂无项目花费数据" description="当前筛选条件下没有项目月额度快照。"/></section><AppDialog :open="Boolean(expanded)" :title="`${expanded?.project_name||''} · 实际开销`" wide @update:open="expanded=$event?expanded:null"><template v-if="expanded"><div class="usage-chart-card"><CreditDonut :segments="segments(expanded)" :total="Number(expanded.quota)" :label="`${expanded.project_name} 按模型拆分的实际开销`"/></div><table class="usage-table"><caption class="table-caption">正倍率模型 credits 与未消耗额度</caption><thead><tr><th>模型</th><th>credits</th></tr></thead><tbody><tr v-for="model in expanded.models" :key="model.id"><td>{{model.name}}</td><td class="numeric-cell">{{model.credits}}</td></tr><tr><td>未消耗额度</td><td class="numeric-cell">{{remaining(expanded)}}</td></tr></tbody></table></template></AppDialog></section></template>
