// Code generated by ent, DO NOT EDIT.

package monthlyusagecube

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldUpdatedAt, v))
}

// Month applies equality check predicate on the "month" field. It's identical to MonthEQ.
func Month(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldMonth, v))
}

// OrganizationID applies equality check predicate on the "organization_id" field. It's identical to OrganizationIDEQ.
func OrganizationID(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldOrganizationID, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldProjectID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldAPIKeyID, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldModelID, v))
}

// OrganizationName applies equality check predicate on the "organization_name" field. It's identical to OrganizationNameEQ.
func OrganizationName(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldOrganizationName, v))
}

// ProjectName applies equality check predicate on the "project_name" field. It's identical to ProjectNameEQ.
func ProjectName(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldProjectName, v))
}

// UserName applies equality check predicate on the "user_name" field. It's identical to UserNameEQ.
func UserName(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldUserName, v))
}

// APIKeyName applies equality check predicate on the "api_key_name" field. It's identical to APIKeyNameEQ.
func APIKeyName(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldAPIKeyName, v))
}

// ModelName applies equality check predicate on the "model_name" field. It's identical to ModelNameEQ.
func ModelName(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldModelName, v))
}

// ChargedMilli applies equality check predicate on the "charged_milli" field. It's identical to ChargedMilliEQ.
func ChargedMilli(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldChargedMilli, v))
}

// ChargedCount applies equality check predicate on the "charged_count" field. It's identical to ChargedCountEQ.
func ChargedCount(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldChargedCount, v))
}

// ZeroCostCount applies equality check predicate on the "zero_cost_count" field. It's identical to ZeroCostCountEQ.
func ZeroCostCount(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldZeroCostCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLTE(FieldUpdatedAt, v))
}

// MonthEQ applies the EQ predicate on the "month" field.
func MonthEQ(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldMonth, v))
}

// MonthNEQ applies the NEQ predicate on the "month" field.
func MonthNEQ(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNEQ(FieldMonth, v))
}

// MonthIn applies the In predicate on the "month" field.
func MonthIn(vs ...time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldIn(FieldMonth, vs...))
}

// MonthNotIn applies the NotIn predicate on the "month" field.
func MonthNotIn(vs ...time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNotIn(FieldMonth, vs...))
}

// MonthGT applies the GT predicate on the "month" field.
func MonthGT(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGT(FieldMonth, v))
}

// MonthGTE applies the GTE predicate on the "month" field.
func MonthGTE(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGTE(FieldMonth, v))
}

// MonthLT applies the LT predicate on the "month" field.
func MonthLT(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLT(FieldMonth, v))
}

// MonthLTE applies the LTE predicate on the "month" field.
func MonthLTE(v time.Time) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLTE(FieldMonth, v))
}

// OrganizationIDEQ applies the EQ predicate on the "organization_id" field.
func OrganizationIDEQ(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldOrganizationID, v))
}

// OrganizationIDNEQ applies the NEQ predicate on the "organization_id" field.
func OrganizationIDNEQ(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNEQ(FieldOrganizationID, v))
}

// OrganizationIDIn applies the In predicate on the "organization_id" field.
func OrganizationIDIn(vs ...uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldIn(FieldOrganizationID, vs...))
}

// OrganizationIDNotIn applies the NotIn predicate on the "organization_id" field.
func OrganizationIDNotIn(vs ...uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNotIn(FieldOrganizationID, vs...))
}

// OrganizationIDGT applies the GT predicate on the "organization_id" field.
func OrganizationIDGT(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGT(FieldOrganizationID, v))
}

// OrganizationIDGTE applies the GTE predicate on the "organization_id" field.
func OrganizationIDGTE(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGTE(FieldOrganizationID, v))
}

// OrganizationIDLT applies the LT predicate on the "organization_id" field.
func OrganizationIDLT(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLT(FieldOrganizationID, v))
}

// OrganizationIDLTE applies the LTE predicate on the "organization_id" field.
func OrganizationIDLTE(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLTE(FieldOrganizationID, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLTE(FieldProjectID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLTE(FieldUserID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLTE(FieldAPIKeyID, v))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v uuid.UUID) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLTE(FieldModelID, v))
}

// OrganizationNameEQ applies the EQ predicate on the "organization_name" field.
func OrganizationNameEQ(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldOrganizationName, v))
}

// OrganizationNameNEQ applies the NEQ predicate on the "organization_name" field.
func OrganizationNameNEQ(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNEQ(FieldOrganizationName, v))
}

// OrganizationNameIn applies the In predicate on the "organization_name" field.
func OrganizationNameIn(vs ...string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldIn(FieldOrganizationName, vs...))
}

// OrganizationNameNotIn applies the NotIn predicate on the "organization_name" field.
func OrganizationNameNotIn(vs ...string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNotIn(FieldOrganizationName, vs...))
}

// OrganizationNameGT applies the GT predicate on the "organization_name" field.
func OrganizationNameGT(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGT(FieldOrganizationName, v))
}

// OrganizationNameGTE applies the GTE predicate on the "organization_name" field.
func OrganizationNameGTE(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGTE(FieldOrganizationName, v))
}

// OrganizationNameLT applies the LT predicate on the "organization_name" field.
func OrganizationNameLT(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLT(FieldOrganizationName, v))
}

// OrganizationNameLTE applies the LTE predicate on the "organization_name" field.
func OrganizationNameLTE(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLTE(FieldOrganizationName, v))
}

// OrganizationNameContains applies the Contains predicate on the "organization_name" field.
func OrganizationNameContains(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldContains(FieldOrganizationName, v))
}

// OrganizationNameHasPrefix applies the HasPrefix predicate on the "organization_name" field.
func OrganizationNameHasPrefix(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldHasPrefix(FieldOrganizationName, v))
}

// OrganizationNameHasSuffix applies the HasSuffix predicate on the "organization_name" field.
func OrganizationNameHasSuffix(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldHasSuffix(FieldOrganizationName, v))
}

// OrganizationNameEqualFold applies the EqualFold predicate on the "organization_name" field.
func OrganizationNameEqualFold(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEqualFold(FieldOrganizationName, v))
}

// OrganizationNameContainsFold applies the ContainsFold predicate on the "organization_name" field.
func OrganizationNameContainsFold(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldContainsFold(FieldOrganizationName, v))
}

// ProjectNameEQ applies the EQ predicate on the "project_name" field.
func ProjectNameEQ(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldProjectName, v))
}

// ProjectNameNEQ applies the NEQ predicate on the "project_name" field.
func ProjectNameNEQ(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNEQ(FieldProjectName, v))
}

// ProjectNameIn applies the In predicate on the "project_name" field.
func ProjectNameIn(vs ...string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldIn(FieldProjectName, vs...))
}

// ProjectNameNotIn applies the NotIn predicate on the "project_name" field.
func ProjectNameNotIn(vs ...string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNotIn(FieldProjectName, vs...))
}

// ProjectNameGT applies the GT predicate on the "project_name" field.
func ProjectNameGT(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGT(FieldProjectName, v))
}

// ProjectNameGTE applies the GTE predicate on the "project_name" field.
func ProjectNameGTE(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGTE(FieldProjectName, v))
}

// ProjectNameLT applies the LT predicate on the "project_name" field.
func ProjectNameLT(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLT(FieldProjectName, v))
}

// ProjectNameLTE applies the LTE predicate on the "project_name" field.
func ProjectNameLTE(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLTE(FieldProjectName, v))
}

// ProjectNameContains applies the Contains predicate on the "project_name" field.
func ProjectNameContains(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldContains(FieldProjectName, v))
}

// ProjectNameHasPrefix applies the HasPrefix predicate on the "project_name" field.
func ProjectNameHasPrefix(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldHasPrefix(FieldProjectName, v))
}

// ProjectNameHasSuffix applies the HasSuffix predicate on the "project_name" field.
func ProjectNameHasSuffix(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldHasSuffix(FieldProjectName, v))
}

// ProjectNameEqualFold applies the EqualFold predicate on the "project_name" field.
func ProjectNameEqualFold(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEqualFold(FieldProjectName, v))
}

// ProjectNameContainsFold applies the ContainsFold predicate on the "project_name" field.
func ProjectNameContainsFold(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldContainsFold(FieldProjectName, v))
}

// UserNameEQ applies the EQ predicate on the "user_name" field.
func UserNameEQ(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldUserName, v))
}

// UserNameNEQ applies the NEQ predicate on the "user_name" field.
func UserNameNEQ(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNEQ(FieldUserName, v))
}

// UserNameIn applies the In predicate on the "user_name" field.
func UserNameIn(vs ...string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldIn(FieldUserName, vs...))
}

// UserNameNotIn applies the NotIn predicate on the "user_name" field.
func UserNameNotIn(vs ...string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNotIn(FieldUserName, vs...))
}

// UserNameGT applies the GT predicate on the "user_name" field.
func UserNameGT(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGT(FieldUserName, v))
}

// UserNameGTE applies the GTE predicate on the "user_name" field.
func UserNameGTE(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGTE(FieldUserName, v))
}

// UserNameLT applies the LT predicate on the "user_name" field.
func UserNameLT(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLT(FieldUserName, v))
}

// UserNameLTE applies the LTE predicate on the "user_name" field.
func UserNameLTE(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLTE(FieldUserName, v))
}

// UserNameContains applies the Contains predicate on the "user_name" field.
func UserNameContains(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldContains(FieldUserName, v))
}

// UserNameHasPrefix applies the HasPrefix predicate on the "user_name" field.
func UserNameHasPrefix(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldHasPrefix(FieldUserName, v))
}

// UserNameHasSuffix applies the HasSuffix predicate on the "user_name" field.
func UserNameHasSuffix(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldHasSuffix(FieldUserName, v))
}

// UserNameEqualFold applies the EqualFold predicate on the "user_name" field.
func UserNameEqualFold(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEqualFold(FieldUserName, v))
}

// UserNameContainsFold applies the ContainsFold predicate on the "user_name" field.
func UserNameContainsFold(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldContainsFold(FieldUserName, v))
}

// APIKeyNameEQ applies the EQ predicate on the "api_key_name" field.
func APIKeyNameEQ(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldAPIKeyName, v))
}

// APIKeyNameNEQ applies the NEQ predicate on the "api_key_name" field.
func APIKeyNameNEQ(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNEQ(FieldAPIKeyName, v))
}

// APIKeyNameIn applies the In predicate on the "api_key_name" field.
func APIKeyNameIn(vs ...string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldIn(FieldAPIKeyName, vs...))
}

// APIKeyNameNotIn applies the NotIn predicate on the "api_key_name" field.
func APIKeyNameNotIn(vs ...string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNotIn(FieldAPIKeyName, vs...))
}

// APIKeyNameGT applies the GT predicate on the "api_key_name" field.
func APIKeyNameGT(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGT(FieldAPIKeyName, v))
}

// APIKeyNameGTE applies the GTE predicate on the "api_key_name" field.
func APIKeyNameGTE(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGTE(FieldAPIKeyName, v))
}

// APIKeyNameLT applies the LT predicate on the "api_key_name" field.
func APIKeyNameLT(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLT(FieldAPIKeyName, v))
}

// APIKeyNameLTE applies the LTE predicate on the "api_key_name" field.
func APIKeyNameLTE(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLTE(FieldAPIKeyName, v))
}

// APIKeyNameContains applies the Contains predicate on the "api_key_name" field.
func APIKeyNameContains(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldContains(FieldAPIKeyName, v))
}

// APIKeyNameHasPrefix applies the HasPrefix predicate on the "api_key_name" field.
func APIKeyNameHasPrefix(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldHasPrefix(FieldAPIKeyName, v))
}

// APIKeyNameHasSuffix applies the HasSuffix predicate on the "api_key_name" field.
func APIKeyNameHasSuffix(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldHasSuffix(FieldAPIKeyName, v))
}

// APIKeyNameEqualFold applies the EqualFold predicate on the "api_key_name" field.
func APIKeyNameEqualFold(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEqualFold(FieldAPIKeyName, v))
}

// APIKeyNameContainsFold applies the ContainsFold predicate on the "api_key_name" field.
func APIKeyNameContainsFold(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldContainsFold(FieldAPIKeyName, v))
}

// ModelNameEQ applies the EQ predicate on the "model_name" field.
func ModelNameEQ(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldModelName, v))
}

// ModelNameNEQ applies the NEQ predicate on the "model_name" field.
func ModelNameNEQ(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNEQ(FieldModelName, v))
}

// ModelNameIn applies the In predicate on the "model_name" field.
func ModelNameIn(vs ...string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldIn(FieldModelName, vs...))
}

// ModelNameNotIn applies the NotIn predicate on the "model_name" field.
func ModelNameNotIn(vs ...string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNotIn(FieldModelName, vs...))
}

// ModelNameGT applies the GT predicate on the "model_name" field.
func ModelNameGT(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGT(FieldModelName, v))
}

// ModelNameGTE applies the GTE predicate on the "model_name" field.
func ModelNameGTE(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGTE(FieldModelName, v))
}

// ModelNameLT applies the LT predicate on the "model_name" field.
func ModelNameLT(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLT(FieldModelName, v))
}

// ModelNameLTE applies the LTE predicate on the "model_name" field.
func ModelNameLTE(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLTE(FieldModelName, v))
}

// ModelNameContains applies the Contains predicate on the "model_name" field.
func ModelNameContains(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldContains(FieldModelName, v))
}

// ModelNameHasPrefix applies the HasPrefix predicate on the "model_name" field.
func ModelNameHasPrefix(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldHasPrefix(FieldModelName, v))
}

// ModelNameHasSuffix applies the HasSuffix predicate on the "model_name" field.
func ModelNameHasSuffix(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldHasSuffix(FieldModelName, v))
}

// ModelNameEqualFold applies the EqualFold predicate on the "model_name" field.
func ModelNameEqualFold(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEqualFold(FieldModelName, v))
}

// ModelNameContainsFold applies the ContainsFold predicate on the "model_name" field.
func ModelNameContainsFold(v string) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldContainsFold(FieldModelName, v))
}

// ChargedMilliEQ applies the EQ predicate on the "charged_milli" field.
func ChargedMilliEQ(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldChargedMilli, v))
}

// ChargedMilliNEQ applies the NEQ predicate on the "charged_milli" field.
func ChargedMilliNEQ(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNEQ(FieldChargedMilli, v))
}

// ChargedMilliIn applies the In predicate on the "charged_milli" field.
func ChargedMilliIn(vs ...int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldIn(FieldChargedMilli, vs...))
}

// ChargedMilliNotIn applies the NotIn predicate on the "charged_milli" field.
func ChargedMilliNotIn(vs ...int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNotIn(FieldChargedMilli, vs...))
}

// ChargedMilliGT applies the GT predicate on the "charged_milli" field.
func ChargedMilliGT(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGT(FieldChargedMilli, v))
}

// ChargedMilliGTE applies the GTE predicate on the "charged_milli" field.
func ChargedMilliGTE(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGTE(FieldChargedMilli, v))
}

// ChargedMilliLT applies the LT predicate on the "charged_milli" field.
func ChargedMilliLT(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLT(FieldChargedMilli, v))
}

// ChargedMilliLTE applies the LTE predicate on the "charged_milli" field.
func ChargedMilliLTE(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLTE(FieldChargedMilli, v))
}

// ChargedCountEQ applies the EQ predicate on the "charged_count" field.
func ChargedCountEQ(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldChargedCount, v))
}

// ChargedCountNEQ applies the NEQ predicate on the "charged_count" field.
func ChargedCountNEQ(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNEQ(FieldChargedCount, v))
}

// ChargedCountIn applies the In predicate on the "charged_count" field.
func ChargedCountIn(vs ...int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldIn(FieldChargedCount, vs...))
}

// ChargedCountNotIn applies the NotIn predicate on the "charged_count" field.
func ChargedCountNotIn(vs ...int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNotIn(FieldChargedCount, vs...))
}

// ChargedCountGT applies the GT predicate on the "charged_count" field.
func ChargedCountGT(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGT(FieldChargedCount, v))
}

// ChargedCountGTE applies the GTE predicate on the "charged_count" field.
func ChargedCountGTE(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGTE(FieldChargedCount, v))
}

// ChargedCountLT applies the LT predicate on the "charged_count" field.
func ChargedCountLT(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLT(FieldChargedCount, v))
}

// ChargedCountLTE applies the LTE predicate on the "charged_count" field.
func ChargedCountLTE(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLTE(FieldChargedCount, v))
}

// ZeroCostCountEQ applies the EQ predicate on the "zero_cost_count" field.
func ZeroCostCountEQ(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldEQ(FieldZeroCostCount, v))
}

// ZeroCostCountNEQ applies the NEQ predicate on the "zero_cost_count" field.
func ZeroCostCountNEQ(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNEQ(FieldZeroCostCount, v))
}

// ZeroCostCountIn applies the In predicate on the "zero_cost_count" field.
func ZeroCostCountIn(vs ...int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldIn(FieldZeroCostCount, vs...))
}

// ZeroCostCountNotIn applies the NotIn predicate on the "zero_cost_count" field.
func ZeroCostCountNotIn(vs ...int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldNotIn(FieldZeroCostCount, vs...))
}

// ZeroCostCountGT applies the GT predicate on the "zero_cost_count" field.
func ZeroCostCountGT(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGT(FieldZeroCostCount, v))
}

// ZeroCostCountGTE applies the GTE predicate on the "zero_cost_count" field.
func ZeroCostCountGTE(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldGTE(FieldZeroCostCount, v))
}

// ZeroCostCountLT applies the LT predicate on the "zero_cost_count" field.
func ZeroCostCountLT(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLT(FieldZeroCostCount, v))
}

// ZeroCostCountLTE applies the LTE predicate on the "zero_cost_count" field.
func ZeroCostCountLTE(v int64) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.FieldLTE(FieldZeroCostCount, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MonthlyUsageCube) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MonthlyUsageCube) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MonthlyUsageCube) predicate.MonthlyUsageCube {
	return predicate.MonthlyUsageCube(sql.NotPredicates(p))
}
