// Code generated by ent, DO NOT EDIT.

package mentorprojectapplication

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldEQ(FieldCreatedAt, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldEQ(FieldProjectID, v))
}

// MentorID applies equality check predicate on the "mentor_id" field. It's identical to MentorIDEQ.
func MentorID(v uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldEQ(FieldMentorID, v))
}

// ReviewedBy applies equality check predicate on the "reviewed_by" field. It's identical to ReviewedByEQ.
func ReviewedBy(v uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldEQ(FieldReviewedBy, v))
}

// ReviewComment applies equality check predicate on the "review_comment" field. It's identical to ReviewCommentEQ.
func ReviewComment(v string) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldEQ(FieldReviewComment, v))
}

// ReviewedAt applies equality check predicate on the "reviewed_at" field. It's identical to ReviewedAtEQ.
func ReviewedAt(v time.Time) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldEQ(FieldReviewedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldLTE(FieldCreatedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldNotIn(FieldProjectID, vs...))
}

// MentorIDEQ applies the EQ predicate on the "mentor_id" field.
func MentorIDEQ(v uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldEQ(FieldMentorID, v))
}

// MentorIDNEQ applies the NEQ predicate on the "mentor_id" field.
func MentorIDNEQ(v uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldNEQ(FieldMentorID, v))
}

// MentorIDIn applies the In predicate on the "mentor_id" field.
func MentorIDIn(vs ...uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldIn(FieldMentorID, vs...))
}

// MentorIDNotIn applies the NotIn predicate on the "mentor_id" field.
func MentorIDNotIn(vs ...uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldNotIn(FieldMentorID, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldNotIn(FieldStatus, vs...))
}

// ReviewedByEQ applies the EQ predicate on the "reviewed_by" field.
func ReviewedByEQ(v uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldEQ(FieldReviewedBy, v))
}

// ReviewedByNEQ applies the NEQ predicate on the "reviewed_by" field.
func ReviewedByNEQ(v uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldNEQ(FieldReviewedBy, v))
}

// ReviewedByIn applies the In predicate on the "reviewed_by" field.
func ReviewedByIn(vs ...uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldIn(FieldReviewedBy, vs...))
}

// ReviewedByNotIn applies the NotIn predicate on the "reviewed_by" field.
func ReviewedByNotIn(vs ...uuid.UUID) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldNotIn(FieldReviewedBy, vs...))
}

// ReviewedByIsNil applies the IsNil predicate on the "reviewed_by" field.
func ReviewedByIsNil() predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldIsNull(FieldReviewedBy))
}

// ReviewedByNotNil applies the NotNil predicate on the "reviewed_by" field.
func ReviewedByNotNil() predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldNotNull(FieldReviewedBy))
}

// ReviewCommentEQ applies the EQ predicate on the "review_comment" field.
func ReviewCommentEQ(v string) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldEQ(FieldReviewComment, v))
}

// ReviewCommentNEQ applies the NEQ predicate on the "review_comment" field.
func ReviewCommentNEQ(v string) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldNEQ(FieldReviewComment, v))
}

// ReviewCommentIn applies the In predicate on the "review_comment" field.
func ReviewCommentIn(vs ...string) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldIn(FieldReviewComment, vs...))
}

// ReviewCommentNotIn applies the NotIn predicate on the "review_comment" field.
func ReviewCommentNotIn(vs ...string) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldNotIn(FieldReviewComment, vs...))
}

// ReviewCommentGT applies the GT predicate on the "review_comment" field.
func ReviewCommentGT(v string) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldGT(FieldReviewComment, v))
}

// ReviewCommentGTE applies the GTE predicate on the "review_comment" field.
func ReviewCommentGTE(v string) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldGTE(FieldReviewComment, v))
}

// ReviewCommentLT applies the LT predicate on the "review_comment" field.
func ReviewCommentLT(v string) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldLT(FieldReviewComment, v))
}

// ReviewCommentLTE applies the LTE predicate on the "review_comment" field.
func ReviewCommentLTE(v string) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldLTE(FieldReviewComment, v))
}

// ReviewCommentContains applies the Contains predicate on the "review_comment" field.
func ReviewCommentContains(v string) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldContains(FieldReviewComment, v))
}

// ReviewCommentHasPrefix applies the HasPrefix predicate on the "review_comment" field.
func ReviewCommentHasPrefix(v string) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldHasPrefix(FieldReviewComment, v))
}

// ReviewCommentHasSuffix applies the HasSuffix predicate on the "review_comment" field.
func ReviewCommentHasSuffix(v string) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldHasSuffix(FieldReviewComment, v))
}

// ReviewCommentIsNil applies the IsNil predicate on the "review_comment" field.
func ReviewCommentIsNil() predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldIsNull(FieldReviewComment))
}

// ReviewCommentNotNil applies the NotNil predicate on the "review_comment" field.
func ReviewCommentNotNil() predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldNotNull(FieldReviewComment))
}

// ReviewCommentEqualFold applies the EqualFold predicate on the "review_comment" field.
func ReviewCommentEqualFold(v string) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldEqualFold(FieldReviewComment, v))
}

// ReviewCommentContainsFold applies the ContainsFold predicate on the "review_comment" field.
func ReviewCommentContainsFold(v string) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldContainsFold(FieldReviewComment, v))
}

// ReviewedAtEQ applies the EQ predicate on the "reviewed_at" field.
func ReviewedAtEQ(v time.Time) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedAtNEQ applies the NEQ predicate on the "reviewed_at" field.
func ReviewedAtNEQ(v time.Time) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldNEQ(FieldReviewedAt, v))
}

// ReviewedAtIn applies the In predicate on the "reviewed_at" field.
func ReviewedAtIn(vs ...time.Time) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldIn(FieldReviewedAt, vs...))
}

// ReviewedAtNotIn applies the NotIn predicate on the "reviewed_at" field.
func ReviewedAtNotIn(vs ...time.Time) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldNotIn(FieldReviewedAt, vs...))
}

// ReviewedAtGT applies the GT predicate on the "reviewed_at" field.
func ReviewedAtGT(v time.Time) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldGT(FieldReviewedAt, v))
}

// ReviewedAtGTE applies the GTE predicate on the "reviewed_at" field.
func ReviewedAtGTE(v time.Time) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldGTE(FieldReviewedAt, v))
}

// ReviewedAtLT applies the LT predicate on the "reviewed_at" field.
func ReviewedAtLT(v time.Time) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldLT(FieldReviewedAt, v))
}

// ReviewedAtLTE applies the LTE predicate on the "reviewed_at" field.
func ReviewedAtLTE(v time.Time) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldLTE(FieldReviewedAt, v))
}

// ReviewedAtIsNil applies the IsNil predicate on the "reviewed_at" field.
func ReviewedAtIsNil() predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldIsNull(FieldReviewedAt))
}

// ReviewedAtNotNil applies the NotNil predicate on the "reviewed_at" field.
func ReviewedAtNotNil() predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.FieldNotNull(FieldReviewedAt))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMentor applies the HasEdge predicate on the "mentor" edge.
func HasMentor() predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MentorTable, MentorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMentorWith applies the HasEdge predicate on the "mentor" edge with a given conditions (other predicates).
func HasMentorWith(preds ...predicate.User) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(func(s *sql.Selector) {
		step := newMentorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReviewer applies the HasEdge predicate on the "reviewer" edge.
func HasReviewer() predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ReviewerTable, ReviewerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReviewerWith applies the HasEdge predicate on the "reviewer" edge with a given conditions (other predicates).
func HasReviewerWith(preds ...predicate.User) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(func(s *sql.Selector) {
		step := newReviewerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MentorProjectApplication) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MentorProjectApplication) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MentorProjectApplication) predicate.MentorProjectApplication {
	return predicate.MentorProjectApplication(sql.NotPredicates(p))
}
