<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { mentorAPI } from '../../api/mentor'
import type { ApiKey } from '../../api/types'
import { APIError } from '../../api/client'
import AppDialog from '../../components/AppDialog.vue'
import LoadingRegion from '../../components/LoadingRegion.vue'
import StatusBadge from '../../components/StatusBadge.vue'
import { useLoadState } from '../../composables/useLoadState'
import { useToast } from '../../composables/useToast'
const rows=ref<ApiKey[]>([]),selected=ref<ApiKey|null>(null),comment=ref(''),monthlyCredits=ref(''),query=ref(''),project=ref(''),error=ref(''),confirmReject=ref(false),toast=useToast(),loadState=useLoadState()
const filtered=computed(()=>rows.value.filter(key=>(!query.value||`${key.applicant?.name} ${key.applicant?.email}`.toLowerCase().includes(query.value.toLowerCase()))&&(!project.value||key.project.id===project.value))),projects=computed(()=>[...new Map(rows.value.map(key=>[key.project.id,key.project])).values()])
async function load(){await loadState.run(async()=>{try{rows.value=(await mentorAPI.reviews()).sort((a,b)=>a.created_at.localeCompare(b.created_at));error.value=''}catch(e){error.value=msg(e)}})}
async function open(row:ApiKey){try{selected.value=await mentorAPI.review(row.id);monthlyCredits.value=selected.value.requested_monthly_credits;comment.value=''}catch(e){error.value=msg(e)}}
async function act(approve:boolean){if(!selected.value)return;if(approve&&!monthlyCredits.value){error.value='通过初审必须填写导师审核额度';return}if(!approve&&!comment.value.trim()){error.value='驳回必须填写原因';return}try{if(approve)await mentorAPI.approve(selected.value.id,monthlyCredits.value,comment.value||undefined);else await mentorAPI.reject(selected.value.id,comment.value);toast.success(approve?'已通过初审':'已驳回申请');selected.value=null;confirmReject.value=false;await load()}catch(e){error.value=msg(e)}}
function msg(e:unknown){return e instanceof APIError?e.message:'请求失败'}function refresh(){void load()}
onMounted(()=>{void load();window.addEventListener('nebula:refresh',refresh)});onBeforeUnmount(()=>window.removeEventListener('nebula:refresh',refresh))
</script>
<template><section class="page"><div class="page-heading"><div><p class="eyebrow">MENTOR</p><h1>审核密钥</h1><p class="muted">核对学生申请额度并给出导师审核额度。</p></div><button class="button secondary" @click="load">刷新</button></div><p v-if="error" class="error banner">{{error}}</p><section class="panel"><div class="grid two"><label>搜索申请人<input v-model="query"></label><label>项目<select v-model="project"><option value="">全部</option><option v-for="item in projects" :key="item.id" :value="item.id">{{item.name}}</option></select></label></div></section><LoadingRegion :initial-loading="loadState.initialLoading.value" :refreshing="loadState.refreshing.value" variant="split" label="正在加载审核队列"><div class="grid two"><section class="panel"><article v-for="key in filtered" :key="key.id" class="review-row"><div><strong>{{key.name}}</strong><p>{{key.applicant?.name}} · {{key.project.name}}</p><p class="muted">申请 {{key.requested_monthly_credits}} credits</p></div><button class="button primary" @click="open(key)">审核</button></article></section><section class="panel"><template v-if="selected"><div class="row"><h2>{{selected.name}}</h2><StatusBadge :status="selected.status"/></div><p>{{selected.applicant?.name}}（{{selected.applicant?.email}}）</p><p>学生申请额度：{{selected.requested_monthly_credits}} credits</p><label>导师审核月额度（credits）<input v-model="monthlyCredits" inputmode="decimal" required></label><div v-for="model in selected.models" :key="model.id" class="list-row"><span>{{model.display_name}} · {{model.credit_multiplier??'未配置'}}x</span><StatusBadge :status="model.status"/></div><label>审核意见<textarea v-model="comment" rows="4" placeholder="通过可选；驳回必填"></textarea></label><div class="actions"><button class="button danger" @click="confirmReject=true">驳回</button><button class="button primary" @click="act(true)">通过</button></div></template><div v-else class="empty">选择一条申请</div></section></div></LoadingRegion><AppDialog :open="confirmReject" title="确认驳回" @update:open="confirmReject=$event"><button class="button danger" @click="act(false)">确认驳回</button></AppDialog></section></template>
