<script setup lang="ts">
import { reactive, ref } from 'vue'
import { mentorAPI } from '../../api/mentor'
import type { CallLog } from '../../api/types'
import { APIError } from '../../api/client'
import AppDialog from '../../components/AppDialog.vue'
import EmptyState from '../../components/EmptyState.vue'
import StatusBadge from '../../components/StatusBadge.vue'
import MentorUsageFilters, { type MentorResourceFilter } from '../../components/MentorUsageFilters.vue'
import { useVisibilityPolling } from '../../composables/useVisibilityPolling'

const rows=ref<CallLog[]>([]),selected=ref<CallLog|null>(null),nextCursor=ref<string|null>(null),error=ref('')
const filter=reactive<MentorResourceFilter&{start:string;end:string}>({project_id:'',user_id:'',api_key_id:'',model_id:'',status:'',start:'',end:''})
const statusOptions=[{value:'succeeded',label:'成功'},{value:'upstream_failed',label:'上游失败'},{value:'outcome_unknown',label:'结果未知'}]
function query(cursor=''){const entries:Array<[string,string]>=Object.entries(filter).filter(([,value])=>value).map(([key,value])=>[key,(key==='start'||key==='end')?new Date(value).toISOString():value]);const params=new URLSearchParams(entries);if(cursor)params.set('cursor',cursor);return params.toString()}
async function load(append=false){try{const page=await mentorAPI.callLogs(query(append?nextCursor.value??'':''));rows.value=append?rows.value.concat(page.items):page.items;nextCursor.value=page.next_cursor??null;error.value=''}catch(caught){error.value=caught instanceof APIError?caught.message:'加载调用日志失败'}}
async function detail(id:string){try{selected.value=await mentorAPI.callLog(id)}catch(caught){error.value=caught instanceof APIError?caught.message:'加载调用详情失败'}}
useVisibilityPolling(()=>load())
</script>

<template><section class="page"><div class="page-heading"><div><p class="eyebrow">MENTOR</p><h1>调用日志</h1><p class="muted">按项目、成员、Key、模型从左到右缩小范围；任何下拉框留空都表示当前范围内全部。</p></div><button class="button secondary" @click="load()">刷新</button></div><p v-if="error" class="error banner">{{error}}</p><section class="panel"><MentorUsageFilters :filter="filter" :status-options="statusOptions" @error="error=$event"/><div class="filter-grid"><label>开始时间<input v-model="filter.start" type="datetime-local"></label><label>结束时间<input v-model="filter.end" type="datetime-local"></label></div><button class="button primary" @click="load()">查询</button></section><section class="panel"><table v-if="rows.length" class="usage-table"><thead><tr><th>时间</th><th>用户 / Key</th><th>项目 / 模型</th><th>供应商</th><th>结果</th><th>credits</th><th></th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td>{{new Date(row.created_at).toLocaleString()}}</td><td>{{row.user_name}}<br><span class="muted">{{row.api_key_name}}</span></td><td>{{row.project_name}}<br><span class="muted">{{row.model_name}} · {{row.multiplier}}x</span></td><td>{{row.provider_name||'未确定'}}</td><td><StatusBadge :status="row.outcome"/></td><td>{{row.credits}}</td><td><button class="button ghost" @click="detail(row.id)">详情</button></td></tr></tbody></table><EmptyState v-else title="暂无调用记录" description="只有你当前负责项目的网关计费操作会出现在这里。"/><button v-if="nextCursor" class="button secondary wide" @click="load(true)">加载更多</button></section><AppDialog :open="Boolean(selected)" title="调用详情" wide @update:open="selected=$event?selected:null"><template v-if="selected"><div class="usage-summary"><div class="usage-stat">request ID<strong>{{selected.request_id}}</strong></div><div class="usage-stat">协议<strong>{{selected.protocol}}</strong></div><div class="usage-stat">credits<strong>{{selected.credits}}</strong></div></div><p>{{selected.path}} · {{selected.billing_state}} · {{selected.outcome}}</p><p v-if="selected.error_message" class="error">{{selected.error_category}} · {{selected.error_message}}</p><h3>供应商尝试</h3><table class="usage-table"><thead><tr><th>供应商</th><th>状态</th><th>HTTP</th><th>耗时</th><th>脱敏错误</th></tr></thead><tbody><tr v-for="(attempt,index) in selected.attempts||[]" :key="index"><td>{{attempt.provider_name}}</td><td>{{attempt.status}}</td><td>{{attempt.http_status??'—'}}</td><td>{{attempt.latency_ms}}ms</td><td>{{attempt.error_message||'—'}}</td></tr></tbody></table></template></AppDialog></section></template>
