<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { mentorAPI } from '../../api/mentor'
import type { ApiKey, Application, Organization, Project, ProjectUsage } from '../../api/types'
import { APIError } from '../../api/client'
import StatusBadge from '../../components/StatusBadge.vue'
import AppDialog from '../../components/AppDialog.vue'
import LoadingRegion from '../../components/LoadingRegion.vue'
import CreditDonut from '../../components/CreditDonut.vue'
import { useLoadState } from '../../composables/useLoadState'
import { useToast } from '../../composables/useToast'
const orgs=ref<Organization[]>([]),groups=ref<Array<{org:Organization;projects:Project[]}>>([]),applications=ref<Application[]>([]),activeKeys=ref<ApiKey[]>([]),activeProject=ref<Project|null>(null),projectUsage=ref<ProjectUsage|null>(null),revokeKey=ref<ApiKey|null>(null),reason=ref(''),error=ref(''),toast=useToast(),loadState=useLoadState(),keyLoadState=useLoadState()
async function load(){await loadState.run(async()=>{try{orgs.value=await mentorAPI.organizations();groups.value=await Promise.all(orgs.value.map(async org=>({org,projects:await mentorAPI.projects(org.id)})));applications.value=await mentorAPI.applications()}catch(e){error.value=msg(e)}})}
async function apply(project:Project){try{await mentorAPI.apply(project.id);toast.success('项目申请已提交');await load()}catch(e){error.value=msg(e)}}
async function showKeys(project:Project){activeProject.value=project;await keyLoadState.run(async()=>{try{[activeKeys.value,projectUsage.value]=await Promise.all([mentorAPI.activeKeys(project.id),mentorAPI.usage(project.id)])}catch(e){error.value=msg(e)}})}
async function revoke(){if(!revokeKey.value||!reason.value.trim())return;try{await mentorAPI.revoke(revokeKey.value.id,reason.value);toast.success('密钥已撤销并立即失效');revokeKey.value=null;reason.value='';await showKeys(activeProject.value!)}catch(e){error.value=msg(e)}}
function msg(e:unknown){return e instanceof APIError?e.message:'请求失败'};onMounted(load)
</script>
<template><section class="page"><div class="page-heading"><div><p class="eyebrow">MENTOR</p><h1>项目管理</h1></div><button class="button secondary" @click="load">刷新</button></div><p v-if="error" class="error banner">{{error}}</p><LoadingRegion :initial-loading="loadState.initialLoading.value" :refreshing="loadState.refreshing.value" variant="split" label="正在加载项目和申请"><section v-for="group in groups" :key="group.org.id" class="panel" style="margin-bottom:20px"><h2>{{group.org.name}}</h2><div class="grid two"><article v-for="project in group.projects" :key="project.id" class="panel"><div class="row"><strong>{{project.name}}</strong><StatusBadge :status="project.status"/></div><p class="muted">{{project.description||'暂无说明'}}</p><div class="actions"><button v-if="project.is_responsible" class="button ghost" @click="showKeys(project)">项目用量</button><StatusBadge v-else-if="project.application_status==='pending'" status="pending"/><button v-else class="button primary" :disabled="project.status!=='active'" @click="apply(project)">申请负责</button></div></article></div></section><section class="panel"><h2>申请历史</h2><article v-for="item in applications" :key="item.id" class="list-row"><div><strong>{{item.project.name}}</strong><p class="muted">{{item.review_comment||'暂无老师意见'}}</p></div><StatusBadge :status="item.status"/></article><div v-if="!applications.length" class="empty">暂无申请记录</div></section></LoadingRegion><AppDialog :open="Boolean(activeProject)" :title="`${activeProject?.name||''} · 项目用量`" wide @update:open="activeProject=$event?activeProject:null"><LoadingRegion :initial-loading="keyLoadState.initialLoading.value" :refreshing="keyLoadState.refreshing.value" variant="list" label="正在加载项目用量"><div v-if="projectUsage" class="grid two"><div><h2>实际开销</h2><CreditDonut :segments="projectUsage.members.map(m=>({name:m.user_name,value:Number(m.credits)})).concat([{name:'未消耗',value:Math.max(0,Number(projectUsage.quota)-Number(projectUsage.charged))}])" :total="Number(projectUsage.quota)" label="项目实际开销"/></div><div><h2>Key 额度</h2><p class="muted">项目额度 {{projectUsage.quota}} · 已分配 {{projectUsage.allocated}} · 可分配 {{projectUsage.available}}</p></div></div><article v-for="key in activeKeys" :key="key.id" class="list-row"><div><strong>{{key.name}}</strong><p class="muted">{{key.applicant?.name}} · {{key.monthly_credits||'未配置'}} credits</p></div><button class="button danger" @click="revokeKey=key">撤销</button></article><div v-if="!activeKeys.length" class="empty">暂无生效密钥</div></LoadingRegion></AppDialog><AppDialog :open="Boolean(revokeKey)" title="撤销 ACTIVE Key" @update:open="revokeKey=$event?revokeKey:null"><p>撤销后密钥立即失效，且无法恢复。</p><label>撤销原因<textarea v-model="reason" rows="3" required/></label><div class="actions"><button class="button danger" :disabled="!reason.trim()" @click="revoke">确认撤销</button></div></AppDialog></section></template>
