// Code generated by ent, DO NOT EDIT.

package modelbinding

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the modelbinding type in the database.
	Label = "model_binding"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldProviderID holds the string denoting the provider_id field in the database.
	FieldProviderID = "provider_id"
	// FieldUpstreamModelName holds the string denoting the upstream_model_name field in the database.
	FieldUpstreamModelName = "upstream_model_name"
	// FieldAdapter holds the string denoting the adapter field in the database.
	FieldAdapter = "adapter"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgeModel holds the string denoting the model edge name in mutations.
	EdgeModel = "model"
	// EdgeProvider holds the string denoting the provider edge name in mutations.
	EdgeProvider = "provider"
	// Table holds the table name of the modelbinding in the database.
	Table = "model_bindings"
	// ModelTable is the table that holds the model relation/edge.
	ModelTable = "model_bindings"
	// ModelInverseTable is the table name for the Model entity.
	// It exists in this package in order to avoid circular dependency with the "model" package.
	ModelInverseTable = "models"
	// ModelColumn is the table column denoting the model relation/edge.
	ModelColumn = "model_id"
	// ProviderTable is the table that holds the provider relation/edge.
	ProviderTable = "model_bindings"
	// ProviderInverseTable is the table name for the Provider entity.
	// It exists in this package in order to avoid circular dependency with the "provider" package.
	ProviderInverseTable = "providers"
	// ProviderColumn is the table column denoting the provider relation/edge.
	ProviderColumn = "provider_id"
)

// Columns holds all SQL columns for modelbinding fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldModelID,
	FieldProviderID,
	FieldUpstreamModelName,
	FieldAdapter,
	FieldPriority,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// UpstreamModelNameValidator is a validator for the "upstream_model_name" field. It is called by the builders before save.
	UpstreamModelNameValidator func(string) error
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// PriorityValidator is a validator for the "priority" field. It is called by the builders before save.
	PriorityValidator func(int) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Adapter defines the type for the "adapter" enum field.
type Adapter string

// Adapter values.
const (
	AdapterOpenaiCompatible   Adapter = "openai_compatible"
	AdapterOpenaiResponses    Adapter = "openai_responses"
	AdapterOpenaiEmbeddings   Adapter = "openai_embeddings"
	AdapterOpenaiImages       Adapter = "openai_images"
	AdapterOpenaiAudio        Adapter = "openai_audio"
	AdapterOpenaiVideo        Adapter = "openai_video"
	AdapterOpenaiRealtime     Adapter = "openai_realtime"
	AdapterOpenaiModerations  Adapter = "openai_moderations"
	AdapterAnthropic          Adapter = "anthropic"
	AdapterCohereRerankV2     Adapter = "cohere_rerank_v2"
	AdapterGoogleGeminiV1beta Adapter = "google_gemini_v1beta"
)

func (a Adapter) String() string {
	return string(a)
}

// AdapterValidator is a validator for the "adapter" field enum values. It is called by the builders before save.
func AdapterValidator(a Adapter) error {
	switch a {
	case AdapterOpenaiCompatible, AdapterOpenaiResponses, AdapterOpenaiEmbeddings, AdapterOpenaiImages, AdapterOpenaiAudio, AdapterOpenaiVideo, AdapterOpenaiRealtime, AdapterOpenaiModerations, AdapterAnthropic, AdapterCohereRerankV2, AdapterGoogleGeminiV1beta:
		return nil
	default:
		return fmt.Errorf("modelbinding: invalid enum value for adapter field: %q", a)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive   Status = "active"
	StatusInactive Status = "inactive"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusInactive:
		return nil
	default:
		return fmt.Errorf("modelbinding: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the ModelBinding queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByProviderID orders the results by the provider_id field.
func ByProviderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderID, opts...).ToFunc()
}

// ByUpstreamModelName orders the results by the upstream_model_name field.
func ByUpstreamModelName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModelName, opts...).ToFunc()
}

// ByAdapter orders the results by the adapter field.
func ByAdapter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdapter, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByModelField orders the results by model field.
func ByModelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newModelStep(), sql.OrderByField(field, opts...))
	}
}

// ByProviderField orders the results by provider field.
func ByProviderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProviderStep(), sql.OrderByField(field, opts...))
	}
}
func newModelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ModelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ModelTable, ModelColumn),
	)
}
func newProviderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProviderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProviderTable, ProviderColumn),
	)
}
