// Code generated by ent, DO NOT EDIT.

package gatewaycall

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the gatewaycall type in the database.
	Label = "gateway_call"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldMonth holds the string denoting the month field in the database.
	FieldMonth = "month"
	// FieldOrganizationID holds the string denoting the organization_id field in the database.
	FieldOrganizationID = "organization_id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldProviderID holds the string denoting the provider_id field in the database.
	FieldProviderID = "provider_id"
	// FieldOrganizationName holds the string denoting the organization_name field in the database.
	FieldOrganizationName = "organization_name"
	// FieldProjectName holds the string denoting the project_name field in the database.
	FieldProjectName = "project_name"
	// FieldUserName holds the string denoting the user_name field in the database.
	FieldUserName = "user_name"
	// FieldAPIKeyName holds the string denoting the api_key_name field in the database.
	FieldAPIKeyName = "api_key_name"
	// FieldModelName holds the string denoting the model_name field in the database.
	FieldModelName = "model_name"
	// FieldProviderName holds the string denoting the provider_name field in the database.
	FieldProviderName = "provider_name"
	// FieldProtocol holds the string denoting the protocol field in the database.
	FieldProtocol = "protocol"
	// FieldRequestPath holds the string denoting the request_path field in the database.
	FieldRequestPath = "request_path"
	// FieldMultiplierMilli holds the string denoting the multiplier_milli field in the database.
	FieldMultiplierMilli = "multiplier_milli"
	// FieldCreditMilli holds the string denoting the credit_milli field in the database.
	FieldCreditMilli = "credit_milli"
	// FieldBillingState holds the string denoting the billing_state field in the database.
	FieldBillingState = "billing_state"
	// FieldOutcome holds the string denoting the outcome field in the database.
	FieldOutcome = "outcome"
	// FieldErrorCategory holds the string denoting the error_category field in the database.
	FieldErrorCategory = "error_category"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldLeaseExpiresAt holds the string denoting the lease_expires_at field in the database.
	FieldLeaseExpiresAt = "lease_expires_at"
	// FieldSentAt holds the string denoting the sent_at field in the database.
	FieldSentAt = "sent_at"
	// FieldFinalizedAt holds the string denoting the finalized_at field in the database.
	FieldFinalizedAt = "finalized_at"
	// EdgeAttempts holds the string denoting the attempts edge name in mutations.
	EdgeAttempts = "attempts"
	// EdgeMonitoredInput holds the string denoting the monitored_input edge name in mutations.
	EdgeMonitoredInput = "monitored_input"
	// Table holds the table name of the gatewaycall in the database.
	Table = "gateway_calls"
	// AttemptsTable is the table that holds the attempts relation/edge.
	AttemptsTable = "gateway_call_attempts"
	// AttemptsInverseTable is the table name for the GatewayCallAttempt entity.
	// It exists in this package in order to avoid circular dependency with the "gatewaycallattempt" package.
	AttemptsInverseTable = "gateway_call_attempts"
	// AttemptsColumn is the table column denoting the attempts relation/edge.
	AttemptsColumn = "call_id"
	// MonitoredInputTable is the table that holds the monitored_input relation/edge.
	MonitoredInputTable = "monitored_inputs"
	// MonitoredInputInverseTable is the table name for the MonitoredInput entity.
	// It exists in this package in order to avoid circular dependency with the "monitoredinput" package.
	MonitoredInputInverseTable = "monitored_inputs"
	// MonitoredInputColumn is the table column denoting the monitored_input relation/edge.
	MonitoredInputColumn = "call_id"
)

// Columns holds all SQL columns for gatewaycall fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldRequestID,
	FieldMonth,
	FieldOrganizationID,
	FieldProjectID,
	FieldUserID,
	FieldAPIKeyID,
	FieldModelID,
	FieldProviderID,
	FieldOrganizationName,
	FieldProjectName,
	FieldUserName,
	FieldAPIKeyName,
	FieldModelName,
	FieldProviderName,
	FieldProtocol,
	FieldRequestPath,
	FieldMultiplierMilli,
	FieldCreditMilli,
	FieldBillingState,
	FieldOutcome,
	FieldErrorCategory,
	FieldErrorMessage,
	FieldLeaseExpiresAt,
	FieldSentAt,
	FieldFinalizedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// OrganizationNameValidator is a validator for the "organization_name" field. It is called by the builders before save.
	OrganizationNameValidator func(string) error
	// ProjectNameValidator is a validator for the "project_name" field. It is called by the builders before save.
	ProjectNameValidator func(string) error
	// UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	UserNameValidator func(string) error
	// APIKeyNameValidator is a validator for the "api_key_name" field. It is called by the builders before save.
	APIKeyNameValidator func(string) error
	// ModelNameValidator is a validator for the "model_name" field. It is called by the builders before save.
	ModelNameValidator func(string) error
	// ProviderNameValidator is a validator for the "provider_name" field. It is called by the builders before save.
	ProviderNameValidator func(string) error
	// ProtocolValidator is a validator for the "protocol" field. It is called by the builders before save.
	ProtocolValidator func(string) error
	// RequestPathValidator is a validator for the "request_path" field. It is called by the builders before save.
	RequestPathValidator func(string) error
	// MultiplierMilliValidator is a validator for the "multiplier_milli" field. It is called by the builders before save.
	MultiplierMilliValidator func(int64) error
	// CreditMilliValidator is a validator for the "credit_milli" field. It is called by the builders before save.
	CreditMilliValidator func(int64) error
	// ErrorCategoryValidator is a validator for the "error_category" field. It is called by the builders before save.
	ErrorCategoryValidator func(string) error
	// ErrorMessageValidator is a validator for the "error_message" field. It is called by the builders before save.
	ErrorMessageValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// BillingState defines the type for the "billing_state" enum field.
type BillingState string

// BillingStatePending is the default value of the BillingState enum.
const DefaultBillingState = BillingStatePending

// BillingState values.
const (
	BillingStatePending BillingState = "pending"
	BillingStateCharged BillingState = "charged"
	BillingStateFailed  BillingState = "failed"
)

func (bs BillingState) String() string {
	return string(bs)
}

// BillingStateValidator is a validator for the "billing_state" field enum values. It is called by the builders before save.
func BillingStateValidator(bs BillingState) error {
	switch bs {
	case BillingStatePending, BillingStateCharged, BillingStateFailed:
		return nil
	default:
		return fmt.Errorf("gatewaycall: invalid enum value for billing_state field: %q", bs)
	}
}

// Outcome defines the type for the "outcome" enum field.
type Outcome string

// OutcomePending is the default value of the Outcome enum.
const DefaultOutcome = OutcomePending

// Outcome values.
const (
	OutcomePending        Outcome = "pending"
	OutcomeSucceeded      Outcome = "succeeded"
	OutcomeUpstreamFailed Outcome = "upstream_failed"
	OutcomeQuotaRejected  Outcome = "quota_rejected"
	OutcomeOutcomeUnknown Outcome = "outcome_unknown"
)

func (o Outcome) String() string {
	return string(o)
}

// OutcomeValidator is a validator for the "outcome" field enum values. It is called by the builders before save.
func OutcomeValidator(o Outcome) error {
	switch o {
	case OutcomePending, OutcomeSucceeded, OutcomeUpstreamFailed, OutcomeQuotaRejected, OutcomeOutcomeUnknown:
		return nil
	default:
		return fmt.Errorf("gatewaycall: invalid enum value for outcome field: %q", o)
	}
}

// OrderOption defines the ordering options for the GatewayCall queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByMonth orders the results by the month field.
func ByMonth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonth, opts...).ToFunc()
}

// ByOrganizationID orders the results by the organization_id field.
func ByOrganizationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByProviderID orders the results by the provider_id field.
func ByProviderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderID, opts...).ToFunc()
}

// ByOrganizationName orders the results by the organization_name field.
func ByOrganizationName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationName, opts...).ToFunc()
}

// ByProjectName orders the results by the project_name field.
func ByProjectName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectName, opts...).ToFunc()
}

// ByUserName orders the results by the user_name field.
func ByUserName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserName, opts...).ToFunc()
}

// ByAPIKeyName orders the results by the api_key_name field.
func ByAPIKeyName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyName, opts...).ToFunc()
}

// ByModelName orders the results by the model_name field.
func ByModelName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelName, opts...).ToFunc()
}

// ByProviderName orders the results by the provider_name field.
func ByProviderName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderName, opts...).ToFunc()
}

// ByProtocol orders the results by the protocol field.
func ByProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtocol, opts...).ToFunc()
}

// ByRequestPath orders the results by the request_path field.
func ByRequestPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestPath, opts...).ToFunc()
}

// ByMultiplierMilli orders the results by the multiplier_milli field.
func ByMultiplierMilli(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMultiplierMilli, opts...).ToFunc()
}

// ByCreditMilli orders the results by the credit_milli field.
func ByCreditMilli(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditMilli, opts...).ToFunc()
}

// ByBillingState orders the results by the billing_state field.
func ByBillingState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingState, opts...).ToFunc()
}

// ByOutcome orders the results by the outcome field.
func ByOutcome(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutcome, opts...).ToFunc()
}

// ByErrorCategory orders the results by the error_category field.
func ByErrorCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCategory, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByLeaseExpiresAt orders the results by the lease_expires_at field.
func ByLeaseExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseExpiresAt, opts...).ToFunc()
}

// BySentAt orders the results by the sent_at field.
func BySentAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSentAt, opts...).ToFunc()
}

// ByFinalizedAt orders the results by the finalized_at field.
func ByFinalizedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinalizedAt, opts...).ToFunc()
}

// ByAttemptsCount orders the results by attempts count.
func ByAttemptsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAttemptsStep(), opts...)
	}
}

// ByAttempts orders the results by attempts terms.
func ByAttempts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAttemptsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMonitoredInputField orders the results by monitored_input field.
func ByMonitoredInputField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMonitoredInputStep(), sql.OrderByField(field, opts...))
	}
}
func newAttemptsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AttemptsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AttemptsTable, AttemptsColumn),
	)
}
func newMonitoredInputStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MonitoredInputInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, MonitoredInputTable, MonitoredInputColumn),
	)
}
