// Code generated by ent, DO NOT EDIT.

package apikeyaudit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldEQ(FieldCreatedAt, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v uuid.UUID) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldEQ(FieldAPIKeyID, v))
}

// ActorUserID applies equality check predicate on the "actor_user_id" field. It's identical to ActorUserIDEQ.
func ActorUserID(v uuid.UUID) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldEQ(FieldActorUserID, v))
}

// Comment applies equality check predicate on the "comment" field. It's identical to CommentEQ.
func Comment(v string) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldEQ(FieldComment, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldLTE(FieldCreatedAt, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v uuid.UUID) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v uuid.UUID) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...uuid.UUID) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...uuid.UUID) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// ActorUserIDEQ applies the EQ predicate on the "actor_user_id" field.
func ActorUserIDEQ(v uuid.UUID) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldEQ(FieldActorUserID, v))
}

// ActorUserIDNEQ applies the NEQ predicate on the "actor_user_id" field.
func ActorUserIDNEQ(v uuid.UUID) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldNEQ(FieldActorUserID, v))
}

// ActorUserIDIn applies the In predicate on the "actor_user_id" field.
func ActorUserIDIn(vs ...uuid.UUID) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldIn(FieldActorUserID, vs...))
}

// ActorUserIDNotIn applies the NotIn predicate on the "actor_user_id" field.
func ActorUserIDNotIn(vs ...uuid.UUID) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldNotIn(FieldActorUserID, vs...))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v Action) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v Action) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...Action) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...Action) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldNotIn(FieldAction, vs...))
}

// CommentEQ applies the EQ predicate on the "comment" field.
func CommentEQ(v string) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldEQ(FieldComment, v))
}

// CommentNEQ applies the NEQ predicate on the "comment" field.
func CommentNEQ(v string) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldNEQ(FieldComment, v))
}

// CommentIn applies the In predicate on the "comment" field.
func CommentIn(vs ...string) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldIn(FieldComment, vs...))
}

// CommentNotIn applies the NotIn predicate on the "comment" field.
func CommentNotIn(vs ...string) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldNotIn(FieldComment, vs...))
}

// CommentGT applies the GT predicate on the "comment" field.
func CommentGT(v string) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldGT(FieldComment, v))
}

// CommentGTE applies the GTE predicate on the "comment" field.
func CommentGTE(v string) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldGTE(FieldComment, v))
}

// CommentLT applies the LT predicate on the "comment" field.
func CommentLT(v string) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldLT(FieldComment, v))
}

// CommentLTE applies the LTE predicate on the "comment" field.
func CommentLTE(v string) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldLTE(FieldComment, v))
}

// CommentContains applies the Contains predicate on the "comment" field.
func CommentContains(v string) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldContains(FieldComment, v))
}

// CommentHasPrefix applies the HasPrefix predicate on the "comment" field.
func CommentHasPrefix(v string) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldHasPrefix(FieldComment, v))
}

// CommentHasSuffix applies the HasSuffix predicate on the "comment" field.
func CommentHasSuffix(v string) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldHasSuffix(FieldComment, v))
}

// CommentIsNil applies the IsNil predicate on the "comment" field.
func CommentIsNil() predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldIsNull(FieldComment))
}

// CommentNotNil applies the NotNil predicate on the "comment" field.
func CommentNotNil() predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldNotNull(FieldComment))
}

// CommentEqualFold applies the EqualFold predicate on the "comment" field.
func CommentEqualFold(v string) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldEqualFold(FieldComment, v))
}

// CommentContainsFold applies the ContainsFold predicate on the "comment" field.
func CommentContainsFold(v string) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.FieldContainsFold(FieldComment, v))
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.APIKeyAudit {
	return predicate.APIKeyAudit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasActor applies the HasEdge predicate on the "actor" edge.
func HasActor() predicate.APIKeyAudit {
	return predicate.APIKeyAudit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ActorTable, ActorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActorWith applies the HasEdge predicate on the "actor" edge with a given conditions (other predicates).
func HasActorWith(preds ...predicate.User) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(func(s *sql.Selector) {
		step := newActorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.APIKeyAudit) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.APIKeyAudit) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.APIKeyAudit) predicate.APIKeyAudit {
	return predicate.APIKeyAudit(sql.NotPredicates(p))
}
