// Code generated by ent, DO NOT EDIT.

package monitoredinput

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the monitoredinput type in the database.
	Label = "monitored_input"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldCallID holds the string denoting the call_id field in the database.
	FieldCallID = "call_id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldContentBytes holds the string denoting the content_bytes field in the database.
	FieldContentBytes = "content_bytes"
	// FieldVisible holds the string denoting the visible field in the database.
	FieldVisible = "visible"
	// EdgeCall holds the string denoting the call edge name in mutations.
	EdgeCall = "call"
	// Table holds the table name of the monitoredinput in the database.
	Table = "monitored_inputs"
	// CallTable is the table that holds the call relation/edge.
	CallTable = "monitored_inputs"
	// CallInverseTable is the table name for the GatewayCall entity.
	// It exists in this package in order to avoid circular dependency with the "gatewaycall" package.
	CallInverseTable = "gateway_calls"
	// CallColumn is the table column denoting the call relation/edge.
	CallColumn = "call_id"
)

// Columns holds all SQL columns for monitoredinput fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldCallID,
	FieldProjectID,
	FieldUserID,
	FieldSource,
	FieldContent,
	FieldContentBytes,
	FieldVisible,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// ContentBytesValidator is a validator for the "content_bytes" field. It is called by the builders before save.
	ContentBytesValidator func(int64) error
	// DefaultVisible holds the default value on creation for the "visible" field.
	DefaultVisible bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the MonitoredInput queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCallID orders the results by the call_id field.
func ByCallID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCallID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByContentBytes orders the results by the content_bytes field.
func ByContentBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentBytes, opts...).ToFunc()
}

// ByVisible orders the results by the visible field.
func ByVisible(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVisible, opts...).ToFunc()
}

// ByCallField orders the results by call field.
func ByCallField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCallStep(), sql.OrderByField(field, opts...))
	}
}
func newCallStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CallInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, CallTable, CallColumn),
	)
}
