// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/apikeymonthcreditbucket"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/predicate"
)

// APIKeyMonthCreditBucketUpdate is the builder for updating APIKeyMonthCreditBucket entities.
type APIKeyMonthCreditBucketUpdate struct {
	config
	hooks    []Hook
	mutation *APIKeyMonthCreditBucketMutation
}

// Where appends a list predicates to the APIKeyMonthCreditBucketUpdate builder.
func (_u *APIKeyMonthCreditBucketUpdate) Where(ps ...predicate.APIKeyMonthCreditBucket) *APIKeyMonthCreditBucketUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIKeyMonthCreditBucketUpdate) SetUpdatedAt(v time.Time) *APIKeyMonthCreditBucketUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetQuotaMilli sets the "quota_milli" field.
func (_u *APIKeyMonthCreditBucketUpdate) SetQuotaMilli(v int64) *APIKeyMonthCreditBucketUpdate {
	_u.mutation.ResetQuotaMilli()
	_u.mutation.SetQuotaMilli(v)
	return _u
}

// SetNillableQuotaMilli sets the "quota_milli" field if the given value is not nil.
func (_u *APIKeyMonthCreditBucketUpdate) SetNillableQuotaMilli(v *int64) *APIKeyMonthCreditBucketUpdate {
	if v != nil {
		_u.SetQuotaMilli(*v)
	}
	return _u
}

// AddQuotaMilli adds value to the "quota_milli" field.
func (_u *APIKeyMonthCreditBucketUpdate) AddQuotaMilli(v int64) *APIKeyMonthCreditBucketUpdate {
	_u.mutation.AddQuotaMilli(v)
	return _u
}

// SetAllocationActive sets the "allocation_active" field.
func (_u *APIKeyMonthCreditBucketUpdate) SetAllocationActive(v bool) *APIKeyMonthCreditBucketUpdate {
	_u.mutation.SetAllocationActive(v)
	return _u
}

// SetNillableAllocationActive sets the "allocation_active" field if the given value is not nil.
func (_u *APIKeyMonthCreditBucketUpdate) SetNillableAllocationActive(v *bool) *APIKeyMonthCreditBucketUpdate {
	if v != nil {
		_u.SetAllocationActive(*v)
	}
	return _u
}

// SetChargedMilli sets the "charged_milli" field.
func (_u *APIKeyMonthCreditBucketUpdate) SetChargedMilli(v int64) *APIKeyMonthCreditBucketUpdate {
	_u.mutation.ResetChargedMilli()
	_u.mutation.SetChargedMilli(v)
	return _u
}

// SetNillableChargedMilli sets the "charged_milli" field if the given value is not nil.
func (_u *APIKeyMonthCreditBucketUpdate) SetNillableChargedMilli(v *int64) *APIKeyMonthCreditBucketUpdate {
	if v != nil {
		_u.SetChargedMilli(*v)
	}
	return _u
}

// AddChargedMilli adds value to the "charged_milli" field.
func (_u *APIKeyMonthCreditBucketUpdate) AddChargedMilli(v int64) *APIKeyMonthCreditBucketUpdate {
	_u.mutation.AddChargedMilli(v)
	return _u
}

// SetPendingMilli sets the "pending_milli" field.
func (_u *APIKeyMonthCreditBucketUpdate) SetPendingMilli(v int64) *APIKeyMonthCreditBucketUpdate {
	_u.mutation.ResetPendingMilli()
	_u.mutation.SetPendingMilli(v)
	return _u
}

// SetNillablePendingMilli sets the "pending_milli" field if the given value is not nil.
func (_u *APIKeyMonthCreditBucketUpdate) SetNillablePendingMilli(v *int64) *APIKeyMonthCreditBucketUpdate {
	if v != nil {
		_u.SetPendingMilli(*v)
	}
	return _u
}

// AddPendingMilli adds value to the "pending_milli" field.
func (_u *APIKeyMonthCreditBucketUpdate) AddPendingMilli(v int64) *APIKeyMonthCreditBucketUpdate {
	_u.mutation.AddPendingMilli(v)
	return _u
}

// Mutation returns the APIKeyMonthCreditBucketMutation object of the builder.
func (_u *APIKeyMonthCreditBucketUpdate) Mutation() *APIKeyMonthCreditBucketMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *APIKeyMonthCreditBucketUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyMonthCreditBucketUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *APIKeyMonthCreditBucketUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyMonthCreditBucketUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIKeyMonthCreditBucketUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apikeymonthcreditbucket.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeyMonthCreditBucketUpdate) check() error {
	if v, ok := _u.mutation.QuotaMilli(); ok {
		if err := apikeymonthcreditbucket.QuotaMilliValidator(v); err != nil {
			return &ValidationError{Name: "quota_milli", err: fmt.Errorf(`ent: validator failed for field "APIKeyMonthCreditBucket.quota_milli": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChargedMilli(); ok {
		if err := apikeymonthcreditbucket.ChargedMilliValidator(v); err != nil {
			return &ValidationError{Name: "charged_milli", err: fmt.Errorf(`ent: validator failed for field "APIKeyMonthCreditBucket.charged_milli": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PendingMilli(); ok {
		if err := apikeymonthcreditbucket.PendingMilliValidator(v); err != nil {
			return &ValidationError{Name: "pending_milli", err: fmt.Errorf(`ent: validator failed for field "APIKeyMonthCreditBucket.pending_milli": %w`, err)}
		}
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyMonthCreditBucket.api_key"`)
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyMonthCreditBucket.project"`)
	}
	return nil
}

func (_u *APIKeyMonthCreditBucketUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeymonthcreditbucket.Table, apikeymonthcreditbucket.Columns, sqlgraph.NewFieldSpec(apikeymonthcreditbucket.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeymonthcreditbucket.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.QuotaMilli(); ok {
		_spec.SetField(apikeymonthcreditbucket.FieldQuotaMilli, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuotaMilli(); ok {
		_spec.AddField(apikeymonthcreditbucket.FieldQuotaMilli, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AllocationActive(); ok {
		_spec.SetField(apikeymonthcreditbucket.FieldAllocationActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ChargedMilli(); ok {
		_spec.SetField(apikeymonthcreditbucket.FieldChargedMilli, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChargedMilli(); ok {
		_spec.AddField(apikeymonthcreditbucket.FieldChargedMilli, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PendingMilli(); ok {
		_spec.SetField(apikeymonthcreditbucket.FieldPendingMilli, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPendingMilli(); ok {
		_spec.AddField(apikeymonthcreditbucket.FieldPendingMilli, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeymonthcreditbucket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// APIKeyMonthCreditBucketUpdateOne is the builder for updating a single APIKeyMonthCreditBucket entity.
type APIKeyMonthCreditBucketUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *APIKeyMonthCreditBucketMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIKeyMonthCreditBucketUpdateOne) SetUpdatedAt(v time.Time) *APIKeyMonthCreditBucketUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetQuotaMilli sets the "quota_milli" field.
func (_u *APIKeyMonthCreditBucketUpdateOne) SetQuotaMilli(v int64) *APIKeyMonthCreditBucketUpdateOne {
	_u.mutation.ResetQuotaMilli()
	_u.mutation.SetQuotaMilli(v)
	return _u
}

// SetNillableQuotaMilli sets the "quota_milli" field if the given value is not nil.
func (_u *APIKeyMonthCreditBucketUpdateOne) SetNillableQuotaMilli(v *int64) *APIKeyMonthCreditBucketUpdateOne {
	if v != nil {
		_u.SetQuotaMilli(*v)
	}
	return _u
}

// AddQuotaMilli adds value to the "quota_milli" field.
func (_u *APIKeyMonthCreditBucketUpdateOne) AddQuotaMilli(v int64) *APIKeyMonthCreditBucketUpdateOne {
	_u.mutation.AddQuotaMilli(v)
	return _u
}

// SetAllocationActive sets the "allocation_active" field.
func (_u *APIKeyMonthCreditBucketUpdateOne) SetAllocationActive(v bool) *APIKeyMonthCreditBucketUpdateOne {
	_u.mutation.SetAllocationActive(v)
	return _u
}

// SetNillableAllocationActive sets the "allocation_active" field if the given value is not nil.
func (_u *APIKeyMonthCreditBucketUpdateOne) SetNillableAllocationActive(v *bool) *APIKeyMonthCreditBucketUpdateOne {
	if v != nil {
		_u.SetAllocationActive(*v)
	}
	return _u
}

// SetChargedMilli sets the "charged_milli" field.
func (_u *APIKeyMonthCreditBucketUpdateOne) SetChargedMilli(v int64) *APIKeyMonthCreditBucketUpdateOne {
	_u.mutation.ResetChargedMilli()
	_u.mutation.SetChargedMilli(v)
	return _u
}

// SetNillableChargedMilli sets the "charged_milli" field if the given value is not nil.
func (_u *APIKeyMonthCreditBucketUpdateOne) SetNillableChargedMilli(v *int64) *APIKeyMonthCreditBucketUpdateOne {
	if v != nil {
		_u.SetChargedMilli(*v)
	}
	return _u
}

// AddChargedMilli adds value to the "charged_milli" field.
func (_u *APIKeyMonthCreditBucketUpdateOne) AddChargedMilli(v int64) *APIKeyMonthCreditBucketUpdateOne {
	_u.mutation.AddChargedMilli(v)
	return _u
}

// SetPendingMilli sets the "pending_milli" field.
func (_u *APIKeyMonthCreditBucketUpdateOne) SetPendingMilli(v int64) *APIKeyMonthCreditBucketUpdateOne {
	_u.mutation.ResetPendingMilli()
	_u.mutation.SetPendingMilli(v)
	return _u
}

// SetNillablePendingMilli sets the "pending_milli" field if the given value is not nil.
func (_u *APIKeyMonthCreditBucketUpdateOne) SetNillablePendingMilli(v *int64) *APIKeyMonthCreditBucketUpdateOne {
	if v != nil {
		_u.SetPendingMilli(*v)
	}
	return _u
}

// AddPendingMilli adds value to the "pending_milli" field.
func (_u *APIKeyMonthCreditBucketUpdateOne) AddPendingMilli(v int64) *APIKeyMonthCreditBucketUpdateOne {
	_u.mutation.AddPendingMilli(v)
	return _u
}

// Mutation returns the APIKeyMonthCreditBucketMutation object of the builder.
func (_u *APIKeyMonthCreditBucketUpdateOne) Mutation() *APIKeyMonthCreditBucketMutation {
	return _u.mutation
}

// Where appends a list predicates to the APIKeyMonthCreditBucketUpdate builder.
func (_u *APIKeyMonthCreditBucketUpdateOne) Where(ps ...predicate.APIKeyMonthCreditBucket) *APIKeyMonthCreditBucketUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *APIKeyMonthCreditBucketUpdateOne) Select(field string, fields ...string) *APIKeyMonthCreditBucketUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated APIKeyMonthCreditBucket entity.
func (_u *APIKeyMonthCreditBucketUpdateOne) Save(ctx context.Context) (*APIKeyMonthCreditBucket, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyMonthCreditBucketUpdateOne) SaveX(ctx context.Context) *APIKeyMonthCreditBucket {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *APIKeyMonthCreditBucketUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyMonthCreditBucketUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIKeyMonthCreditBucketUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apikeymonthcreditbucket.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeyMonthCreditBucketUpdateOne) check() error {
	if v, ok := _u.mutation.QuotaMilli(); ok {
		if err := apikeymonthcreditbucket.QuotaMilliValidator(v); err != nil {
			return &ValidationError{Name: "quota_milli", err: fmt.Errorf(`ent: validator failed for field "APIKeyMonthCreditBucket.quota_milli": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChargedMilli(); ok {
		if err := apikeymonthcreditbucket.ChargedMilliValidator(v); err != nil {
			return &ValidationError{Name: "charged_milli", err: fmt.Errorf(`ent: validator failed for field "APIKeyMonthCreditBucket.charged_milli": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PendingMilli(); ok {
		if err := apikeymonthcreditbucket.PendingMilliValidator(v); err != nil {
			return &ValidationError{Name: "pending_milli", err: fmt.Errorf(`ent: validator failed for field "APIKeyMonthCreditBucket.pending_milli": %w`, err)}
		}
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyMonthCreditBucket.api_key"`)
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyMonthCreditBucket.project"`)
	}
	return nil
}

func (_u *APIKeyMonthCreditBucketUpdateOne) sqlSave(ctx context.Context) (_node *APIKeyMonthCreditBucket, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeymonthcreditbucket.Table, apikeymonthcreditbucket.Columns, sqlgraph.NewFieldSpec(apikeymonthcreditbucket.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "APIKeyMonthCreditBucket.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apikeymonthcreditbucket.FieldID)
		for _, f := range fields {
			if !apikeymonthcreditbucket.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apikeymonthcreditbucket.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeymonthcreditbucket.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.QuotaMilli(); ok {
		_spec.SetField(apikeymonthcreditbucket.FieldQuotaMilli, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuotaMilli(); ok {
		_spec.AddField(apikeymonthcreditbucket.FieldQuotaMilli, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AllocationActive(); ok {
		_spec.SetField(apikeymonthcreditbucket.FieldAllocationActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ChargedMilli(); ok {
		_spec.SetField(apikeymonthcreditbucket.FieldChargedMilli, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChargedMilli(); ok {
		_spec.AddField(apikeymonthcreditbucket.FieldChargedMilli, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PendingMilli(); ok {
		_spec.SetField(apikeymonthcreditbucket.FieldPendingMilli, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPendingMilli(); ok {
		_spec.AddField(apikeymonthcreditbucket.FieldPendingMilli, field.TypeInt64, value)
	}
	_node = &APIKeyMonthCreditBucket{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeymonthcreditbucket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
