// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/gatewaycall"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/monitoredinput"
)

// GatewayCall is the model entity for the GatewayCall schema.
type GatewayCall struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// Month holds the value of the "month" field.
	Month time.Time `json:"month,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID uuid.UUID `json:"organization_id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID uuid.UUID `json:"project_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID uuid.UUID `json:"api_key_id,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID uuid.UUID `json:"model_id,omitempty"`
	// ProviderID holds the value of the "provider_id" field.
	ProviderID *uuid.UUID `json:"provider_id,omitempty"`
	// OrganizationName holds the value of the "organization_name" field.
	OrganizationName string `json:"organization_name,omitempty"`
	// ProjectName holds the value of the "project_name" field.
	ProjectName string `json:"project_name,omitempty"`
	// UserName holds the value of the "user_name" field.
	UserName string `json:"user_name,omitempty"`
	// APIKeyName holds the value of the "api_key_name" field.
	APIKeyName string `json:"api_key_name,omitempty"`
	// ModelName holds the value of the "model_name" field.
	ModelName string `json:"model_name,omitempty"`
	// ProviderName holds the value of the "provider_name" field.
	ProviderName *string `json:"provider_name,omitempty"`
	// Protocol holds the value of the "protocol" field.
	Protocol string `json:"protocol,omitempty"`
	// RequestPath holds the value of the "request_path" field.
	RequestPath string `json:"request_path,omitempty"`
	// MultiplierMilli holds the value of the "multiplier_milli" field.
	MultiplierMilli int64 `json:"multiplier_milli,omitempty"`
	// CreditMilli holds the value of the "credit_milli" field.
	CreditMilli int64 `json:"credit_milli,omitempty"`
	// BillingState holds the value of the "billing_state" field.
	BillingState gatewaycall.BillingState `json:"billing_state,omitempty"`
	// Outcome holds the value of the "outcome" field.
	Outcome gatewaycall.Outcome `json:"outcome,omitempty"`
	// ErrorCategory holds the value of the "error_category" field.
	ErrorCategory *string `json:"error_category,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// LeaseExpiresAt holds the value of the "lease_expires_at" field.
	LeaseExpiresAt *time.Time `json:"lease_expires_at,omitempty"`
	// SentAt holds the value of the "sent_at" field.
	SentAt *time.Time `json:"sent_at,omitempty"`
	// FinalizedAt holds the value of the "finalized_at" field.
	FinalizedAt *time.Time `json:"finalized_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GatewayCallQuery when eager-loading is set.
	Edges        GatewayCallEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GatewayCallEdges holds the relations/edges for other nodes in the graph.
type GatewayCallEdges struct {
	// Attempts holds the value of the attempts edge.
	Attempts []*GatewayCallAttempt `json:"attempts,omitempty"`
	// MonitoredInput holds the value of the monitored_input edge.
	MonitoredInput *MonitoredInput `json:"monitored_input,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AttemptsOrErr returns the Attempts value or an error if the edge
// was not loaded in eager-loading.
func (e GatewayCallEdges) AttemptsOrErr() ([]*GatewayCallAttempt, error) {
	if e.loadedTypes[0] {
		return e.Attempts, nil
	}
	return nil, &NotLoadedError{edge: "attempts"}
}

// MonitoredInputOrErr returns the MonitoredInput value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GatewayCallEdges) MonitoredInputOrErr() (*MonitoredInput, error) {
	if e.MonitoredInput != nil {
		return e.MonitoredInput, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: monitoredinput.Label}
	}
	return nil, &NotLoadedError{edge: "monitored_input"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GatewayCall) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gatewaycall.FieldProviderID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case gatewaycall.FieldMultiplierMilli, gatewaycall.FieldCreditMilli:
			values[i] = new(sql.NullInt64)
		case gatewaycall.FieldRequestID, gatewaycall.FieldOrganizationName, gatewaycall.FieldProjectName, gatewaycall.FieldUserName, gatewaycall.FieldAPIKeyName, gatewaycall.FieldModelName, gatewaycall.FieldProviderName, gatewaycall.FieldProtocol, gatewaycall.FieldRequestPath, gatewaycall.FieldBillingState, gatewaycall.FieldOutcome, gatewaycall.FieldErrorCategory, gatewaycall.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case gatewaycall.FieldCreatedAt, gatewaycall.FieldMonth, gatewaycall.FieldLeaseExpiresAt, gatewaycall.FieldSentAt, gatewaycall.FieldFinalizedAt:
			values[i] = new(sql.NullTime)
		case gatewaycall.FieldID, gatewaycall.FieldOrganizationID, gatewaycall.FieldProjectID, gatewaycall.FieldUserID, gatewaycall.FieldAPIKeyID, gatewaycall.FieldModelID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GatewayCall fields.
func (_m *GatewayCall) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gatewaycall.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case gatewaycall.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case gatewaycall.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case gatewaycall.FieldMonth:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field month", values[i])
			} else if value.Valid {
				_m.Month = value.Time
			}
		case gatewaycall.FieldOrganizationID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value != nil {
				_m.OrganizationID = *value
			}
		case gatewaycall.FieldProjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value != nil {
				_m.ProjectID = *value
			}
		case gatewaycall.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case gatewaycall.FieldAPIKeyID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value != nil {
				_m.APIKeyID = *value
			}
		case gatewaycall.FieldModelID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value != nil {
				_m.ModelID = *value
			}
		case gatewaycall.FieldProviderID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value.Valid {
				_m.ProviderID = new(uuid.UUID)
				*_m.ProviderID = *value.S.(*uuid.UUID)
			}
		case gatewaycall.FieldOrganizationName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field organization_name", values[i])
			} else if value.Valid {
				_m.OrganizationName = value.String
			}
		case gatewaycall.FieldProjectName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project_name", values[i])
			} else if value.Valid {
				_m.ProjectName = value.String
			}
		case gatewaycall.FieldUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_name", values[i])
			} else if value.Valid {
				_m.UserName = value.String
			}
		case gatewaycall.FieldAPIKeyName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_name", values[i])
			} else if value.Valid {
				_m.APIKeyName = value.String
			}
		case gatewaycall.FieldModelName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_name", values[i])
			} else if value.Valid {
				_m.ModelName = value.String
			}
		case gatewaycall.FieldProviderName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_name", values[i])
			} else if value.Valid {
				_m.ProviderName = new(string)
				*_m.ProviderName = value.String
			}
		case gatewaycall.FieldProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field protocol", values[i])
			} else if value.Valid {
				_m.Protocol = value.String
			}
		case gatewaycall.FieldRequestPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_path", values[i])
			} else if value.Valid {
				_m.RequestPath = value.String
			}
		case gatewaycall.FieldMultiplierMilli:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field multiplier_milli", values[i])
			} else if value.Valid {
				_m.MultiplierMilli = value.Int64
			}
		case gatewaycall.FieldCreditMilli:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field credit_milli", values[i])
			} else if value.Valid {
				_m.CreditMilli = value.Int64
			}
		case gatewaycall.FieldBillingState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_state", values[i])
			} else if value.Valid {
				_m.BillingState = gatewaycall.BillingState(value.String)
			}
		case gatewaycall.FieldOutcome:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field outcome", values[i])
			} else if value.Valid {
				_m.Outcome = gatewaycall.Outcome(value.String)
			}
		case gatewaycall.FieldErrorCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_category", values[i])
			} else if value.Valid {
				_m.ErrorCategory = new(string)
				*_m.ErrorCategory = value.String
			}
		case gatewaycall.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case gatewaycall.FieldLeaseExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field lease_expires_at", values[i])
			} else if value.Valid {
				_m.LeaseExpiresAt = new(time.Time)
				*_m.LeaseExpiresAt = value.Time
			}
		case gatewaycall.FieldSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sent_at", values[i])
			} else if value.Valid {
				_m.SentAt = new(time.Time)
				*_m.SentAt = value.Time
			}
		case gatewaycall.FieldFinalizedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finalized_at", values[i])
			} else if value.Valid {
				_m.FinalizedAt = new(time.Time)
				*_m.FinalizedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GatewayCall.
// This includes values selected through modifiers, order, etc.
func (_m *GatewayCall) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAttempts queries the "attempts" edge of the GatewayCall entity.
func (_m *GatewayCall) QueryAttempts() *GatewayCallAttemptQuery {
	return NewGatewayCallClient(_m.config).QueryAttempts(_m)
}

// QueryMonitoredInput queries the "monitored_input" edge of the GatewayCall entity.
func (_m *GatewayCall) QueryMonitoredInput() *MonitoredInputQuery {
	return NewGatewayCallClient(_m.config).QueryMonitoredInput(_m)
}

// Update returns a builder for updating this GatewayCall.
// Note that you need to call GatewayCall.Unwrap() before calling this method if this GatewayCall
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GatewayCall) Update() *GatewayCallUpdateOne {
	return NewGatewayCallClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GatewayCall entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GatewayCall) Unwrap() *GatewayCall {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GatewayCall is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GatewayCall) String() string {
	var builder strings.Builder
	builder.WriteString("GatewayCall(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("month=")
	builder.WriteString(_m.Month.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("organization_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrganizationID))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelID))
	builder.WriteString(", ")
	if v := _m.ProviderID; v != nil {
		builder.WriteString("provider_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("organization_name=")
	builder.WriteString(_m.OrganizationName)
	builder.WriteString(", ")
	builder.WriteString("project_name=")
	builder.WriteString(_m.ProjectName)
	builder.WriteString(", ")
	builder.WriteString("user_name=")
	builder.WriteString(_m.UserName)
	builder.WriteString(", ")
	builder.WriteString("api_key_name=")
	builder.WriteString(_m.APIKeyName)
	builder.WriteString(", ")
	builder.WriteString("model_name=")
	builder.WriteString(_m.ModelName)
	builder.WriteString(", ")
	if v := _m.ProviderName; v != nil {
		builder.WriteString("provider_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("protocol=")
	builder.WriteString(_m.Protocol)
	builder.WriteString(", ")
	builder.WriteString("request_path=")
	builder.WriteString(_m.RequestPath)
	builder.WriteString(", ")
	builder.WriteString("multiplier_milli=")
	builder.WriteString(fmt.Sprintf("%v", _m.MultiplierMilli))
	builder.WriteString(", ")
	builder.WriteString("credit_milli=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditMilli))
	builder.WriteString(", ")
	builder.WriteString("billing_state=")
	builder.WriteString(fmt.Sprintf("%v", _m.BillingState))
	builder.WriteString(", ")
	builder.WriteString("outcome=")
	builder.WriteString(fmt.Sprintf("%v", _m.Outcome))
	builder.WriteString(", ")
	if v := _m.ErrorCategory; v != nil {
		builder.WriteString("error_category=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LeaseExpiresAt; v != nil {
		builder.WriteString("lease_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SentAt; v != nil {
		builder.WriteString("sent_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FinalizedAt; v != nil {
		builder.WriteString("finalized_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// GatewayCalls is a parsable slice of GatewayCall.
type GatewayCalls []*GatewayCall
