// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/gatewaycallattempt"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/predicate"
)

// GatewayCallAttemptDelete is the builder for deleting a GatewayCallAttempt entity.
type GatewayCallAttemptDelete struct {
	config
	hooks    []Hook
	mutation *GatewayCallAttemptMutation
}

// Where appends a list predicates to the GatewayCallAttemptDelete builder.
func (_d *GatewayCallAttemptDelete) Where(ps ...predicate.GatewayCallAttempt) *GatewayCallAttemptDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GatewayCallAttemptDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GatewayCallAttemptDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GatewayCallAttemptDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(gatewaycallattempt.Table, sqlgraph.NewFieldSpec(gatewaycallattempt.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GatewayCallAttemptDeleteOne is the builder for deleting a single GatewayCallAttempt entity.
type GatewayCallAttemptDeleteOne struct {
	_d *GatewayCallAttemptDelete
}

// Where appends a list predicates to the GatewayCallAttemptDelete builder.
func (_d *GatewayCallAttemptDeleteOne) Where(ps ...predicate.GatewayCallAttempt) *GatewayCallAttemptDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GatewayCallAttemptDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{gatewaycallattempt.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GatewayCallAttemptDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
