// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/matrixmodelcatalog"
)

// MatrixModelCatalogCreate is the builder for creating a MatrixModelCatalog entity.
type MatrixModelCatalogCreate struct {
	config
	mutation *MatrixModelCatalogMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *MatrixModelCatalogCreate) SetCreatedAt(v time.Time) *MatrixModelCatalogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MatrixModelCatalogCreate) SetNillableCreatedAt(v *time.Time) *MatrixModelCatalogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MatrixModelCatalogCreate) SetUpdatedAt(v time.Time) *MatrixModelCatalogCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MatrixModelCatalogCreate) SetNillableUpdatedAt(v *time.Time) *MatrixModelCatalogCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetModelID sets the "model_id" field.
func (_c *MatrixModelCatalogCreate) SetModelID(v string) *MatrixModelCatalogCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *MatrixModelCatalogCreate) SetDescription(v string) *MatrixModelCatalogCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *MatrixModelCatalogCreate) SetNillableDescription(v *string) *MatrixModelCatalogCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetOwnedBy sets the "owned_by" field.
func (_c *MatrixModelCatalogCreate) SetOwnedBy(v []string) *MatrixModelCatalogCreate {
	_c.mutation.SetOwnedBy(v)
	return _c
}

// SetModelTypes sets the "model_types" field.
func (_c *MatrixModelCatalogCreate) SetModelTypes(v []string) *MatrixModelCatalogCreate {
	_c.mutation.SetModelTypes(v)
	return _c
}

// SetSupportedEndpointTypes sets the "supported_endpoint_types" field.
func (_c *MatrixModelCatalogCreate) SetSupportedEndpointTypes(v []string) *MatrixModelCatalogCreate {
	_c.mutation.SetSupportedEndpointTypes(v)
	return _c
}

// SetTags sets the "tags" field.
func (_c *MatrixModelCatalogCreate) SetTags(v []string) *MatrixModelCatalogCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetRawEntries sets the "raw_entries" field.
func (_c *MatrixModelCatalogCreate) SetRawEntries(v []map[string]interface{}) *MatrixModelCatalogCreate {
	_c.mutation.SetRawEntries(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *MatrixModelCatalogCreate) SetStatus(v matrixmodelcatalog.Status) *MatrixModelCatalogCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MatrixModelCatalogCreate) SetNillableStatus(v *matrixmodelcatalog.Status) *MatrixModelCatalogCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *MatrixModelCatalogCreate) SetLastSeenAt(v time.Time) *MatrixModelCatalogCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetSyncedAt sets the "synced_at" field.
func (_c *MatrixModelCatalogCreate) SetSyncedAt(v time.Time) *MatrixModelCatalogCreate {
	_c.mutation.SetSyncedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *MatrixModelCatalogCreate) SetID(v uuid.UUID) *MatrixModelCatalogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MatrixModelCatalogCreate) SetNillableID(v *uuid.UUID) *MatrixModelCatalogCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the MatrixModelCatalogMutation object of the builder.
func (_c *MatrixModelCatalogCreate) Mutation() *MatrixModelCatalogMutation {
	return _c.mutation
}

// Save creates the MatrixModelCatalog in the database.
func (_c *MatrixModelCatalogCreate) Save(ctx context.Context) (*MatrixModelCatalog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MatrixModelCatalogCreate) SaveX(ctx context.Context) *MatrixModelCatalog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MatrixModelCatalogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MatrixModelCatalogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MatrixModelCatalogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := matrixmodelcatalog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := matrixmodelcatalog.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.OwnedBy(); !ok {
		v := matrixmodelcatalog.DefaultOwnedBy
		_c.mutation.SetOwnedBy(v)
	}
	if _, ok := _c.mutation.ModelTypes(); !ok {
		v := matrixmodelcatalog.DefaultModelTypes
		_c.mutation.SetModelTypes(v)
	}
	if _, ok := _c.mutation.SupportedEndpointTypes(); !ok {
		v := matrixmodelcatalog.DefaultSupportedEndpointTypes
		_c.mutation.SetSupportedEndpointTypes(v)
	}
	if _, ok := _c.mutation.Tags(); !ok {
		v := matrixmodelcatalog.DefaultTags
		_c.mutation.SetTags(v)
	}
	if _, ok := _c.mutation.RawEntries(); !ok {
		v := matrixmodelcatalog.DefaultRawEntries
		_c.mutation.SetRawEntries(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := matrixmodelcatalog.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := matrixmodelcatalog.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MatrixModelCatalogCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MatrixModelCatalog.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MatrixModelCatalog.updated_at"`)}
	}
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "MatrixModelCatalog.model_id"`)}
	}
	if v, ok := _c.mutation.ModelID(); ok {
		if err := matrixmodelcatalog.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "MatrixModelCatalog.model_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := matrixmodelcatalog.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "MatrixModelCatalog.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OwnedBy(); !ok {
		return &ValidationError{Name: "owned_by", err: errors.New(`ent: missing required field "MatrixModelCatalog.owned_by"`)}
	}
	if _, ok := _c.mutation.ModelTypes(); !ok {
		return &ValidationError{Name: "model_types", err: errors.New(`ent: missing required field "MatrixModelCatalog.model_types"`)}
	}
	if _, ok := _c.mutation.SupportedEndpointTypes(); !ok {
		return &ValidationError{Name: "supported_endpoint_types", err: errors.New(`ent: missing required field "MatrixModelCatalog.supported_endpoint_types"`)}
	}
	if _, ok := _c.mutation.Tags(); !ok {
		return &ValidationError{Name: "tags", err: errors.New(`ent: missing required field "MatrixModelCatalog.tags"`)}
	}
	if _, ok := _c.mutation.RawEntries(); !ok {
		return &ValidationError{Name: "raw_entries", err: errors.New(`ent: missing required field "MatrixModelCatalog.raw_entries"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MatrixModelCatalog.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := matrixmodelcatalog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MatrixModelCatalog.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "MatrixModelCatalog.last_seen_at"`)}
	}
	if _, ok := _c.mutation.SyncedAt(); !ok {
		return &ValidationError{Name: "synced_at", err: errors.New(`ent: missing required field "MatrixModelCatalog.synced_at"`)}
	}
	return nil
}

func (_c *MatrixModelCatalogCreate) sqlSave(ctx context.Context) (*MatrixModelCatalog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MatrixModelCatalogCreate) createSpec() (*MatrixModelCatalog, *sqlgraph.CreateSpec) {
	var (
		_node = &MatrixModelCatalog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(matrixmodelcatalog.Table, sqlgraph.NewFieldSpec(matrixmodelcatalog.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(matrixmodelcatalog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(matrixmodelcatalog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(matrixmodelcatalog.FieldModelID, field.TypeString, value)
		_node.ModelID = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(matrixmodelcatalog.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.OwnedBy(); ok {
		_spec.SetField(matrixmodelcatalog.FieldOwnedBy, field.TypeJSON, value)
		_node.OwnedBy = value
	}
	if value, ok := _c.mutation.ModelTypes(); ok {
		_spec.SetField(matrixmodelcatalog.FieldModelTypes, field.TypeJSON, value)
		_node.ModelTypes = value
	}
	if value, ok := _c.mutation.SupportedEndpointTypes(); ok {
		_spec.SetField(matrixmodelcatalog.FieldSupportedEndpointTypes, field.TypeJSON, value)
		_node.SupportedEndpointTypes = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(matrixmodelcatalog.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.RawEntries(); ok {
		_spec.SetField(matrixmodelcatalog.FieldRawEntries, field.TypeJSON, value)
		_node.RawEntries = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(matrixmodelcatalog.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(matrixmodelcatalog.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	if value, ok := _c.mutation.SyncedAt(); ok {
		_spec.SetField(matrixmodelcatalog.FieldSyncedAt, field.TypeTime, value)
		_node.SyncedAt = value
	}
	return _node, _spec
}

// MatrixModelCatalogCreateBulk is the builder for creating many MatrixModelCatalog entities in bulk.
type MatrixModelCatalogCreateBulk struct {
	config
	err      error
	builders []*MatrixModelCatalogCreate
}

// Save creates the MatrixModelCatalog entities in the database.
func (_c *MatrixModelCatalogCreateBulk) Save(ctx context.Context) ([]*MatrixModelCatalog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MatrixModelCatalog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MatrixModelCatalogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MatrixModelCatalogCreateBulk) SaveX(ctx context.Context) []*MatrixModelCatalog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MatrixModelCatalogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MatrixModelCatalogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
