// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/matrixmodelcatalog"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/predicate"
)

// MatrixModelCatalogUpdate is the builder for updating MatrixModelCatalog entities.
type MatrixModelCatalogUpdate struct {
	config
	hooks    []Hook
	mutation *MatrixModelCatalogMutation
}

// Where appends a list predicates to the MatrixModelCatalogUpdate builder.
func (_u *MatrixModelCatalogUpdate) Where(ps ...predicate.MatrixModelCatalog) *MatrixModelCatalogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MatrixModelCatalogUpdate) SetUpdatedAt(v time.Time) *MatrixModelCatalogUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *MatrixModelCatalogUpdate) SetModelID(v string) *MatrixModelCatalogUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *MatrixModelCatalogUpdate) SetNillableModelID(v *string) *MatrixModelCatalogUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *MatrixModelCatalogUpdate) SetDescription(v string) *MatrixModelCatalogUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *MatrixModelCatalogUpdate) SetNillableDescription(v *string) *MatrixModelCatalogUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *MatrixModelCatalogUpdate) ClearDescription() *MatrixModelCatalogUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetOwnedBy sets the "owned_by" field.
func (_u *MatrixModelCatalogUpdate) SetOwnedBy(v []string) *MatrixModelCatalogUpdate {
	_u.mutation.SetOwnedBy(v)
	return _u
}

// AppendOwnedBy appends value to the "owned_by" field.
func (_u *MatrixModelCatalogUpdate) AppendOwnedBy(v []string) *MatrixModelCatalogUpdate {
	_u.mutation.AppendOwnedBy(v)
	return _u
}

// SetModelTypes sets the "model_types" field.
func (_u *MatrixModelCatalogUpdate) SetModelTypes(v []string) *MatrixModelCatalogUpdate {
	_u.mutation.SetModelTypes(v)
	return _u
}

// AppendModelTypes appends value to the "model_types" field.
func (_u *MatrixModelCatalogUpdate) AppendModelTypes(v []string) *MatrixModelCatalogUpdate {
	_u.mutation.AppendModelTypes(v)
	return _u
}

// SetSupportedEndpointTypes sets the "supported_endpoint_types" field.
func (_u *MatrixModelCatalogUpdate) SetSupportedEndpointTypes(v []string) *MatrixModelCatalogUpdate {
	_u.mutation.SetSupportedEndpointTypes(v)
	return _u
}

// AppendSupportedEndpointTypes appends value to the "supported_endpoint_types" field.
func (_u *MatrixModelCatalogUpdate) AppendSupportedEndpointTypes(v []string) *MatrixModelCatalogUpdate {
	_u.mutation.AppendSupportedEndpointTypes(v)
	return _u
}

// SetTags sets the "tags" field.
func (_u *MatrixModelCatalogUpdate) SetTags(v []string) *MatrixModelCatalogUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *MatrixModelCatalogUpdate) AppendTags(v []string) *MatrixModelCatalogUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// SetRawEntries sets the "raw_entries" field.
func (_u *MatrixModelCatalogUpdate) SetRawEntries(v []map[string]interface{}) *MatrixModelCatalogUpdate {
	_u.mutation.SetRawEntries(v)
	return _u
}

// AppendRawEntries appends value to the "raw_entries" field.
func (_u *MatrixModelCatalogUpdate) AppendRawEntries(v []map[string]interface{}) *MatrixModelCatalogUpdate {
	_u.mutation.AppendRawEntries(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *MatrixModelCatalogUpdate) SetStatus(v matrixmodelcatalog.Status) *MatrixModelCatalogUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MatrixModelCatalogUpdate) SetNillableStatus(v *matrixmodelcatalog.Status) *MatrixModelCatalogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *MatrixModelCatalogUpdate) SetLastSeenAt(v time.Time) *MatrixModelCatalogUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *MatrixModelCatalogUpdate) SetNillableLastSeenAt(v *time.Time) *MatrixModelCatalogUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *MatrixModelCatalogUpdate) SetSyncedAt(v time.Time) *MatrixModelCatalogUpdate {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *MatrixModelCatalogUpdate) SetNillableSyncedAt(v *time.Time) *MatrixModelCatalogUpdate {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// Mutation returns the MatrixModelCatalogMutation object of the builder.
func (_u *MatrixModelCatalogUpdate) Mutation() *MatrixModelCatalogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MatrixModelCatalogUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MatrixModelCatalogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MatrixModelCatalogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MatrixModelCatalogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MatrixModelCatalogUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := matrixmodelcatalog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MatrixModelCatalogUpdate) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := matrixmodelcatalog.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "MatrixModelCatalog.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := matrixmodelcatalog.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "MatrixModelCatalog.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := matrixmodelcatalog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MatrixModelCatalog.status": %w`, err)}
		}
	}
	return nil
}

func (_u *MatrixModelCatalogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(matrixmodelcatalog.Table, matrixmodelcatalog.Columns, sqlgraph.NewFieldSpec(matrixmodelcatalog.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(matrixmodelcatalog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(matrixmodelcatalog.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(matrixmodelcatalog.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(matrixmodelcatalog.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.OwnedBy(); ok {
		_spec.SetField(matrixmodelcatalog.FieldOwnedBy, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOwnedBy(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, matrixmodelcatalog.FieldOwnedBy, value)
		})
	}
	if value, ok := _u.mutation.ModelTypes(); ok {
		_spec.SetField(matrixmodelcatalog.FieldModelTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedModelTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, matrixmodelcatalog.FieldModelTypes, value)
		})
	}
	if value, ok := _u.mutation.SupportedEndpointTypes(); ok {
		_spec.SetField(matrixmodelcatalog.FieldSupportedEndpointTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSupportedEndpointTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, matrixmodelcatalog.FieldSupportedEndpointTypes, value)
		})
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(matrixmodelcatalog.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, matrixmodelcatalog.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.RawEntries(); ok {
		_spec.SetField(matrixmodelcatalog.FieldRawEntries, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRawEntries(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, matrixmodelcatalog.FieldRawEntries, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(matrixmodelcatalog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(matrixmodelcatalog.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(matrixmodelcatalog.FieldSyncedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{matrixmodelcatalog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MatrixModelCatalogUpdateOne is the builder for updating a single MatrixModelCatalog entity.
type MatrixModelCatalogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MatrixModelCatalogMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MatrixModelCatalogUpdateOne) SetUpdatedAt(v time.Time) *MatrixModelCatalogUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *MatrixModelCatalogUpdateOne) SetModelID(v string) *MatrixModelCatalogUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *MatrixModelCatalogUpdateOne) SetNillableModelID(v *string) *MatrixModelCatalogUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *MatrixModelCatalogUpdateOne) SetDescription(v string) *MatrixModelCatalogUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *MatrixModelCatalogUpdateOne) SetNillableDescription(v *string) *MatrixModelCatalogUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *MatrixModelCatalogUpdateOne) ClearDescription() *MatrixModelCatalogUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetOwnedBy sets the "owned_by" field.
func (_u *MatrixModelCatalogUpdateOne) SetOwnedBy(v []string) *MatrixModelCatalogUpdateOne {
	_u.mutation.SetOwnedBy(v)
	return _u
}

// AppendOwnedBy appends value to the "owned_by" field.
func (_u *MatrixModelCatalogUpdateOne) AppendOwnedBy(v []string) *MatrixModelCatalogUpdateOne {
	_u.mutation.AppendOwnedBy(v)
	return _u
}

// SetModelTypes sets the "model_types" field.
func (_u *MatrixModelCatalogUpdateOne) SetModelTypes(v []string) *MatrixModelCatalogUpdateOne {
	_u.mutation.SetModelTypes(v)
	return _u
}

// AppendModelTypes appends value to the "model_types" field.
func (_u *MatrixModelCatalogUpdateOne) AppendModelTypes(v []string) *MatrixModelCatalogUpdateOne {
	_u.mutation.AppendModelTypes(v)
	return _u
}

// SetSupportedEndpointTypes sets the "supported_endpoint_types" field.
func (_u *MatrixModelCatalogUpdateOne) SetSupportedEndpointTypes(v []string) *MatrixModelCatalogUpdateOne {
	_u.mutation.SetSupportedEndpointTypes(v)
	return _u
}

// AppendSupportedEndpointTypes appends value to the "supported_endpoint_types" field.
func (_u *MatrixModelCatalogUpdateOne) AppendSupportedEndpointTypes(v []string) *MatrixModelCatalogUpdateOne {
	_u.mutation.AppendSupportedEndpointTypes(v)
	return _u
}

// SetTags sets the "tags" field.
func (_u *MatrixModelCatalogUpdateOne) SetTags(v []string) *MatrixModelCatalogUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *MatrixModelCatalogUpdateOne) AppendTags(v []string) *MatrixModelCatalogUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// SetRawEntries sets the "raw_entries" field.
func (_u *MatrixModelCatalogUpdateOne) SetRawEntries(v []map[string]interface{}) *MatrixModelCatalogUpdateOne {
	_u.mutation.SetRawEntries(v)
	return _u
}

// AppendRawEntries appends value to the "raw_entries" field.
func (_u *MatrixModelCatalogUpdateOne) AppendRawEntries(v []map[string]interface{}) *MatrixModelCatalogUpdateOne {
	_u.mutation.AppendRawEntries(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *MatrixModelCatalogUpdateOne) SetStatus(v matrixmodelcatalog.Status) *MatrixModelCatalogUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MatrixModelCatalogUpdateOne) SetNillableStatus(v *matrixmodelcatalog.Status) *MatrixModelCatalogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *MatrixModelCatalogUpdateOne) SetLastSeenAt(v time.Time) *MatrixModelCatalogUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *MatrixModelCatalogUpdateOne) SetNillableLastSeenAt(v *time.Time) *MatrixModelCatalogUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *MatrixModelCatalogUpdateOne) SetSyncedAt(v time.Time) *MatrixModelCatalogUpdateOne {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *MatrixModelCatalogUpdateOne) SetNillableSyncedAt(v *time.Time) *MatrixModelCatalogUpdateOne {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// Mutation returns the MatrixModelCatalogMutation object of the builder.
func (_u *MatrixModelCatalogUpdateOne) Mutation() *MatrixModelCatalogMutation {
	return _u.mutation
}

// Where appends a list predicates to the MatrixModelCatalogUpdate builder.
func (_u *MatrixModelCatalogUpdateOne) Where(ps ...predicate.MatrixModelCatalog) *MatrixModelCatalogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MatrixModelCatalogUpdateOne) Select(field string, fields ...string) *MatrixModelCatalogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MatrixModelCatalog entity.
func (_u *MatrixModelCatalogUpdateOne) Save(ctx context.Context) (*MatrixModelCatalog, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MatrixModelCatalogUpdateOne) SaveX(ctx context.Context) *MatrixModelCatalog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MatrixModelCatalogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MatrixModelCatalogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MatrixModelCatalogUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := matrixmodelcatalog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MatrixModelCatalogUpdateOne) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := matrixmodelcatalog.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "MatrixModelCatalog.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := matrixmodelcatalog.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "MatrixModelCatalog.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := matrixmodelcatalog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MatrixModelCatalog.status": %w`, err)}
		}
	}
	return nil
}

func (_u *MatrixModelCatalogUpdateOne) sqlSave(ctx context.Context) (_node *MatrixModelCatalog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(matrixmodelcatalog.Table, matrixmodelcatalog.Columns, sqlgraph.NewFieldSpec(matrixmodelcatalog.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MatrixModelCatalog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, matrixmodelcatalog.FieldID)
		for _, f := range fields {
			if !matrixmodelcatalog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != matrixmodelcatalog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(matrixmodelcatalog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(matrixmodelcatalog.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(matrixmodelcatalog.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(matrixmodelcatalog.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.OwnedBy(); ok {
		_spec.SetField(matrixmodelcatalog.FieldOwnedBy, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOwnedBy(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, matrixmodelcatalog.FieldOwnedBy, value)
		})
	}
	if value, ok := _u.mutation.ModelTypes(); ok {
		_spec.SetField(matrixmodelcatalog.FieldModelTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedModelTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, matrixmodelcatalog.FieldModelTypes, value)
		})
	}
	if value, ok := _u.mutation.SupportedEndpointTypes(); ok {
		_spec.SetField(matrixmodelcatalog.FieldSupportedEndpointTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSupportedEndpointTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, matrixmodelcatalog.FieldSupportedEndpointTypes, value)
		})
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(matrixmodelcatalog.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, matrixmodelcatalog.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.RawEntries(); ok {
		_spec.SetField(matrixmodelcatalog.FieldRawEntries, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRawEntries(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, matrixmodelcatalog.FieldRawEntries, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(matrixmodelcatalog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(matrixmodelcatalog.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(matrixmodelcatalog.FieldSyncedAt, field.TypeTime, value)
	}
	_node = &MatrixModelCatalog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{matrixmodelcatalog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
