// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/mentorprojectapplication"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/project"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/user"
)

// MentorProjectApplicationCreate is the builder for creating a MentorProjectApplication entity.
type MentorProjectApplicationCreate struct {
	config
	mutation *MentorProjectApplicationMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *MentorProjectApplicationCreate) SetCreatedAt(v time.Time) *MentorProjectApplicationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MentorProjectApplicationCreate) SetNillableCreatedAt(v *time.Time) *MentorProjectApplicationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *MentorProjectApplicationCreate) SetProjectID(v uuid.UUID) *MentorProjectApplicationCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetMentorID sets the "mentor_id" field.
func (_c *MentorProjectApplicationCreate) SetMentorID(v uuid.UUID) *MentorProjectApplicationCreate {
	_c.mutation.SetMentorID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *MentorProjectApplicationCreate) SetStatus(v mentorprojectapplication.Status) *MentorProjectApplicationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MentorProjectApplicationCreate) SetNillableStatus(v *mentorprojectapplication.Status) *MentorProjectApplicationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetReviewedBy sets the "reviewed_by" field.
func (_c *MentorProjectApplicationCreate) SetReviewedBy(v uuid.UUID) *MentorProjectApplicationCreate {
	_c.mutation.SetReviewedBy(v)
	return _c
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_c *MentorProjectApplicationCreate) SetNillableReviewedBy(v *uuid.UUID) *MentorProjectApplicationCreate {
	if v != nil {
		_c.SetReviewedBy(*v)
	}
	return _c
}

// SetReviewComment sets the "review_comment" field.
func (_c *MentorProjectApplicationCreate) SetReviewComment(v string) *MentorProjectApplicationCreate {
	_c.mutation.SetReviewComment(v)
	return _c
}

// SetNillableReviewComment sets the "review_comment" field if the given value is not nil.
func (_c *MentorProjectApplicationCreate) SetNillableReviewComment(v *string) *MentorProjectApplicationCreate {
	if v != nil {
		_c.SetReviewComment(*v)
	}
	return _c
}

// SetReviewedAt sets the "reviewed_at" field.
func (_c *MentorProjectApplicationCreate) SetReviewedAt(v time.Time) *MentorProjectApplicationCreate {
	_c.mutation.SetReviewedAt(v)
	return _c
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_c *MentorProjectApplicationCreate) SetNillableReviewedAt(v *time.Time) *MentorProjectApplicationCreate {
	if v != nil {
		_c.SetReviewedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MentorProjectApplicationCreate) SetID(v uuid.UUID) *MentorProjectApplicationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MentorProjectApplicationCreate) SetNillableID(v *uuid.UUID) *MentorProjectApplicationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *MentorProjectApplicationCreate) SetProject(v *Project) *MentorProjectApplicationCreate {
	return _c.SetProjectID(v.ID)
}

// SetMentor sets the "mentor" edge to the User entity.
func (_c *MentorProjectApplicationCreate) SetMentor(v *User) *MentorProjectApplicationCreate {
	return _c.SetMentorID(v.ID)
}

// SetReviewerID sets the "reviewer" edge to the User entity by ID.
func (_c *MentorProjectApplicationCreate) SetReviewerID(id uuid.UUID) *MentorProjectApplicationCreate {
	_c.mutation.SetReviewerID(id)
	return _c
}

// SetNillableReviewerID sets the "reviewer" edge to the User entity by ID if the given value is not nil.
func (_c *MentorProjectApplicationCreate) SetNillableReviewerID(id *uuid.UUID) *MentorProjectApplicationCreate {
	if id != nil {
		_c = _c.SetReviewerID(*id)
	}
	return _c
}

// SetReviewer sets the "reviewer" edge to the User entity.
func (_c *MentorProjectApplicationCreate) SetReviewer(v *User) *MentorProjectApplicationCreate {
	return _c.SetReviewerID(v.ID)
}

// Mutation returns the MentorProjectApplicationMutation object of the builder.
func (_c *MentorProjectApplicationCreate) Mutation() *MentorProjectApplicationMutation {
	return _c.mutation
}

// Save creates the MentorProjectApplication in the database.
func (_c *MentorProjectApplicationCreate) Save(ctx context.Context) (*MentorProjectApplication, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MentorProjectApplicationCreate) SaveX(ctx context.Context) *MentorProjectApplication {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MentorProjectApplicationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MentorProjectApplicationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MentorProjectApplicationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mentorprojectapplication.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := mentorprojectapplication.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := mentorprojectapplication.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MentorProjectApplicationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MentorProjectApplication.created_at"`)}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "MentorProjectApplication.project_id"`)}
	}
	if _, ok := _c.mutation.MentorID(); !ok {
		return &ValidationError{Name: "mentor_id", err: errors.New(`ent: missing required field "MentorProjectApplication.mentor_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MentorProjectApplication.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := mentorprojectapplication.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MentorProjectApplication.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ReviewComment(); ok {
		if err := mentorprojectapplication.ReviewCommentValidator(v); err != nil {
			return &ValidationError{Name: "review_comment", err: fmt.Errorf(`ent: validator failed for field "MentorProjectApplication.review_comment": %w`, err)}
		}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "MentorProjectApplication.project"`)}
	}
	if len(_c.mutation.MentorIDs()) == 0 {
		return &ValidationError{Name: "mentor", err: errors.New(`ent: missing required edge "MentorProjectApplication.mentor"`)}
	}
	return nil
}

func (_c *MentorProjectApplicationCreate) sqlSave(ctx context.Context) (*MentorProjectApplication, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MentorProjectApplicationCreate) createSpec() (*MentorProjectApplication, *sqlgraph.CreateSpec) {
	var (
		_node = &MentorProjectApplication{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mentorprojectapplication.Table, sqlgraph.NewFieldSpec(mentorprojectapplication.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mentorprojectapplication.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(mentorprojectapplication.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ReviewComment(); ok {
		_spec.SetField(mentorprojectapplication.FieldReviewComment, field.TypeString, value)
		_node.ReviewComment = &value
	}
	if value, ok := _c.mutation.ReviewedAt(); ok {
		_spec.SetField(mentorprojectapplication.FieldReviewedAt, field.TypeTime, value)
		_node.ReviewedAt = &value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mentorprojectapplication.ProjectTable,
			Columns: []string{mentorprojectapplication.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MentorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mentorprojectapplication.MentorTable,
			Columns: []string{mentorprojectapplication.MentorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MentorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReviewerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mentorprojectapplication.ReviewerTable,
			Columns: []string{mentorprojectapplication.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ReviewedBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MentorProjectApplicationCreateBulk is the builder for creating many MentorProjectApplication entities in bulk.
type MentorProjectApplicationCreateBulk struct {
	config
	err      error
	builders []*MentorProjectApplicationCreate
}

// Save creates the MentorProjectApplication entities in the database.
func (_c *MentorProjectApplicationCreateBulk) Save(ctx context.Context) ([]*MentorProjectApplication, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MentorProjectApplication, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MentorProjectApplicationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MentorProjectApplicationCreateBulk) SaveX(ctx context.Context) []*MentorProjectApplication {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MentorProjectApplicationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MentorProjectApplicationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
