// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/model"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/modelbinding"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/provider"
)

// ModelBindingCreate is the builder for creating a ModelBinding entity.
type ModelBindingCreate struct {
	config
	mutation *ModelBindingMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelBindingCreate) SetCreatedAt(v time.Time) *ModelBindingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelBindingCreate) SetNillableCreatedAt(v *time.Time) *ModelBindingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelBindingCreate) SetUpdatedAt(v time.Time) *ModelBindingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelBindingCreate) SetNillableUpdatedAt(v *time.Time) *ModelBindingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetModelID sets the "model_id" field.
func (_c *ModelBindingCreate) SetModelID(v uuid.UUID) *ModelBindingCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetProviderID sets the "provider_id" field.
func (_c *ModelBindingCreate) SetProviderID(v uuid.UUID) *ModelBindingCreate {
	_c.mutation.SetProviderID(v)
	return _c
}

// SetUpstreamModelName sets the "upstream_model_name" field.
func (_c *ModelBindingCreate) SetUpstreamModelName(v string) *ModelBindingCreate {
	_c.mutation.SetUpstreamModelName(v)
	return _c
}

// SetAdapter sets the "adapter" field.
func (_c *ModelBindingCreate) SetAdapter(v modelbinding.Adapter) *ModelBindingCreate {
	_c.mutation.SetAdapter(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *ModelBindingCreate) SetPriority(v int) *ModelBindingCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *ModelBindingCreate) SetNillablePriority(v *int) *ModelBindingCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ModelBindingCreate) SetStatus(v modelbinding.Status) *ModelBindingCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ModelBindingCreate) SetNillableStatus(v *modelbinding.Status) *ModelBindingCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ModelBindingCreate) SetID(v uuid.UUID) *ModelBindingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ModelBindingCreate) SetNillableID(v *uuid.UUID) *ModelBindingCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetModel sets the "model" edge to the Model entity.
func (_c *ModelBindingCreate) SetModel(v *Model) *ModelBindingCreate {
	return _c.SetModelID(v.ID)
}

// SetProvider sets the "provider" edge to the Provider entity.
func (_c *ModelBindingCreate) SetProvider(v *Provider) *ModelBindingCreate {
	return _c.SetProviderID(v.ID)
}

// Mutation returns the ModelBindingMutation object of the builder.
func (_c *ModelBindingCreate) Mutation() *ModelBindingMutation {
	return _c.mutation
}

// Save creates the ModelBinding in the database.
func (_c *ModelBindingCreate) Save(ctx context.Context) (*ModelBinding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelBindingCreate) SaveX(ctx context.Context) *ModelBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelBindingCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelbinding.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := modelbinding.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := modelbinding.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := modelbinding.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := modelbinding.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelBindingCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ModelBinding.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ModelBinding.updated_at"`)}
	}
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "ModelBinding.model_id"`)}
	}
	if _, ok := _c.mutation.ProviderID(); !ok {
		return &ValidationError{Name: "provider_id", err: errors.New(`ent: missing required field "ModelBinding.provider_id"`)}
	}
	if _, ok := _c.mutation.UpstreamModelName(); !ok {
		return &ValidationError{Name: "upstream_model_name", err: errors.New(`ent: missing required field "ModelBinding.upstream_model_name"`)}
	}
	if v, ok := _c.mutation.UpstreamModelName(); ok {
		if err := modelbinding.UpstreamModelNameValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model_name", err: fmt.Errorf(`ent: validator failed for field "ModelBinding.upstream_model_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Adapter(); !ok {
		return &ValidationError{Name: "adapter", err: errors.New(`ent: missing required field "ModelBinding.adapter"`)}
	}
	if v, ok := _c.mutation.Adapter(); ok {
		if err := modelbinding.AdapterValidator(v); err != nil {
			return &ValidationError{Name: "adapter", err: fmt.Errorf(`ent: validator failed for field "ModelBinding.adapter": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "ModelBinding.priority"`)}
	}
	if v, ok := _c.mutation.Priority(); ok {
		if err := modelbinding.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "ModelBinding.priority": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ModelBinding.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := modelbinding.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ModelBinding.status": %w`, err)}
		}
	}
	if len(_c.mutation.ModelIDs()) == 0 {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required edge "ModelBinding.model"`)}
	}
	if len(_c.mutation.ProviderIDs()) == 0 {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required edge "ModelBinding.provider"`)}
	}
	return nil
}

func (_c *ModelBindingCreate) sqlSave(ctx context.Context) (*ModelBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelBindingCreate) createSpec() (*ModelBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelbinding.Table, sqlgraph.NewFieldSpec(modelbinding.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelbinding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelbinding.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UpstreamModelName(); ok {
		_spec.SetField(modelbinding.FieldUpstreamModelName, field.TypeString, value)
		_node.UpstreamModelName = value
	}
	if value, ok := _c.mutation.Adapter(); ok {
		_spec.SetField(modelbinding.FieldAdapter, field.TypeEnum, value)
		_node.Adapter = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(modelbinding.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(modelbinding.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.ModelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelbinding.ModelTable,
			Columns: []string{modelbinding.ModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ModelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelbinding.ProviderTable,
			Columns: []string{modelbinding.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProviderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ModelBindingCreateBulk is the builder for creating many ModelBinding entities in bulk.
type ModelBindingCreateBulk struct {
	config
	err      error
	builders []*ModelBindingCreate
}

// Save creates the ModelBinding entities in the database.
func (_c *ModelBindingCreateBulk) Save(ctx context.Context) ([]*ModelBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelBindingCreateBulk) SaveX(ctx context.Context) []*ModelBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
