// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/model"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/modelbinding"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/provider"
)

// ModelBinding is the model entity for the ModelBinding schema.
type ModelBinding struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID uuid.UUID `json:"model_id,omitempty"`
	// ProviderID holds the value of the "provider_id" field.
	ProviderID uuid.UUID `json:"provider_id,omitempty"`
	// UpstreamModelName holds the value of the "upstream_model_name" field.
	UpstreamModelName string `json:"upstream_model_name,omitempty"`
	// Adapter holds the value of the "adapter" field.
	Adapter modelbinding.Adapter `json:"adapter,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority int `json:"priority,omitempty"`
	// Status holds the value of the "status" field.
	Status modelbinding.Status `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ModelBindingQuery when eager-loading is set.
	Edges        ModelBindingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ModelBindingEdges holds the relations/edges for other nodes in the graph.
type ModelBindingEdges struct {
	// Model holds the value of the model edge.
	Model *Model `json:"model,omitempty"`
	// Provider holds the value of the provider edge.
	Provider *Provider `json:"provider,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ModelOrErr returns the Model value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ModelBindingEdges) ModelOrErr() (*Model, error) {
	if e.Model != nil {
		return e.Model, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: model.Label}
	}
	return nil, &NotLoadedError{edge: "model"}
}

// ProviderOrErr returns the Provider value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ModelBindingEdges) ProviderOrErr() (*Provider, error) {
	if e.Provider != nil {
		return e.Provider, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: provider.Label}
	}
	return nil, &NotLoadedError{edge: "provider"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelbinding.FieldPriority:
			values[i] = new(sql.NullInt64)
		case modelbinding.FieldUpstreamModelName, modelbinding.FieldAdapter, modelbinding.FieldStatus:
			values[i] = new(sql.NullString)
		case modelbinding.FieldCreatedAt, modelbinding.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case modelbinding.FieldID, modelbinding.FieldModelID, modelbinding.FieldProviderID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelBinding fields.
func (_m *ModelBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelbinding.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case modelbinding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case modelbinding.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case modelbinding.FieldModelID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value != nil {
				_m.ModelID = *value
			}
		case modelbinding.FieldProviderID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value != nil {
				_m.ProviderID = *value
			}
		case modelbinding.FieldUpstreamModelName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model_name", values[i])
			} else if value.Valid {
				_m.UpstreamModelName = value.String
			}
		case modelbinding.FieldAdapter:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field adapter", values[i])
			} else if value.Valid {
				_m.Adapter = modelbinding.Adapter(value.String)
			}
		case modelbinding.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case modelbinding.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = modelbinding.Status(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelBinding.
// This includes values selected through modifiers, order, etc.
func (_m *ModelBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryModel queries the "model" edge of the ModelBinding entity.
func (_m *ModelBinding) QueryModel() *ModelQuery {
	return NewModelBindingClient(_m.config).QueryModel(_m)
}

// QueryProvider queries the "provider" edge of the ModelBinding entity.
func (_m *ModelBinding) QueryProvider() *ProviderQuery {
	return NewModelBindingClient(_m.config).QueryProvider(_m)
}

// Update returns a builder for updating this ModelBinding.
// Note that you need to call ModelBinding.Unwrap() before calling this method if this ModelBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelBinding) Update() *ModelBindingUpdateOne {
	return NewModelBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelBinding) Unwrap() *ModelBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelBinding) String() string {
	var builder strings.Builder
	builder.WriteString("ModelBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelID))
	builder.WriteString(", ")
	builder.WriteString("provider_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderID))
	builder.WriteString(", ")
	builder.WriteString("upstream_model_name=")
	builder.WriteString(_m.UpstreamModelName)
	builder.WriteString(", ")
	builder.WriteString("adapter=")
	builder.WriteString(fmt.Sprintf("%v", _m.Adapter))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// ModelBindings is a parsable slice of ModelBinding.
type ModelBindings []*ModelBinding
