// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/apikeymodel"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/model"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/modelbinding"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/predicate"
)

// ModelUpdate is the builder for updating Model entities.
type ModelUpdate struct {
	config
	hooks    []Hook
	mutation *ModelMutation
}

// Where appends a list predicates to the ModelUpdate builder.
func (_u *ModelUpdate) Where(ps ...predicate.Model) *ModelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelUpdate) SetUpdatedAt(v time.Time) *ModelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *ModelUpdate) SetModelID(v string) *ModelUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableModelID(v *string) *ModelUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ModelUpdate) SetDisplayName(v string) *ModelUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableDisplayName(v *string) *ModelUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ModelUpdate) SetDescription(v string) *ModelUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableDescription(v *string) *ModelUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ModelUpdate) ClearDescription() *ModelUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCategory sets the "category" field.
func (_u *ModelUpdate) SetCategory(v model.Category) *ModelUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableCategory(v *model.Category) *ModelUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *ModelUpdate) SetCapabilities(v []string) *ModelUpdate {
	_u.mutation.SetCapabilities(v)
	return _u
}

// AppendCapabilities appends value to the "capabilities" field.
func (_u *ModelUpdate) AppendCapabilities(v []string) *ModelUpdate {
	_u.mutation.AppendCapabilities(v)
	return _u
}

// SetInputModalities sets the "input_modalities" field.
func (_u *ModelUpdate) SetInputModalities(v []string) *ModelUpdate {
	_u.mutation.SetInputModalities(v)
	return _u
}

// AppendInputModalities appends value to the "input_modalities" field.
func (_u *ModelUpdate) AppendInputModalities(v []string) *ModelUpdate {
	_u.mutation.AppendInputModalities(v)
	return _u
}

// SetOutputModalities sets the "output_modalities" field.
func (_u *ModelUpdate) SetOutputModalities(v []string) *ModelUpdate {
	_u.mutation.SetOutputModalities(v)
	return _u
}

// AppendOutputModalities appends value to the "output_modalities" field.
func (_u *ModelUpdate) AppendOutputModalities(v []string) *ModelUpdate {
	_u.mutation.AppendOutputModalities(v)
	return _u
}

// SetContextWindow sets the "context_window" field.
func (_u *ModelUpdate) SetContextWindow(v int) *ModelUpdate {
	_u.mutation.ResetContextWindow()
	_u.mutation.SetContextWindow(v)
	return _u
}

// SetNillableContextWindow sets the "context_window" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableContextWindow(v *int) *ModelUpdate {
	if v != nil {
		_u.SetContextWindow(*v)
	}
	return _u
}

// AddContextWindow adds value to the "context_window" field.
func (_u *ModelUpdate) AddContextWindow(v int) *ModelUpdate {
	_u.mutation.AddContextWindow(v)
	return _u
}

// ClearContextWindow clears the value of the "context_window" field.
func (_u *ModelUpdate) ClearContextWindow() *ModelUpdate {
	_u.mutation.ClearContextWindow()
	return _u
}

// SetMaxInputTokens sets the "max_input_tokens" field.
func (_u *ModelUpdate) SetMaxInputTokens(v int) *ModelUpdate {
	_u.mutation.ResetMaxInputTokens()
	_u.mutation.SetMaxInputTokens(v)
	return _u
}

// SetNillableMaxInputTokens sets the "max_input_tokens" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableMaxInputTokens(v *int) *ModelUpdate {
	if v != nil {
		_u.SetMaxInputTokens(*v)
	}
	return _u
}

// AddMaxInputTokens adds value to the "max_input_tokens" field.
func (_u *ModelUpdate) AddMaxInputTokens(v int) *ModelUpdate {
	_u.mutation.AddMaxInputTokens(v)
	return _u
}

// ClearMaxInputTokens clears the value of the "max_input_tokens" field.
func (_u *ModelUpdate) ClearMaxInputTokens() *ModelUpdate {
	_u.mutation.ClearMaxInputTokens()
	return _u
}

// SetMaxOutputTokens sets the "max_output_tokens" field.
func (_u *ModelUpdate) SetMaxOutputTokens(v int) *ModelUpdate {
	_u.mutation.ResetMaxOutputTokens()
	_u.mutation.SetMaxOutputTokens(v)
	return _u
}

// SetNillableMaxOutputTokens sets the "max_output_tokens" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableMaxOutputTokens(v *int) *ModelUpdate {
	if v != nil {
		_u.SetMaxOutputTokens(*v)
	}
	return _u
}

// AddMaxOutputTokens adds value to the "max_output_tokens" field.
func (_u *ModelUpdate) AddMaxOutputTokens(v int) *ModelUpdate {
	_u.mutation.AddMaxOutputTokens(v)
	return _u
}

// ClearMaxOutputTokens clears the value of the "max_output_tokens" field.
func (_u *ModelUpdate) ClearMaxOutputTokens() *ModelUpdate {
	_u.mutation.ClearMaxOutputTokens()
	return _u
}

// SetIsCommon sets the "is_common" field.
func (_u *ModelUpdate) SetIsCommon(v bool) *ModelUpdate {
	_u.mutation.SetIsCommon(v)
	return _u
}

// SetNillableIsCommon sets the "is_common" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableIsCommon(v *bool) *ModelUpdate {
	if v != nil {
		_u.SetIsCommon(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ModelUpdate) SetStatus(v model.Status) *ModelUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableStatus(v *model.Status) *ModelUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreditMultiplierMilli sets the "credit_multiplier_milli" field.
func (_u *ModelUpdate) SetCreditMultiplierMilli(v int64) *ModelUpdate {
	_u.mutation.ResetCreditMultiplierMilli()
	_u.mutation.SetCreditMultiplierMilli(v)
	return _u
}

// SetNillableCreditMultiplierMilli sets the "credit_multiplier_milli" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableCreditMultiplierMilli(v *int64) *ModelUpdate {
	if v != nil {
		_u.SetCreditMultiplierMilli(*v)
	}
	return _u
}

// AddCreditMultiplierMilli adds value to the "credit_multiplier_milli" field.
func (_u *ModelUpdate) AddCreditMultiplierMilli(v int64) *ModelUpdate {
	_u.mutation.AddCreditMultiplierMilli(v)
	return _u
}

// ClearCreditMultiplierMilli clears the value of the "credit_multiplier_milli" field.
func (_u *ModelUpdate) ClearCreditMultiplierMilli() *ModelUpdate {
	_u.mutation.ClearCreditMultiplierMilli()
	return _u
}

// AddBindingIDs adds the "bindings" edge to the ModelBinding entity by IDs.
func (_u *ModelUpdate) AddBindingIDs(ids ...uuid.UUID) *ModelUpdate {
	_u.mutation.AddBindingIDs(ids...)
	return _u
}

// AddBindings adds the "bindings" edges to the ModelBinding entity.
func (_u *ModelUpdate) AddBindings(v ...*ModelBinding) *ModelUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBindingIDs(ids...)
}

// AddAPIKeyModelIDs adds the "api_key_models" edge to the APIKeyModel entity by IDs.
func (_u *ModelUpdate) AddAPIKeyModelIDs(ids ...uuid.UUID) *ModelUpdate {
	_u.mutation.AddAPIKeyModelIDs(ids...)
	return _u
}

// AddAPIKeyModels adds the "api_key_models" edges to the APIKeyModel entity.
func (_u *ModelUpdate) AddAPIKeyModels(v ...*APIKeyModel) *ModelUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyModelIDs(ids...)
}

// Mutation returns the ModelMutation object of the builder.
func (_u *ModelUpdate) Mutation() *ModelMutation {
	return _u.mutation
}

// ClearBindings clears all "bindings" edges to the ModelBinding entity.
func (_u *ModelUpdate) ClearBindings() *ModelUpdate {
	_u.mutation.ClearBindings()
	return _u
}

// RemoveBindingIDs removes the "bindings" edge to ModelBinding entities by IDs.
func (_u *ModelUpdate) RemoveBindingIDs(ids ...uuid.UUID) *ModelUpdate {
	_u.mutation.RemoveBindingIDs(ids...)
	return _u
}

// RemoveBindings removes "bindings" edges to ModelBinding entities.
func (_u *ModelUpdate) RemoveBindings(v ...*ModelBinding) *ModelUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBindingIDs(ids...)
}

// ClearAPIKeyModels clears all "api_key_models" edges to the APIKeyModel entity.
func (_u *ModelUpdate) ClearAPIKeyModels() *ModelUpdate {
	_u.mutation.ClearAPIKeyModels()
	return _u
}

// RemoveAPIKeyModelIDs removes the "api_key_models" edge to APIKeyModel entities by IDs.
func (_u *ModelUpdate) RemoveAPIKeyModelIDs(ids ...uuid.UUID) *ModelUpdate {
	_u.mutation.RemoveAPIKeyModelIDs(ids...)
	return _u
}

// RemoveAPIKeyModels removes "api_key_models" edges to APIKeyModel entities.
func (_u *ModelUpdate) RemoveAPIKeyModels(v ...*APIKeyModel) *ModelUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyModelIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := model.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelUpdate) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := model.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "Model.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := model.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Model.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := model.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Model.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := model.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Model.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContextWindow(); ok {
		if err := model.ContextWindowValidator(v); err != nil {
			return &ValidationError{Name: "context_window", err: fmt.Errorf(`ent: validator failed for field "Model.context_window": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxInputTokens(); ok {
		if err := model.MaxInputTokensValidator(v); err != nil {
			return &ValidationError{Name: "max_input_tokens", err: fmt.Errorf(`ent: validator failed for field "Model.max_input_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxOutputTokens(); ok {
		if err := model.MaxOutputTokensValidator(v); err != nil {
			return &ValidationError{Name: "max_output_tokens", err: fmt.Errorf(`ent: validator failed for field "Model.max_output_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := model.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Model.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreditMultiplierMilli(); ok {
		if err := model.CreditMultiplierMilliValidator(v); err != nil {
			return &ValidationError{Name: "credit_multiplier_milli", err: fmt.Errorf(`ent: validator failed for field "Model.credit_multiplier_milli": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(model.Table, model.Columns, sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(model.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(model.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(model.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(model.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(model.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(model.FieldCategory, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(model.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCapabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, model.FieldCapabilities, value)
		})
	}
	if value, ok := _u.mutation.InputModalities(); ok {
		_spec.SetField(model.FieldInputModalities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedInputModalities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, model.FieldInputModalities, value)
		})
	}
	if value, ok := _u.mutation.OutputModalities(); ok {
		_spec.SetField(model.FieldOutputModalities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOutputModalities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, model.FieldOutputModalities, value)
		})
	}
	if value, ok := _u.mutation.ContextWindow(); ok {
		_spec.SetField(model.FieldContextWindow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedContextWindow(); ok {
		_spec.AddField(model.FieldContextWindow, field.TypeInt, value)
	}
	if _u.mutation.ContextWindowCleared() {
		_spec.ClearField(model.FieldContextWindow, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxInputTokens(); ok {
		_spec.SetField(model.FieldMaxInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxInputTokens(); ok {
		_spec.AddField(model.FieldMaxInputTokens, field.TypeInt, value)
	}
	if _u.mutation.MaxInputTokensCleared() {
		_spec.ClearField(model.FieldMaxInputTokens, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxOutputTokens(); ok {
		_spec.SetField(model.FieldMaxOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxOutputTokens(); ok {
		_spec.AddField(model.FieldMaxOutputTokens, field.TypeInt, value)
	}
	if _u.mutation.MaxOutputTokensCleared() {
		_spec.ClearField(model.FieldMaxOutputTokens, field.TypeInt)
	}
	if value, ok := _u.mutation.IsCommon(); ok {
		_spec.SetField(model.FieldIsCommon, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(model.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreditMultiplierMilli(); ok {
		_spec.SetField(model.FieldCreditMultiplierMilli, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreditMultiplierMilli(); ok {
		_spec.AddField(model.FieldCreditMultiplierMilli, field.TypeInt64, value)
	}
	if _u.mutation.CreditMultiplierMilliCleared() {
		_spec.ClearField(model.FieldCreditMultiplierMilli, field.TypeInt64)
	}
	if _u.mutation.BindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   model.BindingsTable,
			Columns: []string{model.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelbinding.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBindingsIDs(); len(nodes) > 0 && !_u.mutation.BindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   model.BindingsTable,
			Columns: []string{model.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelbinding.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   model.BindingsTable,
			Columns: []string{model.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelbinding.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   model.APIKeyModelsTable,
			Columns: []string{model.APIKeyModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikeymodel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeyModelsIDs(); len(nodes) > 0 && !_u.mutation.APIKeyModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   model.APIKeyModelsTable,
			Columns: []string{model.APIKeyModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikeymodel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyModelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   model.APIKeyModelsTable,
			Columns: []string{model.APIKeyModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikeymodel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{model.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelUpdateOne is the builder for updating a single Model entity.
type ModelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelUpdateOne) SetUpdatedAt(v time.Time) *ModelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *ModelUpdateOne) SetModelID(v string) *ModelUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableModelID(v *string) *ModelUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ModelUpdateOne) SetDisplayName(v string) *ModelUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableDisplayName(v *string) *ModelUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ModelUpdateOne) SetDescription(v string) *ModelUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableDescription(v *string) *ModelUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ModelUpdateOne) ClearDescription() *ModelUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCategory sets the "category" field.
func (_u *ModelUpdateOne) SetCategory(v model.Category) *ModelUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableCategory(v *model.Category) *ModelUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *ModelUpdateOne) SetCapabilities(v []string) *ModelUpdateOne {
	_u.mutation.SetCapabilities(v)
	return _u
}

// AppendCapabilities appends value to the "capabilities" field.
func (_u *ModelUpdateOne) AppendCapabilities(v []string) *ModelUpdateOne {
	_u.mutation.AppendCapabilities(v)
	return _u
}

// SetInputModalities sets the "input_modalities" field.
func (_u *ModelUpdateOne) SetInputModalities(v []string) *ModelUpdateOne {
	_u.mutation.SetInputModalities(v)
	return _u
}

// AppendInputModalities appends value to the "input_modalities" field.
func (_u *ModelUpdateOne) AppendInputModalities(v []string) *ModelUpdateOne {
	_u.mutation.AppendInputModalities(v)
	return _u
}

// SetOutputModalities sets the "output_modalities" field.
func (_u *ModelUpdateOne) SetOutputModalities(v []string) *ModelUpdateOne {
	_u.mutation.SetOutputModalities(v)
	return _u
}

// AppendOutputModalities appends value to the "output_modalities" field.
func (_u *ModelUpdateOne) AppendOutputModalities(v []string) *ModelUpdateOne {
	_u.mutation.AppendOutputModalities(v)
	return _u
}

// SetContextWindow sets the "context_window" field.
func (_u *ModelUpdateOne) SetContextWindow(v int) *ModelUpdateOne {
	_u.mutation.ResetContextWindow()
	_u.mutation.SetContextWindow(v)
	return _u
}

// SetNillableContextWindow sets the "context_window" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableContextWindow(v *int) *ModelUpdateOne {
	if v != nil {
		_u.SetContextWindow(*v)
	}
	return _u
}

// AddContextWindow adds value to the "context_window" field.
func (_u *ModelUpdateOne) AddContextWindow(v int) *ModelUpdateOne {
	_u.mutation.AddContextWindow(v)
	return _u
}

// ClearContextWindow clears the value of the "context_window" field.
func (_u *ModelUpdateOne) ClearContextWindow() *ModelUpdateOne {
	_u.mutation.ClearContextWindow()
	return _u
}

// SetMaxInputTokens sets the "max_input_tokens" field.
func (_u *ModelUpdateOne) SetMaxInputTokens(v int) *ModelUpdateOne {
	_u.mutation.ResetMaxInputTokens()
	_u.mutation.SetMaxInputTokens(v)
	return _u
}

// SetNillableMaxInputTokens sets the "max_input_tokens" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableMaxInputTokens(v *int) *ModelUpdateOne {
	if v != nil {
		_u.SetMaxInputTokens(*v)
	}
	return _u
}

// AddMaxInputTokens adds value to the "max_input_tokens" field.
func (_u *ModelUpdateOne) AddMaxInputTokens(v int) *ModelUpdateOne {
	_u.mutation.AddMaxInputTokens(v)
	return _u
}

// ClearMaxInputTokens clears the value of the "max_input_tokens" field.
func (_u *ModelUpdateOne) ClearMaxInputTokens() *ModelUpdateOne {
	_u.mutation.ClearMaxInputTokens()
	return _u
}

// SetMaxOutputTokens sets the "max_output_tokens" field.
func (_u *ModelUpdateOne) SetMaxOutputTokens(v int) *ModelUpdateOne {
	_u.mutation.ResetMaxOutputTokens()
	_u.mutation.SetMaxOutputTokens(v)
	return _u
}

// SetNillableMaxOutputTokens sets the "max_output_tokens" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableMaxOutputTokens(v *int) *ModelUpdateOne {
	if v != nil {
		_u.SetMaxOutputTokens(*v)
	}
	return _u
}

// AddMaxOutputTokens adds value to the "max_output_tokens" field.
func (_u *ModelUpdateOne) AddMaxOutputTokens(v int) *ModelUpdateOne {
	_u.mutation.AddMaxOutputTokens(v)
	return _u
}

// ClearMaxOutputTokens clears the value of the "max_output_tokens" field.
func (_u *ModelUpdateOne) ClearMaxOutputTokens() *ModelUpdateOne {
	_u.mutation.ClearMaxOutputTokens()
	return _u
}

// SetIsCommon sets the "is_common" field.
func (_u *ModelUpdateOne) SetIsCommon(v bool) *ModelUpdateOne {
	_u.mutation.SetIsCommon(v)
	return _u
}

// SetNillableIsCommon sets the "is_common" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableIsCommon(v *bool) *ModelUpdateOne {
	if v != nil {
		_u.SetIsCommon(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ModelUpdateOne) SetStatus(v model.Status) *ModelUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableStatus(v *model.Status) *ModelUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreditMultiplierMilli sets the "credit_multiplier_milli" field.
func (_u *ModelUpdateOne) SetCreditMultiplierMilli(v int64) *ModelUpdateOne {
	_u.mutation.ResetCreditMultiplierMilli()
	_u.mutation.SetCreditMultiplierMilli(v)
	return _u
}

// SetNillableCreditMultiplierMilli sets the "credit_multiplier_milli" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableCreditMultiplierMilli(v *int64) *ModelUpdateOne {
	if v != nil {
		_u.SetCreditMultiplierMilli(*v)
	}
	return _u
}

// AddCreditMultiplierMilli adds value to the "credit_multiplier_milli" field.
func (_u *ModelUpdateOne) AddCreditMultiplierMilli(v int64) *ModelUpdateOne {
	_u.mutation.AddCreditMultiplierMilli(v)
	return _u
}

// ClearCreditMultiplierMilli clears the value of the "credit_multiplier_milli" field.
func (_u *ModelUpdateOne) ClearCreditMultiplierMilli() *ModelUpdateOne {
	_u.mutation.ClearCreditMultiplierMilli()
	return _u
}

// AddBindingIDs adds the "bindings" edge to the ModelBinding entity by IDs.
func (_u *ModelUpdateOne) AddBindingIDs(ids ...uuid.UUID) *ModelUpdateOne {
	_u.mutation.AddBindingIDs(ids...)
	return _u
}

// AddBindings adds the "bindings" edges to the ModelBinding entity.
func (_u *ModelUpdateOne) AddBindings(v ...*ModelBinding) *ModelUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBindingIDs(ids...)
}

// AddAPIKeyModelIDs adds the "api_key_models" edge to the APIKeyModel entity by IDs.
func (_u *ModelUpdateOne) AddAPIKeyModelIDs(ids ...uuid.UUID) *ModelUpdateOne {
	_u.mutation.AddAPIKeyModelIDs(ids...)
	return _u
}

// AddAPIKeyModels adds the "api_key_models" edges to the APIKeyModel entity.
func (_u *ModelUpdateOne) AddAPIKeyModels(v ...*APIKeyModel) *ModelUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyModelIDs(ids...)
}

// Mutation returns the ModelMutation object of the builder.
func (_u *ModelUpdateOne) Mutation() *ModelMutation {
	return _u.mutation
}

// ClearBindings clears all "bindings" edges to the ModelBinding entity.
func (_u *ModelUpdateOne) ClearBindings() *ModelUpdateOne {
	_u.mutation.ClearBindings()
	return _u
}

// RemoveBindingIDs removes the "bindings" edge to ModelBinding entities by IDs.
func (_u *ModelUpdateOne) RemoveBindingIDs(ids ...uuid.UUID) *ModelUpdateOne {
	_u.mutation.RemoveBindingIDs(ids...)
	return _u
}

// RemoveBindings removes "bindings" edges to ModelBinding entities.
func (_u *ModelUpdateOne) RemoveBindings(v ...*ModelBinding) *ModelUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBindingIDs(ids...)
}

// ClearAPIKeyModels clears all "api_key_models" edges to the APIKeyModel entity.
func (_u *ModelUpdateOne) ClearAPIKeyModels() *ModelUpdateOne {
	_u.mutation.ClearAPIKeyModels()
	return _u
}

// RemoveAPIKeyModelIDs removes the "api_key_models" edge to APIKeyModel entities by IDs.
func (_u *ModelUpdateOne) RemoveAPIKeyModelIDs(ids ...uuid.UUID) *ModelUpdateOne {
	_u.mutation.RemoveAPIKeyModelIDs(ids...)
	return _u
}

// RemoveAPIKeyModels removes "api_key_models" edges to APIKeyModel entities.
func (_u *ModelUpdateOne) RemoveAPIKeyModels(v ...*APIKeyModel) *ModelUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyModelIDs(ids...)
}

// Where appends a list predicates to the ModelUpdate builder.
func (_u *ModelUpdateOne) Where(ps ...predicate.Model) *ModelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelUpdateOne) Select(field string, fields ...string) *ModelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Model entity.
func (_u *ModelUpdateOne) Save(ctx context.Context) (*Model, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelUpdateOne) SaveX(ctx context.Context) *Model {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := model.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelUpdateOne) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := model.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "Model.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := model.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Model.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := model.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Model.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := model.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Model.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContextWindow(); ok {
		if err := model.ContextWindowValidator(v); err != nil {
			return &ValidationError{Name: "context_window", err: fmt.Errorf(`ent: validator failed for field "Model.context_window": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxInputTokens(); ok {
		if err := model.MaxInputTokensValidator(v); err != nil {
			return &ValidationError{Name: "max_input_tokens", err: fmt.Errorf(`ent: validator failed for field "Model.max_input_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxOutputTokens(); ok {
		if err := model.MaxOutputTokensValidator(v); err != nil {
			return &ValidationError{Name: "max_output_tokens", err: fmt.Errorf(`ent: validator failed for field "Model.max_output_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := model.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Model.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreditMultiplierMilli(); ok {
		if err := model.CreditMultiplierMilliValidator(v); err != nil {
			return &ValidationError{Name: "credit_multiplier_milli", err: fmt.Errorf(`ent: validator failed for field "Model.credit_multiplier_milli": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelUpdateOne) sqlSave(ctx context.Context) (_node *Model, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(model.Table, model.Columns, sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Model.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, model.FieldID)
		for _, f := range fields {
			if !model.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != model.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(model.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(model.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(model.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(model.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(model.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(model.FieldCategory, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(model.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCapabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, model.FieldCapabilities, value)
		})
	}
	if value, ok := _u.mutation.InputModalities(); ok {
		_spec.SetField(model.FieldInputModalities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedInputModalities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, model.FieldInputModalities, value)
		})
	}
	if value, ok := _u.mutation.OutputModalities(); ok {
		_spec.SetField(model.FieldOutputModalities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOutputModalities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, model.FieldOutputModalities, value)
		})
	}
	if value, ok := _u.mutation.ContextWindow(); ok {
		_spec.SetField(model.FieldContextWindow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedContextWindow(); ok {
		_spec.AddField(model.FieldContextWindow, field.TypeInt, value)
	}
	if _u.mutation.ContextWindowCleared() {
		_spec.ClearField(model.FieldContextWindow, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxInputTokens(); ok {
		_spec.SetField(model.FieldMaxInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxInputTokens(); ok {
		_spec.AddField(model.FieldMaxInputTokens, field.TypeInt, value)
	}
	if _u.mutation.MaxInputTokensCleared() {
		_spec.ClearField(model.FieldMaxInputTokens, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxOutputTokens(); ok {
		_spec.SetField(model.FieldMaxOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxOutputTokens(); ok {
		_spec.AddField(model.FieldMaxOutputTokens, field.TypeInt, value)
	}
	if _u.mutation.MaxOutputTokensCleared() {
		_spec.ClearField(model.FieldMaxOutputTokens, field.TypeInt)
	}
	if value, ok := _u.mutation.IsCommon(); ok {
		_spec.SetField(model.FieldIsCommon, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(model.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreditMultiplierMilli(); ok {
		_spec.SetField(model.FieldCreditMultiplierMilli, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreditMultiplierMilli(); ok {
		_spec.AddField(model.FieldCreditMultiplierMilli, field.TypeInt64, value)
	}
	if _u.mutation.CreditMultiplierMilliCleared() {
		_spec.ClearField(model.FieldCreditMultiplierMilli, field.TypeInt64)
	}
	if _u.mutation.BindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   model.BindingsTable,
			Columns: []string{model.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelbinding.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBindingsIDs(); len(nodes) > 0 && !_u.mutation.BindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   model.BindingsTable,
			Columns: []string{model.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelbinding.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   model.BindingsTable,
			Columns: []string{model.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelbinding.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   model.APIKeyModelsTable,
			Columns: []string{model.APIKeyModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikeymodel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeyModelsIDs(); len(nodes) > 0 && !_u.mutation.APIKeyModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   model.APIKeyModelsTable,
			Columns: []string{model.APIKeyModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikeymodel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyModelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   model.APIKeyModelsTable,
			Columns: []string{model.APIKeyModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikeymodel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Model{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{model.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
