// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/monitoredinput"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/predicate"
)

// MonitoredInputDelete is the builder for deleting a MonitoredInput entity.
type MonitoredInputDelete struct {
	config
	hooks    []Hook
	mutation *MonitoredInputMutation
}

// Where appends a list predicates to the MonitoredInputDelete builder.
func (_d *MonitoredInputDelete) Where(ps ...predicate.MonitoredInput) *MonitoredInputDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MonitoredInputDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MonitoredInputDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MonitoredInputDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(monitoredinput.Table, sqlgraph.NewFieldSpec(monitoredinput.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MonitoredInputDeleteOne is the builder for deleting a single MonitoredInput entity.
type MonitoredInputDeleteOne struct {
	_d *MonitoredInputDelete
}

// Where appends a list predicates to the MonitoredInputDelete builder.
func (_d *MonitoredInputDeleteOne) Where(ps ...predicate.MonitoredInput) *MonitoredInputDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MonitoredInputDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{monitoredinput.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MonitoredInputDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
