// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/project"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/projectmonthcreditbucket"
)

// ProjectMonthCreditBucket is the model entity for the ProjectMonthCreditBucket schema.
type ProjectMonthCreditBucket struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID uuid.UUID `json:"project_id,omitempty"`
	// Month holds the value of the "month" field.
	Month time.Time `json:"month,omitempty"`
	// QuotaMilli holds the value of the "quota_milli" field.
	QuotaMilli int64 `json:"quota_milli,omitempty"`
	// AllocatedMilli holds the value of the "allocated_milli" field.
	AllocatedMilli int64 `json:"allocated_milli,omitempty"`
	// ChargedMilli holds the value of the "charged_milli" field.
	ChargedMilli int64 `json:"charged_milli,omitempty"`
	// PendingMilli holds the value of the "pending_milli" field.
	PendingMilli int64 `json:"pending_milli,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectMonthCreditBucketQuery when eager-loading is set.
	Edges        ProjectMonthCreditBucketEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProjectMonthCreditBucketEdges holds the relations/edges for other nodes in the graph.
type ProjectMonthCreditBucketEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectMonthCreditBucketEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProjectMonthCreditBucket) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case projectmonthcreditbucket.FieldQuotaMilli, projectmonthcreditbucket.FieldAllocatedMilli, projectmonthcreditbucket.FieldChargedMilli, projectmonthcreditbucket.FieldPendingMilli:
			values[i] = new(sql.NullInt64)
		case projectmonthcreditbucket.FieldCreatedAt, projectmonthcreditbucket.FieldUpdatedAt, projectmonthcreditbucket.FieldMonth:
			values[i] = new(sql.NullTime)
		case projectmonthcreditbucket.FieldID, projectmonthcreditbucket.FieldProjectID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProjectMonthCreditBucket fields.
func (_m *ProjectMonthCreditBucket) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case projectmonthcreditbucket.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case projectmonthcreditbucket.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case projectmonthcreditbucket.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case projectmonthcreditbucket.FieldProjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value != nil {
				_m.ProjectID = *value
			}
		case projectmonthcreditbucket.FieldMonth:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field month", values[i])
			} else if value.Valid {
				_m.Month = value.Time
			}
		case projectmonthcreditbucket.FieldQuotaMilli:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quota_milli", values[i])
			} else if value.Valid {
				_m.QuotaMilli = value.Int64
			}
		case projectmonthcreditbucket.FieldAllocatedMilli:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field allocated_milli", values[i])
			} else if value.Valid {
				_m.AllocatedMilli = value.Int64
			}
		case projectmonthcreditbucket.FieldChargedMilli:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field charged_milli", values[i])
			} else if value.Valid {
				_m.ChargedMilli = value.Int64
			}
		case projectmonthcreditbucket.FieldPendingMilli:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pending_milli", values[i])
			} else if value.Valid {
				_m.PendingMilli = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProjectMonthCreditBucket.
// This includes values selected through modifiers, order, etc.
func (_m *ProjectMonthCreditBucket) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the ProjectMonthCreditBucket entity.
func (_m *ProjectMonthCreditBucket) QueryProject() *ProjectQuery {
	return NewProjectMonthCreditBucketClient(_m.config).QueryProject(_m)
}

// Update returns a builder for updating this ProjectMonthCreditBucket.
// Note that you need to call ProjectMonthCreditBucket.Unwrap() before calling this method if this ProjectMonthCreditBucket
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProjectMonthCreditBucket) Update() *ProjectMonthCreditBucketUpdateOne {
	return NewProjectMonthCreditBucketClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProjectMonthCreditBucket entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProjectMonthCreditBucket) Unwrap() *ProjectMonthCreditBucket {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProjectMonthCreditBucket is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProjectMonthCreditBucket) String() string {
	var builder strings.Builder
	builder.WriteString("ProjectMonthCreditBucket(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("month=")
	builder.WriteString(_m.Month.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("quota_milli=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuotaMilli))
	builder.WriteString(", ")
	builder.WriteString("allocated_milli=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllocatedMilli))
	builder.WriteString(", ")
	builder.WriteString("charged_milli=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChargedMilli))
	builder.WriteString(", ")
	builder.WriteString("pending_milli=")
	builder.WriteString(fmt.Sprintf("%v", _m.PendingMilli))
	builder.WriteByte(')')
	return builder.String()
}

// ProjectMonthCreditBuckets is a parsable slice of ProjectMonthCreditBucket.
type ProjectMonthCreditBuckets []*ProjectMonthCreditBucket
