// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/promptaccessaudit"
)

// PromptAccessAuditCreate is the builder for creating a PromptAccessAudit entity.
type PromptAccessAuditCreate struct {
	config
	mutation *PromptAccessAuditMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *PromptAccessAuditCreate) SetCreatedAt(v time.Time) *PromptAccessAuditCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PromptAccessAuditCreate) SetNillableCreatedAt(v *time.Time) *PromptAccessAuditCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetActorUserID sets the "actor_user_id" field.
func (_c *PromptAccessAuditCreate) SetActorUserID(v uuid.UUID) *PromptAccessAuditCreate {
	_c.mutation.SetActorUserID(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *PromptAccessAuditCreate) SetProjectID(v uuid.UUID) *PromptAccessAuditCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_c *PromptAccessAuditCreate) SetNillableProjectID(v *uuid.UUID) *PromptAccessAuditCreate {
	if v != nil {
		_c.SetProjectID(*v)
	}
	return _c
}

// SetMonitoredInputID sets the "monitored_input_id" field.
func (_c *PromptAccessAuditCreate) SetMonitoredInputID(v uuid.UUID) *PromptAccessAuditCreate {
	_c.mutation.SetMonitoredInputID(v)
	return _c
}

// SetNillableMonitoredInputID sets the "monitored_input_id" field if the given value is not nil.
func (_c *PromptAccessAuditCreate) SetNillableMonitoredInputID(v *uuid.UUID) *PromptAccessAuditCreate {
	if v != nil {
		_c.SetMonitoredInputID(*v)
	}
	return _c
}

// SetAccessType sets the "access_type" field.
func (_c *PromptAccessAuditCreate) SetAccessType(v string) *PromptAccessAuditCreate {
	_c.mutation.SetAccessType(v)
	return _c
}

// SetQueryScope sets the "query_scope" field.
func (_c *PromptAccessAuditCreate) SetQueryScope(v map[string]interface{}) *PromptAccessAuditCreate {
	_c.mutation.SetQueryScope(v)
	return _c
}

// SetResultIds sets the "result_ids" field.
func (_c *PromptAccessAuditCreate) SetResultIds(v []string) *PromptAccessAuditCreate {
	_c.mutation.SetResultIds(v)
	return _c
}

// SetResultCount sets the "result_count" field.
func (_c *PromptAccessAuditCreate) SetResultCount(v int) *PromptAccessAuditCreate {
	_c.mutation.SetResultCount(v)
	return _c
}

// SetNillableResultCount sets the "result_count" field if the given value is not nil.
func (_c *PromptAccessAuditCreate) SetNillableResultCount(v *int) *PromptAccessAuditCreate {
	if v != nil {
		_c.SetResultCount(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PromptAccessAuditCreate) SetID(v uuid.UUID) *PromptAccessAuditCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PromptAccessAuditCreate) SetNillableID(v *uuid.UUID) *PromptAccessAuditCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PromptAccessAuditMutation object of the builder.
func (_c *PromptAccessAuditCreate) Mutation() *PromptAccessAuditMutation {
	return _c.mutation
}

// Save creates the PromptAccessAudit in the database.
func (_c *PromptAccessAuditCreate) Save(ctx context.Context) (*PromptAccessAudit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromptAccessAuditCreate) SaveX(ctx context.Context) *PromptAccessAudit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromptAccessAuditCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromptAccessAuditCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromptAccessAuditCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := promptaccessaudit.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ResultCount(); !ok {
		v := promptaccessaudit.DefaultResultCount
		_c.mutation.SetResultCount(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := promptaccessaudit.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromptAccessAuditCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PromptAccessAudit.created_at"`)}
	}
	if _, ok := _c.mutation.ActorUserID(); !ok {
		return &ValidationError{Name: "actor_user_id", err: errors.New(`ent: missing required field "PromptAccessAudit.actor_user_id"`)}
	}
	if _, ok := _c.mutation.AccessType(); !ok {
		return &ValidationError{Name: "access_type", err: errors.New(`ent: missing required field "PromptAccessAudit.access_type"`)}
	}
	if v, ok := _c.mutation.AccessType(); ok {
		if err := promptaccessaudit.AccessTypeValidator(v); err != nil {
			return &ValidationError{Name: "access_type", err: fmt.Errorf(`ent: validator failed for field "PromptAccessAudit.access_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResultCount(); !ok {
		return &ValidationError{Name: "result_count", err: errors.New(`ent: missing required field "PromptAccessAudit.result_count"`)}
	}
	if v, ok := _c.mutation.ResultCount(); ok {
		if err := promptaccessaudit.ResultCountValidator(v); err != nil {
			return &ValidationError{Name: "result_count", err: fmt.Errorf(`ent: validator failed for field "PromptAccessAudit.result_count": %w`, err)}
		}
	}
	return nil
}

func (_c *PromptAccessAuditCreate) sqlSave(ctx context.Context) (*PromptAccessAudit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromptAccessAuditCreate) createSpec() (*PromptAccessAudit, *sqlgraph.CreateSpec) {
	var (
		_node = &PromptAccessAudit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(promptaccessaudit.Table, sqlgraph.NewFieldSpec(promptaccessaudit.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(promptaccessaudit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ActorUserID(); ok {
		_spec.SetField(promptaccessaudit.FieldActorUserID, field.TypeUUID, value)
		_node.ActorUserID = value
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(promptaccessaudit.FieldProjectID, field.TypeUUID, value)
		_node.ProjectID = &value
	}
	if value, ok := _c.mutation.MonitoredInputID(); ok {
		_spec.SetField(promptaccessaudit.FieldMonitoredInputID, field.TypeUUID, value)
		_node.MonitoredInputID = &value
	}
	if value, ok := _c.mutation.AccessType(); ok {
		_spec.SetField(promptaccessaudit.FieldAccessType, field.TypeString, value)
		_node.AccessType = value
	}
	if value, ok := _c.mutation.QueryScope(); ok {
		_spec.SetField(promptaccessaudit.FieldQueryScope, field.TypeJSON, value)
		_node.QueryScope = value
	}
	if value, ok := _c.mutation.ResultIds(); ok {
		_spec.SetField(promptaccessaudit.FieldResultIds, field.TypeJSON, value)
		_node.ResultIds = value
	}
	if value, ok := _c.mutation.ResultCount(); ok {
		_spec.SetField(promptaccessaudit.FieldResultCount, field.TypeInt, value)
		_node.ResultCount = value
	}
	return _node, _spec
}

// PromptAccessAuditCreateBulk is the builder for creating many PromptAccessAudit entities in bulk.
type PromptAccessAuditCreateBulk struct {
	config
	err      error
	builders []*PromptAccessAuditCreate
}

// Save creates the PromptAccessAudit entities in the database.
func (_c *PromptAccessAuditCreateBulk) Save(ctx context.Context) ([]*PromptAccessAudit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PromptAccessAudit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromptAccessAuditMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromptAccessAuditCreateBulk) SaveX(ctx context.Context) []*PromptAccessAudit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromptAccessAuditCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromptAccessAuditCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
