// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/predicate"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/promptaccessaudit"
)

// PromptAccessAuditDelete is the builder for deleting a PromptAccessAudit entity.
type PromptAccessAuditDelete struct {
	config
	hooks    []Hook
	mutation *PromptAccessAuditMutation
}

// Where appends a list predicates to the PromptAccessAuditDelete builder.
func (_d *PromptAccessAuditDelete) Where(ps ...predicate.PromptAccessAudit) *PromptAccessAuditDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PromptAccessAuditDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PromptAccessAuditDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PromptAccessAuditDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(promptaccessaudit.Table, sqlgraph.NewFieldSpec(promptaccessaudit.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PromptAccessAuditDeleteOne is the builder for deleting a single PromptAccessAudit entity.
type PromptAccessAuditDeleteOne struct {
	_d *PromptAccessAuditDelete
}

// Where appends a list predicates to the PromptAccessAuditDelete builder.
func (_d *PromptAccessAuditDeleteOne) Where(ps ...predicate.PromptAccessAudit) *PromptAccessAuditDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PromptAccessAuditDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{promptaccessaudit.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PromptAccessAuditDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
