// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/predicate"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/quotaadjustmentaudit"
)

// QuotaAdjustmentAuditUpdate is the builder for updating QuotaAdjustmentAudit entities.
type QuotaAdjustmentAuditUpdate struct {
	config
	hooks    []Hook
	mutation *QuotaAdjustmentAuditMutation
}

// Where appends a list predicates to the QuotaAdjustmentAuditUpdate builder.
func (_u *QuotaAdjustmentAuditUpdate) Where(ps ...predicate.QuotaAdjustmentAudit) *QuotaAdjustmentAuditUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the QuotaAdjustmentAuditMutation object of the builder.
func (_u *QuotaAdjustmentAuditUpdate) Mutation() *QuotaAdjustmentAuditMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuotaAdjustmentAuditUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuotaAdjustmentAuditUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuotaAdjustmentAuditUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuotaAdjustmentAuditUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *QuotaAdjustmentAuditUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(quotaadjustmentaudit.Table, quotaadjustmentaudit.Columns, sqlgraph.NewFieldSpec(quotaadjustmentaudit.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quotaadjustmentaudit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuotaAdjustmentAuditUpdateOne is the builder for updating a single QuotaAdjustmentAudit entity.
type QuotaAdjustmentAuditUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuotaAdjustmentAuditMutation
}

// Mutation returns the QuotaAdjustmentAuditMutation object of the builder.
func (_u *QuotaAdjustmentAuditUpdateOne) Mutation() *QuotaAdjustmentAuditMutation {
	return _u.mutation
}

// Where appends a list predicates to the QuotaAdjustmentAuditUpdate builder.
func (_u *QuotaAdjustmentAuditUpdateOne) Where(ps ...predicate.QuotaAdjustmentAudit) *QuotaAdjustmentAuditUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuotaAdjustmentAuditUpdateOne) Select(field string, fields ...string) *QuotaAdjustmentAuditUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated QuotaAdjustmentAudit entity.
func (_u *QuotaAdjustmentAuditUpdateOne) Save(ctx context.Context) (*QuotaAdjustmentAudit, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuotaAdjustmentAuditUpdateOne) SaveX(ctx context.Context) *QuotaAdjustmentAudit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuotaAdjustmentAuditUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuotaAdjustmentAuditUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *QuotaAdjustmentAuditUpdateOne) sqlSave(ctx context.Context) (_node *QuotaAdjustmentAudit, err error) {
	_spec := sqlgraph.NewUpdateSpec(quotaadjustmentaudit.Table, quotaadjustmentaudit.Columns, sqlgraph.NewFieldSpec(quotaadjustmentaudit.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "QuotaAdjustmentAudit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quotaadjustmentaudit.FieldID)
		for _, f := range fields {
			if !quotaadjustmentaudit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != quotaadjustmentaudit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &QuotaAdjustmentAudit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quotaadjustmentaudit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
