// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/starprince1234/Nebula-api/internal/infrastructure/db/ent/quotaadjustmentaudit"
)

// QuotaAdjustmentAudit is the model entity for the QuotaAdjustmentAudit schema.
type QuotaAdjustmentAudit struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// OwnerType holds the value of the "owner_type" field.
	OwnerType quotaadjustmentaudit.OwnerType `json:"owner_type,omitempty"`
	// OwnerID holds the value of the "owner_id" field.
	OwnerID uuid.UUID `json:"owner_id,omitempty"`
	// ActorUserID holds the value of the "actor_user_id" field.
	ActorUserID uuid.UUID `json:"actor_user_id,omitempty"`
	// OldQuotaMilli holds the value of the "old_quota_milli" field.
	OldQuotaMilli int64 `json:"old_quota_milli,omitempty"`
	// NewQuotaMilli holds the value of the "new_quota_milli" field.
	NewQuotaMilli int64 `json:"new_quota_milli,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason       string `json:"reason,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*QuotaAdjustmentAudit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case quotaadjustmentaudit.FieldOldQuotaMilli, quotaadjustmentaudit.FieldNewQuotaMilli:
			values[i] = new(sql.NullInt64)
		case quotaadjustmentaudit.FieldOwnerType, quotaadjustmentaudit.FieldReason:
			values[i] = new(sql.NullString)
		case quotaadjustmentaudit.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case quotaadjustmentaudit.FieldID, quotaadjustmentaudit.FieldOwnerID, quotaadjustmentaudit.FieldActorUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the QuotaAdjustmentAudit fields.
func (_m *QuotaAdjustmentAudit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case quotaadjustmentaudit.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case quotaadjustmentaudit.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case quotaadjustmentaudit.FieldOwnerType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_type", values[i])
			} else if value.Valid {
				_m.OwnerType = quotaadjustmentaudit.OwnerType(value.String)
			}
		case quotaadjustmentaudit.FieldOwnerID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value != nil {
				_m.OwnerID = *value
			}
		case quotaadjustmentaudit.FieldActorUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field actor_user_id", values[i])
			} else if value != nil {
				_m.ActorUserID = *value
			}
		case quotaadjustmentaudit.FieldOldQuotaMilli:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field old_quota_milli", values[i])
			} else if value.Valid {
				_m.OldQuotaMilli = value.Int64
			}
		case quotaadjustmentaudit.FieldNewQuotaMilli:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field new_quota_milli", values[i])
			} else if value.Valid {
				_m.NewQuotaMilli = value.Int64
			}
		case quotaadjustmentaudit.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the QuotaAdjustmentAudit.
// This includes values selected through modifiers, order, etc.
func (_m *QuotaAdjustmentAudit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this QuotaAdjustmentAudit.
// Note that you need to call QuotaAdjustmentAudit.Unwrap() before calling this method if this QuotaAdjustmentAudit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *QuotaAdjustmentAudit) Update() *QuotaAdjustmentAuditUpdateOne {
	return NewQuotaAdjustmentAuditClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the QuotaAdjustmentAudit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *QuotaAdjustmentAudit) Unwrap() *QuotaAdjustmentAudit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: QuotaAdjustmentAudit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *QuotaAdjustmentAudit) String() string {
	var builder strings.Builder
	builder.WriteString("QuotaAdjustmentAudit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("owner_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerType))
	builder.WriteString(", ")
	builder.WriteString("owner_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerID))
	builder.WriteString(", ")
	builder.WriteString("actor_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActorUserID))
	builder.WriteString(", ")
	builder.WriteString("old_quota_milli=")
	builder.WriteString(fmt.Sprintf("%v", _m.OldQuotaMilli))
	builder.WriteString(", ")
	builder.WriteString("new_quota_milli=")
	builder.WriteString(fmt.Sprintf("%v", _m.NewQuotaMilli))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteByte(')')
	return builder.String()
}

// QuotaAdjustmentAudits is a parsable slice of QuotaAdjustmentAudit.
type QuotaAdjustmentAudits []*QuotaAdjustmentAudit
